/** Digital cards: the gallery, the editor, downloads, orders. Merged into the English catalog. */
export const enCards = {
  'nav.cards': 'Cards',

  // Gallery
  'cards.gallery.eyebrow': '{count} invitation cards',
  'cards.gallery.title': 'Personalised digital invitation cards',
  'cards.gallery.subtitle': 'Pick a design, make it yours in the editor and download it for WhatsApp, Instagram or print. Free with a small watermark, or {price} without it. No sign-up.',
  'cards.gallery.step1': 'Pick a design',
  'cards.gallery.step1Body': 'Weddings, engagements, haldi, mehendi, birthdays, pujas and more.',
  'cards.gallery.step2': 'Make it yours',
  'cards.gallery.step2Body': 'Names, date, venue, colours, fonts, photos and the size, right on the card.',
  'cards.gallery.step3': 'Download',
  'cards.gallery.step3Body': 'Free with a small watermark, or {price} for the clean card, emailed to you too.',
  'cards.gallery.heading': 'Card designs',
  'cards.gallery.search': 'Search designs',
  'cards.gallery.searchPlaceholder': 'Search: peacock, floral, South Indian, birthday…',
  'cards.gallery.searchButton': 'Search',
  'cards.gallery.sort': 'Sort',
  'cards.gallery.sort.featured': 'Featured',
  'cards.gallery.sort.new': 'Newest',
  'cards.gallery.sort.name': 'Name (A–Z)',
  'cards.gallery.occasion': 'Occasion',
  'cards.gallery.style': 'Style',
  'cards.style.royal': 'Royal',
  'cards.style.floral': 'Floral',
  'cards.style.traditional': 'Traditional',
  'cards.style.modern': 'Modern',
  'cards.style.minimal': 'Minimal',
  'cards.style.pastel': 'Pastel',
  'cards.style.luxury': 'Luxury',
  'cards.style.festive': 'Festive',
  'cards.style.night': 'Night sky',
  'cards.style.romantic': 'Romantic',
  'cards.style.kids': 'For children',
  'cards.style.photo': 'With your photo',
  'cards.gallery.customize': 'Customize card',
  'cards.gallery.customizeNamed': 'Customize the {name} card',
  'cards.gallery.new': 'New',
  'cards.gallery.continue': 'Continue your card',
  'cards.gallery.purchases': 'Cards you bought',
  'cards.gallery.findPurchase': 'Bought on another device? Find your card',
  'cards.gallery.showing': 'Showing {shown} of {total} designs',
  'cards.gallery.showMore': 'Show more designs ({count} more)',
  'cards.gallery.emptyTitle': 'No designs match',
  'cards.gallery.emptyBody': 'Try another occasion or a shorter search.',

  // Editor
  'cards.editor.back': 'All card designs',
  'cards.editor.undo': 'Undo',
  'cards.editor.redo': 'Redo',
  'cards.editor.reset': 'Reset to the original template',
  'cards.editor.zoomIn': 'Zoom in',
  'cards.editor.zoomOut': 'Zoom out',
  'cards.editor.fit': 'Fit to screen',
  'cards.editor.preview': 'Preview the final card',
  'cards.editor.edit': 'Back to editing',
  'cards.editor.download': 'Download',
  'cards.editor.tools': 'Editing tools',
  'cards.editor.canvas': 'Your card',
  'cards.editor.canvasHint': 'Tap anything on the card to change it. Drag to move, use the handles to resize and rotate.',
  'cards.editor.inspector': 'Selected element',
  'cards.editor.closeSheet': 'Close',
  'cards.editor.foldSheet': 'Fold down to see more of the card',
  'cards.editor.unfoldSheet': 'Show the settings',
  'cards.editor.saving': 'Saving…',
  'cards.editor.saved': 'Saved',
  'cards.editor.savedDevice': 'Saved on this device',
  'cards.editor.saveFailed': 'Not saved online yet (kept on this device)',
  'cards.editor.notSaved': 'Your card could not be saved. Check your connection and try again.',
  'cards.editor.watermarkPreview': 'Show the free card’s watermark',

  'cards.panel.details': 'Details',
  'cards.panel.text': 'Text',
  'cards.panel.colors': 'Colours',
  'cards.panel.photos': 'Photos',
  'cards.panel.elements': 'Elements',
  'cards.panel.size': 'Size',

  'cards.details.intro': 'Fill these in once: the card’s names, date and venue update as you type. Change any text on the card itself to word it your way.',
  'cards.details.occasion': 'Occasion',
  'cards.details.occasionConfirm': 'Start this design again with the wording for that occasion? Your details are kept.',
  'cards.details.language': 'Language',
  'cards.details.people': 'Who is it for',
  'cards.details.bride': 'Bride’s name',
  'cards.details.groom': 'Groom’s name',
  'cards.details.honoree': 'Name',
  'cards.details.eventTitle': 'Event title',
  'cards.details.family': 'Parents’ or family names',
  'cards.details.when': 'When',
  'cards.details.date': 'Date',
  'cards.details.time': 'Time',
  'cards.details.where': 'Where',
  'cards.details.venue': 'Venue',
  'cards.details.address': 'Address',
  'cards.details.city': 'City',
  'cards.details.messageTitle': 'Invitation message',
  'cards.details.message': 'A line for your guests',
  'cards.details.addToCard': 'Add to card',
  'cards.details.functions': 'Functions',
  'cards.details.functionName': 'Function {n}',
  'cards.details.functionAdd': 'Add a function',
  'cards.details.functionRemove': 'Remove function {n}',

  'cards.text.add': 'Add text',
  'cards.text.preset.heading': 'Heading',
  'cards.text.preset.subheading': 'Small capitals',
  'cards.text.preset.body': 'Paragraph',
  'cards.text.preset.script': 'Script',
  'cards.text.sample.heading': 'Your heading',
  'cards.text.sample.subheading': 'Save the date',
  'cards.text.sample.body': 'Write a few words for your guests here.',
  'cards.text.sample.script': 'With love',
  'cards.text.onCard': 'Text on the card',
  'cards.text.onCardHint': 'Edit any line here or on the card. Long names shrink to fit their space.',
  'cards.text.linked': 'Follows your Details. Typing here changes only this line.',
  'cards.text.styleIt': 'Font, size and colour',

  'cards.palette.primary': 'Main',
  'cards.palette.secondary': 'Ornaments',
  'cards.palette.accent': 'Accent',
  'cards.palette.background': 'Background',
  'cards.palette.surface': 'Panels',
  'cards.palette.text': 'Text',
  'cards.palette.muted': 'Soft text',
  'cards.color.none': 'No colour',
  'cards.color.custom': 'Any colour',
  'cards.colors.palettes': 'Colour palettes',
  'cards.colors.palettesHint': 'Recolours the whole card at once.',
  'cards.colors.templateColors': 'Template colours',
  'cards.colors.palette': 'Card colours',
  'cards.colors.restore': 'Restore',
  'cards.colors.readable': 'Text colours are adjusted automatically so they stay readable on what is behind them.',
  'cards.colors.background': 'Card background',
  'cards.colors.bg.template': 'Template',
  'cards.colors.bg.color': 'Colour',
  'cards.colors.bg.gradient': 'Gradient',
  'cards.colors.bg.from': 'From',
  'cards.colors.bg.to': 'To',
  'cards.colors.sections': 'To colour a band, panel or decoration on its own, select it on the card.',

  'cards.photos.add': 'Add a photo',
  'cards.photos.uploading': 'Uploading…',
  'cards.photos.spots': 'Photos on the card',
  'cards.photos.spotsHint': 'Select a photo to crop, zoom or reshape it.',
  'cards.photos.none': 'This design has no photo yet. Add one and place it anywhere.',
  'cards.photos.select': 'Select this photo',
  'cards.photos.empty': 'No photo yet',
  'cards.photos.upload': 'Upload',
  'cards.photos.replace': 'Replace',
  'cards.photos.remove': 'Remove the photo',
  'cards.photos.full': 'This card already has as many photos as it can hold.',
  'cards.photos.type': 'Use a JPEG, PNG or WebP photo.',
  'cards.photos.size': 'Photos can be up to 15 MB.',
  'cards.photos.failed': 'That photo could not be added. Please try again.',
  'cards.photos.private': 'Photos are stored privately and only appear in your card.',

  'cards.elements.decorations': 'Decorations',
  'cards.elements.shapes': 'Shapes',
  'cards.elements.addNamed': 'Add {name}',
  'cards.elements.layers': 'Layers',
  'cards.elements.layersHint': 'Top of the list is in front. Hide, lock or reorder anything here.',

  'cards.size.title': 'Card size',
  'cards.size.hint': 'The design rearranges itself to fit. Undo brings back the previous size.',
  'cards.size.reset': 'Start over',
  'cards.size.resetHint': 'Brings back the original design. Your details are kept.',
  'cards.size.resetButton': 'Reset to the original template',
  'cards.size.resetConfirm': 'Reset the card to the original template? Your details are kept, and Undo can bring your design back.',

  'cards.format.phone': 'Phone',
  'cards.format.phone.use': 'WhatsApp and phones',
  'cards.format.story': 'Story',
  'cards.format.story.use': 'WhatsApp status, Instagram stories',
  'cards.format.portrait': 'Portrait 5 × 7',
  'cards.format.portrait.use': 'Printed cards',
  'cards.format.square': 'Square',
  'cards.format.square.use': 'Instagram and Facebook posts',
  'cards.format.landscape': 'Landscape',
  'cards.format.landscape.use': 'Screens and email',

  'cards.inspector.nothing': 'Nothing selected',
  'cards.inspector.nothingHint': 'Tap any text, photo or decoration on the card to change it here. Double-click text to type straight away.',
  'cards.inspector.text': 'Text',
  'cards.inspector.photo': 'Photo',
  'cards.inspector.shape': 'Shape',
  'cards.inspector.decoration': 'Decoration',
  'cards.inspector.done': 'Done',
  'cards.inspector.arrange': 'Arrange',
  'cards.inspector.words': 'Text',
  'cards.inspector.font': 'Font',
  'cards.inspector.fontRoles': 'The design’s fonts',
  'cards.inspector.fontRole.heading': 'Heading',
  'cards.inspector.fontRole.body': 'Body',
  'cards.inspector.fontRole.script': 'Script',
  'cards.inspector.fontFamilies': 'All fonts (Hindi included)',
  'cards.inspector.size': 'Size',
  'cards.inspector.bold': 'Bold',
  'cards.inspector.italic': 'Italic',
  'cards.inspector.alignLeft': 'Align left',
  'cards.inspector.alignCenter': 'Centre',
  'cards.inspector.alignRight': 'Align right',
  'cards.inspector.color': 'Colour',
  'cards.inspector.spacing': 'Spacing',
  'cards.inspector.lineHeight': 'Line spacing',
  'cards.inspector.letterSpacing': 'Letter spacing',
  'cards.inspector.effects': 'Style',
  'cards.inspector.case': 'Letters',
  'cards.inspector.case.none': 'As typed',
  'cards.inspector.case.upper': 'CAPITALS',
  'cards.inspector.shadow': 'Shadow',
  'cards.inspector.shadow.none': 'None',
  'cards.inspector.shadow.soft': 'Soft',
  'cards.inspector.shadow.glow': 'Glow',
  'cards.inspector.shadow.hard': 'Hard',
  'cards.inspector.foil': 'Metallic foil',
  'cards.inspector.overflow': 'Long text',
  'cards.inspector.overflow.shrink': 'Shrink to fit',
  'cards.inspector.overflow.wrap': 'Wrap lines',
  'cards.inspector.crop': 'Crop',
  'cards.inspector.cropHint': 'Zoom in, then move the focus to choose what shows.',
  'cards.inspector.fit': 'Fit',
  'cards.inspector.fit.cover': 'Fill the frame',
  'cards.inspector.fit.contain': 'Whole photo',
  'cards.inspector.zoom': 'Zoom',
  'cards.inspector.focusX': 'Focus left – right',
  'cards.inspector.focusY': 'Focus top – bottom',
  'cards.inspector.flipX': 'Flip sideways',
  'cards.inspector.flipY': 'Flip upside down',
  'cards.inspector.frame': 'Frame',
  'cards.inspector.radius': 'Corner rounding',
  'cards.inspector.border': 'Border',
  'cards.inspector.borderColor': 'Border colour',
  'cards.inspector.brightness': 'Brightness',
  'cards.inspector.fill': 'Fill',
  'cards.inspector.solidFill': 'Use a single colour',
  'cards.inspector.outline': 'Outline',
  'cards.inspector.outlineColor': 'Outline colour',
  'cards.inspector.sky': 'Show the sky',
  'cards.inspector.placement': 'Placement',
  'cards.inspector.rotation': 'Rotation',
  'cards.inspector.opacity': 'Opacity',

  'cards.mask.none': 'Square',
  'cards.mask.rounded': 'Rounded',
  'cards.mask.circle': 'Circle',
  'cards.mask.ellipse': 'Oval',
  'cards.mask.arch': 'Arch',
  'cards.mask.diamond': 'Diamond',
  'cards.mask.leaf': 'Leaf',

  'cards.layer.duplicate': 'Duplicate',
  'cards.layer.front': 'Bring to front',
  'cards.layer.back': 'Send to back',
  'cards.layer.up': 'Move forward',
  'cards.layer.down': 'Move backward',
  'cards.layer.lock': 'Lock in place',
  'cards.layer.unlock': 'Unlock',
  'cards.layer.hide': 'Hide',
  'cards.layer.show': 'Show',
  'cards.layer.delete': 'Delete',

  // Download
  'cards.download.title': 'Download your card',
  'cards.download.subtitle': 'Choose how you would like it. Your design stays as it is either way.',
  'cards.download.close': 'Close and keep editing',
  'cards.download.back': 'Back',
  'cards.download.plan': 'Included in your plan',
  'cards.download.planNamed': 'Included in your {plan} plan',
  'cards.download.planBody': 'Your plan covers watermark-free cards. Download it now: nothing to fill in.',
  'cards.download.planButton': 'Download without watermark',
  'cards.download.freeTitle': 'Free download',
  'cards.download.freePrice': '₹0',
  'cards.download.freePoint1': 'With a small Bulava watermark at the bottom',
  'cards.download.freePoint2': 'Just your WhatsApp number',
  'cards.download.freePoint3': 'Full size, ready to share',
  'cards.download.freeButton': 'Download free',
  'cards.download.paidTitle': 'Without watermark',
  'cards.download.paidPrice': '{price} per card',
  'cards.download.paidPoint1': 'No watermark: just your card',
  'cards.download.paidPoint2': 'High-quality image, the same size and look',
  'cards.download.paidPoint3': 'Emailed to you, downloadable again any time',
  'cards.download.paidButton': 'Remove watermark · {price}',
  'cards.download.paidUnavailable': 'Payments are unavailable right now',
  'cards.download.freeFormTitle': 'Your Invitation Card Is Ready!',
  'cards.download.freeFormBody': 'Enter your WhatsApp number to download your personalized invitation card for free.',
  'cards.download.phone': 'WhatsApp / mobile number',
  'cards.download.phoneInvalid': 'Enter a valid mobile number, for example 98765 43210.',
  'cards.download.offers': 'Send me offers and new designs on WhatsApp (optional; you can stop them any time).',
  'cards.download.freePrivacy': 'We keep your number with your download so we can help if anything goes wrong. It is never shown on the card or shared, and we message you about offers only if you tick the box above.',
  'cards.download.privacyLink': 'Privacy policy',
  'cards.download.watermarkNote': 'The free card has a small Bulava watermark across the bottom.',
  'cards.download.continue': 'Continue to download',
  'cards.download.upsell': 'Rather have it without the watermark? {price}',
  'cards.download.paidFormTitle': 'Your card, without the watermark',
  'cards.download.paidFormBody': 'We email the card to you, and your number and name stay with the order in case you need help with it later.',
  'cards.download.name': 'Full name',
  'cards.download.nameInvalid': 'Enter your full name.',
  'cards.download.email': 'Email address',
  'cards.download.emailHint': 'Your card and receipt are sent here.',
  'cards.download.emailInvalid': 'Enter a valid email address.',
  'cards.download.termsBefore': 'I agree to the',
  'cards.download.terms': 'Terms of Service',
  'cards.download.termsAnd': 'and the',
  'cards.download.refund': 'Refund and Cancellation Policy',
  'cards.download.termsRequired': 'Please accept the Terms of Service and the Refund and Cancellation Policy.',
  'cards.download.paidPrivacy': 'Your name, email and number are used for this order and its receipt only.',
  'cards.download.payable': 'Amount payable',
  'cards.download.pay': 'Pay {price}',
  'cards.download.secure': 'Secure payment by Razorpay: UPI, cards, net banking and wallets.',
  'cards.download.payFailed': 'The payment did not go through. Nothing was charged for this card: you can try again.',
  'cards.download.payCancelled': 'The payment was not completed. Your card is safe: try again whenever you are ready.',
  'cards.download.making': 'Making your card…',
  'cards.download.makingBody': 'This takes a few seconds. Please keep this window open.',
  'cards.download.readyTitle': 'Your card is ready',
  'cards.download.readyFree': 'Here is your card with the Bulava watermark. Download it below.',
  'cards.download.readyPlan': 'Here is your card, without the watermark. Download it below.',
  'cards.download.readyPlanSaved': 'Your card, without the watermark, is downloading. If it does not start, use the button below.',
  'cards.download.otherWays': 'See the other ways to download',
  'cards.download.save': 'Download card ({width} × {height} px)',
  'cards.download.upgradeTitle': 'Want it without the watermark?',
  'cards.download.upgradeBody': 'Get the same card, clean, for {price}. We email it to you too.',
  'cards.download.keepEditing': 'Back to editing',
  'cards.download.failedTitle': 'We could not make your card',
  'cards.download.failed': 'Something went wrong while making the image. Your design is safe: please try again.',
  'cards.download.slow': 'This is taking longer than usual. Your design is safe: try again in a moment.',
  'cards.download.tryAgain': 'Try again',
  'cards.download.orderFootnote': 'This page and the email both let you download your card again.',

  // Orders
  'cards.order.title': 'Your invitation card',
  'cards.order.description': 'Watermark-free invitation card',
  'cards.order.loading': 'Opening your order…',
  'cards.order.notFound': 'We could not find this order. Check the link in your email, or find your card with your email and number.',
  'cards.order.noLink': 'Open your card from its link',
  'cards.order.noLinkBody': 'Use the link in the email we sent after your purchase, or find your card with your email and number.',
  'cards.order.confirming': 'Confirming your payment…',
  'cards.order.confirmingBody': 'This usually takes a few seconds. Please do not pay again: this page updates as soon as your bank confirms.',
  'cards.order.notPaid': 'Payment not completed',
  'cards.order.notPaidBody': 'Reason: {reason}. Your card is safe, and nothing was charged for it.',
  'cards.order.closedBody': 'The payment window was closed before paying. Your card is safe, and nothing was charged for it.',
  'cards.order.payAgain': 'Pay {amount}',
  'cards.order.payFailed': 'The payment did not go through. You can try again.',
  'cards.order.readyTitle': 'Your Invitation Card Is Ready!',
  'cards.order.readyBody': 'Your payment was successful. You can now download your watermark-free invitation card. We’ve also sent a copy to your email address.',
  'cards.order.makingTitle': 'Payment successful',
  'cards.order.makingBody': 'We are making your watermark-free card now. It appears here in a few seconds, and we email it to you.',
  'cards.order.failedTitle': 'Your card needs another try',
  'cards.order.failedBody': 'Your payment is safe, but the image could not be made. Make it again: you will not be charged again.',
  'cards.order.regenerate': 'Make my card again',
  'cards.order.download': 'Download watermark-free card',
  'cards.order.previewAlt': 'Your watermark-free invitation card',
  'cards.order.emailTitle': 'Email',
  'cards.order.emailWaiting': 'We will email the card to {email} as soon as it is ready.',
  'cards.order.emailQueued': 'Sending the card to {email}…',
  'cards.order.emailSent': 'Sent to {email}. Check your spam folder if you cannot see it.',
  'cards.order.emailFailed': 'We could not email it to {email}. You can download it here, or try again.',
  'cards.order.emailRetry': 'Try emailing it again',
  'cards.order.emailAgain': 'Email it again',
  'cards.order.reference': 'Order',
  'cards.order.amount': 'Amount',
  'cards.order.paidOn': 'Paid on',
  'cards.order.payment': 'Payment ID',
  'cards.order.size': 'Image size',
  'cards.order.keepLink': 'Keep this page’s link to download your card again later.',
  'cards.order.copyLink': 'Copy the link',
  'cards.order.refunded': 'This order was refunded, so the card can no longer be downloaded here.',
  'cards.order.expired': 'This checkout was not completed. Your card is still in the editor on the device you made it on.',

  // Recovery
  'cards.recover.eyebrow': 'Digital cards',
  'cards.recover.title': 'Find a card you bought',
  'cards.recover.body': 'Enter the email and mobile number you used at checkout. We email you a link to each card bought with them.',
  'cards.recover.onDevice': 'Bought on this device',
  'cards.recover.submit': 'Email me the links',
  'cards.recover.sentTitle': 'Check your email',
  'cards.recover.sentBody': 'If cards were bought with these details, the links are on their way. They usually arrive within a minute.',

  // Errors
  'error.CARDS_UNAVAILABLE': 'Digital cards are not available right now. Please try again later.',
  'error.CARD_SESSION_EXPIRED': 'This card is no longer saved here. Start again from the design.',
  'error.CARD_NOT_READY': 'Your card is not ready yet. Please wait a moment and try again.',
  'error.CARD_PLAN_REQUIRED': 'Your plan does not include watermark-free cards.',
} as const;
