/** Host dashboard copy. Merged into the English catalog. */
export const enDashboard = {
  'dash.nav.design': 'Design',
  'dash.nav.video': 'Video & cards',
  'dash.nav.photos': 'Photos',
  'dash.nav.updates': 'Updates',
  'dash.nav.checkin': 'Check-in',
  'dash.nav.settings': 'Settings',
  'dash.nav.upgrade': 'Upgrade',
  'dash.nav.account': 'Account',
  'dash.nav.events': 'My events',
  'dash.nav.viewSite': 'Open live site',
  'dash.plan.free': 'Free plan',
  'dash.plan.paid': '{plan} plan',
  'dash.greeting': 'Namaste, {name}',
  'dash.newEvent.subtitle': 'Pick the occasion and we will set up suggested functions and guest groups for you.',

  'dash.checklist.title': 'Get your invitation ready',
  'dash.checklist.design': 'Choose a design',
  'dash.checklist.functions': 'Add functions and venues',
  'dash.checklist.guests': 'Add your guests',
  'dash.checklist.invite': 'Create invitation links',
  'dash.checklist.publish': 'Publish your event',
  'dash.checklist.share': 'Share on WhatsApp',
  'dash.stats.guests': 'Guests',
  'dash.stats.invited': 'Invitations',
  'dash.stats.opened': 'Opened',
  'dash.stats.attending': 'Attending',

  'design.title': 'Invitation design',
  'design.subtitle': 'Choose how your invitation looks. Guests see your names, functions and photos in this design.',
  'design.current': 'Current design',
  'design.default': 'Default design',
  'design.choose': 'Choose',
  'design.chosen': 'In use',
  'design.locked': 'Upgrade to use',
  'design.colors': 'Colours',
  'design.words': 'Your words',
  'design.photos': 'Photos',
  'design.photos.hint': 'Choose up to {count} approved photos from your albums.',
  'design.photos.none': 'Upload photos in the Photos tab to use them here.',
  'design.saved': 'Design saved.',
  'design.preview': 'Live preview',
  'design.filter.suggested': 'Suggested for this event',
  'design.tab.style': 'Style',
  'design.tab.photos': 'Photos',
  'design.tab.words': 'Words',
  'design.tab.motion': 'Motion & music',
  'design.tab.sections': 'Sections',
  'design.colors.presets': 'Palettes made for this design',
  'design.colors.custom': 'Your own colours',
  'design.colors.reset': 'Reset colours',
  'design.colors.note': 'Pick any colours: text adjusts automatically so your invitation stays easy to read.',
  'design.color.primary': 'Main',
  'design.color.secondary': 'Second',
  'design.color.accent': 'Accent',
  'design.color.background': 'Background',
  'design.fonts': 'Typography',
  'design.fonts.note': 'Each pairing includes a matching Hindi typeface.',
  'design.fonts.template': 'Designer’s choice',
  'design.photo.cover': 'Cover photo',
  'design.photo.partnerOne': 'First partner / honoree',
  'design.photo.partnerTwo': 'Second partner',
  'design.photo.story': 'Story photo',
  'design.photo.closing': 'Closing photo',
  'design.photo.upload': 'Upload',
  'design.photo.choose': 'Choose from album',
  'design.photo.remove': 'Remove',
  'design.photo.uploading': 'Uploading and preparing…',
  'design.photo.empty': 'No photo yet',
  'design.photo.failed': 'That photo could not be used. Try a JPG or PNG under 25 MB.',
  'design.photo.extra': 'More photos for the gallery',
  'design.photo.extraHint': 'Shown in the gallery until guests share their own. Up to {count}.',
  'design.photo.note': 'Photos you place here appear wherever this invitation is shown.',
  'design.motion.opening': 'Opening',
  'design.motion.openingNote': 'Plays once when a guest opens the invitation.',
  'design.motion.none': 'No opening',
  'design.motion.effect': 'Ambient effect',
  'design.motion.effectNote': 'Gentle movement over the page. Guests who turn off animations never see it.',
  'design.sections.note': 'Hide the parts you do not need. The opening section always shows; empty sections hide themselves.',
  'design.section.hero': 'Opening',
  'design.section.couple': 'The couple',
  'design.section.parents': 'Families',
  'design.section.family': 'Blessings',
  'design.section.story': 'Story',
  'design.section.countdown': 'Countdown',
  'design.section.eventTimeline': 'Schedule',
  'design.section.gallery': 'Gallery',
  'design.section.venue': 'Venue',
  'design.section.map': 'Map',
  'design.section.rsvp': 'RSVP',
  'design.section.accommodation': 'Stay',
  'design.section.travel': 'Travel',
  'design.section.giftRegistry': 'Gifts',
  'design.section.announcements': 'Updates',
  'design.section.photoShare': 'Photo sharing',
  'design.section.menu': 'Menu',
  'design.section.quote': 'Verse',
  'design.section.footer': 'Closing',
  'design.section.canvas': 'Designed section',
  'design.watermarked': 'This design is beyond your plan: the invitation shows a watermark until you upgrade. You can design and preview it fully.',
  'design.watermarked.cta': 'Upgrade to publish without the mark',

  // Provisional (WhatsApp-only) accounts
  'claim.banner': 'Your work is saved under your WhatsApp number. Secure your account to publish, invite guests and pay.',
  'claim.banner.cta': 'Secure my account',
  'claim.title': 'Secure your account',
  'claim.subtitle': 'Your invitation is saved under {phone}. Add a way to sign in again, then you can publish, invite guests and upgrade.',
  'claim.subtitle.noPhone': 'Add a way to sign in again, then you can publish, invite guests and upgrade.',
  'claim.whatsapp.title': 'Verify with WhatsApp',
  'claim.whatsapp.body': 'We send a 6-digit code to your WhatsApp number. That is all it takes.',
  'claim.whatsapp.send': 'Send me a code',
  'claim.whatsapp.sent': 'Code sent to {target}.',
  'claim.whatsapp.code': 'Code from WhatsApp',
  'claim.whatsapp.verify': 'Verify',
  'claim.email.title': 'Add an email and password',
  'claim.email.body': 'Sign in from any device and receive receipts on email.',
  'claim.email.submit': 'Save and secure',
  'claim.google.title': 'Or continue with Google',
  'claim.publishFirst': 'Publishing needs a secured account.',

  // The preview link
  'share.preview.title': 'Preview link',
  'share.preview.body': 'Works before publishing and whatever the access settings. It shows a “Preview” mark and nobody can RSVP from it. Share it with family to choose the design together.',
  'share.preview.copy': 'Copy preview link',
  'share.preview.open': 'Open preview',
  'share.preview.replace': 'New preview link',
  'share.preview.replaced': 'The old preview link no longer works.',
  'dash.nav.preview': 'Preview link',

  // Sign-in and sign-up with a WhatsApp number
  'auth.field.phone': 'WhatsApp number (optional)',
  'auth.field.phoneHint': 'For your preview links and, if you like, updates. Indian numbers need no country code.',
  'auth.field.whatsappUpdates': 'Send me updates about my invitations on WhatsApp',
  'auth.phone.body': 'Enter the number you used and we send a 6-digit code.',
  'auth.phone.number': 'WhatsApp number',
  'auth.phone.send': 'Send code',
  'auth.phone.sent': 'If this number has an account, a code is on its way to {target}.',
  'auth.phone.code': 'Code',
  'auth.phone.verify': 'Verify and sign in',
  'auth.phone.useEmail': 'Sign in with email instead',
  'auth.phone.usePhone': 'Sign in with your WhatsApp number',
  'auth.phone.change': 'Change number',
  'account.phone': 'WhatsApp number',
  'account.phone.hint': 'Used for preview links and sign-in codes.',
  'account.whatsappUpdates': 'Updates on WhatsApp',
  'account.whatsappUpdates.hint': 'Occasional messages about your invitations. You can switch this off any time.',
  'account.saveProfile': 'Save profile',
  'account.profileSaved': 'Profile saved.',
  'effect.none': 'None',
  'effect.petals': 'Rose petals',
  'effect.marigold': 'Marigold petals',
  'effect.goldDust': 'Gold dust',
  'effect.fireflies': 'Fireflies',
  'effect.confetti': 'Confetti',
  'effect.lanterns': 'Sky lanterns',
  'effect.snow': 'Snowfall',

  'video.title': 'Video invitations & image cards',
  'video.subtitle': 'Turn your details into a short 9:16 film or a 4:5 image card. Rendering takes a few minutes.',
  'video.create': 'Create',
  'video.customize': 'Make it yours: colours, fonts and your photo',
  'video.queue': 'Your renders',
  'video.empty': 'No renders yet.',
  'video.status.QUEUED': 'Waiting',
  'video.status.PROCESSING': 'Rendering {progress}%',
  'video.status.COMPLETED': 'Ready',
  'video.status.FAILED': 'Failed',
  'video.status.CANCELLED': 'Cancelled',
  'video.download': 'Download',
  'video.cancel': 'Cancel',
  'video.watermark': 'Includes Bulava mark (Free plan)',
  'video.music': 'Music',
  'video.music.none': 'No music',

  'photos.title': 'Photo album',
  'photos.subtitle': 'One album for the whole event: one QR code and link for uploads, one gallery for guests and one live wall. Every function has its own folder.',
  'photos.create': 'Create album',
  'photos.name': 'Album name',
  'photos.function': 'For function',
  'photos.allFunctions': 'Whole event',
  'photos.visibility': 'Who can view the gallery',
  'photos.visibility.PUBLIC': 'Anyone with the album link',
  'photos.visibility.INVITE_ONLY': 'Invited guests',
  'photos.visibility.FUNCTION_RESTRICTED': 'Guests see the folders of their functions',
  'photos.visibility.PRIVATE': 'Only hosts',
  'photos.moderation': 'Approval',
  'photos.moderation.AUTO_APPROVE': 'Show immediately',
  'photos.moderation.MANUAL_APPROVAL': 'Approve before showing',
  'photos.downloads': 'Guests can download',
  'photos.original': 'Allow original quality',
  'photos.uploadsOpen': 'Uploads open',
  'photos.qr': 'QR code',
  'photos.printQr': 'Print QR',
  'photos.copyLink': 'Copy upload link',
  'photos.items': '{count} photos',
  'photos.pending': 'Waiting for approval',
  'photos.approve': 'Approve',
  'photos.reject': 'Reject',
  'photos.empty': 'No photos yet.',
  'wall.enable': 'Live photo wall',
  'wall.hint': 'Show the album as a full-screen slideshow on a TV or projector at the venue, from the folders marked “On live wall”. New photos appear within seconds.',
  'wall.moderationTip': 'Tip: choose “Approve before showing” when the wall is on a big screen.',
  'wall.open': 'Open the wall',
  'wall.copy': 'Copy wall link',
  'wall.rotate': 'New link',
  'wall.rotateConfirm': 'Create a new wall link? Screens using the old link stop updating.',

  'updates.title': 'Updates to guests',
  'updates.subtitle': 'Post a change or reminder. It appears on each guest’s invitation and is emailed to guests with an email address.',
  'updates.new': 'New update',
  'updates.field.title': 'Title',
  'updates.field.body': 'Message',
  'updates.audience': 'Send to',
  'updates.audience.all': 'All guests',
  'updates.audience.function': 'Guests of a function',
  'updates.audience.group': 'A guest group',
  'updates.send': 'Publish update',
  'updates.email': 'Also email guests who have an email address',
  'updates.sent': 'Update published to {count} guests.',
  'updates.empty': 'No updates yet.',

  'checkin.dash.title': 'Event-day check-in',
  'checkin.dash.subtitle': 'Every guest’s invitation shows a QR pass. Staff scan it with their phone camera and check guests in here.',
  'checkin.dash.expected': 'Expected',
  'checkin.dash.arrived': 'Arrived',
  'checkin.dash.guests': 'Guests',
  'checkin.dash.manual': 'Enter a guest code',
  'checkin.dash.open': 'Open',

  'settings.title': 'Event settings',
  'settings.access': 'Access & privacy',
  'settings.pin': 'PIN for private-link events',
  'settings.pin.set': 'Set PIN',
  'settings.pin.remove': 'Remove PIN',
  'settings.pin.active': 'A PIN is set.',
  'settings.otp': 'Ask guests to confirm with a one-time code',
  'settings.visibility': 'List this event publicly (public events only)',
  'settings.publicLink': 'Public page',
  'settings.exports': 'Exports',
  'settings.export.guests': 'Guest list (CSV)',
  'settings.export.rsvps': 'RSVPs (CSV)',
  'settings.export.invitations': 'Invitation report (CSV)',
  'settings.export.attendance': 'Attendance (CSV)',
  'settings.export.media': 'Photo list (CSV)',
  'settings.clone': 'Duplicate event',
  'settings.clone.body': 'Copies functions, groups, design and questions. Guests are never copied.',
  'settings.clone.title': 'New event name',
  'settings.danger': 'Danger zone',
  'settings.delete': 'Delete event',
  'settings.delete.body': 'All invitation links stop working immediately.',
  'settings.delete.confirm': 'Type the event name to confirm',
  'settings.status': 'Event status',
  'settings.complete': 'Mark as completed',
  'settings.archive': 'Archive',

  'upgrade.title': 'Upgrade this event',
  'upgrade.subtitle': 'One-time payment for this event. Pay by UPI, card or net banking.',
  'upgrade.coupon': 'Coupon code',
  'upgrade.pay': 'Pay {amount}',
  'upgrade.unavailable': 'Online payment is not available right now.',
  'upgrade.history': 'Payments',
  'upgrade.included': 'Included',
  'upgrade.consent.before': 'I agree to the',
  'upgrade.consent.refund': 'Refund and Cancellation Policy',
  'upgrade.consent.after': ', and I understand the plan starts as soon as the payment is confirmed. Prices include GST.',
  'upgrade.consent.required': 'Tick the box to continue to payment.',
  'upgrade.consent.secure': 'You pay on Razorpay’s secure checkout by UPI, card, net banking or wallet. Bulava never sees your card or bank details.',

  // Payment history (/dashboard/payments)
  'payments.title': 'Payment history',
  'payments.subtitle': 'Every plan you have bought for your events or your account. Open one for its receipt and status.',
  'payments.totalPaid': 'Total paid',
  'payments.count': 'Successful payments',
  'payments.complimentary': 'Complimentary',
  'payments.emptyTitle': 'No payments yet',
  'payments.emptyBody': 'When you upgrade an event, the payment and its receipt appear here.',
  'payments.emptyCta': 'Go to my events',
  'payments.help': 'Need a refund or a GST invoice? Our',
  'payments.refundPolicy': 'refund and cancellation policy explains how',
  'dash.nav.payments': 'Payments',

  // Payment status page (/dashboard/payments/:orderId)
  'payment.status.CREATED': 'Pending',
  'payment.status.PAID': 'Paid',
  'payment.status.FAILED': 'Failed',
  'payment.status.REFUNDED': 'Refunded',
  'payment.status.CANCELLED': 'Cancelled',
  'payment.eyebrow.paid': 'Payment confirmed',
  'payment.eyebrow.confirming': 'Confirming payment',
  'payment.eyebrow.waiting': 'Still confirming',
  'payment.eyebrow.failed': 'Payment failed',
  'payment.eyebrow.unpaid': 'Payment pending',
  'payment.eyebrow.refunded': 'Refunded',
  'payment.eyebrow.cancelled': 'Cancelled',
  'payment.title.paid': 'Thank you! You’re all set.',
  'payment.title.confirming': 'Confirming your payment…',
  'payment.title.waiting': 'Your bank is taking a little longer',
  'payment.title.failed': 'Your payment didn’t go through',
  'payment.title.unpaid': 'Complete your payment',
  'payment.title.refunded': 'This payment was refunded',
  'payment.title.cancelled': 'This order was cancelled',
  'payment.body.paid': '{plan} is now active for {event}. A confirmation is in your notifications, and your receipt is below.',
  'payment.body.confirming': 'Razorpay has your payment and we are confirming it now. This usually takes a few seconds, and this page updates by itself.',
  'payment.body.waiting': 'Some banks and UPI apps take a few minutes to confirm. You can safely leave this page: {plan} switches on by itself as soon as the payment is confirmed, and we will notify you. If money left your account and nothing changes within 30 minutes, contact us.',
  'payment.body.failed': 'The payment for {plan} was not completed. If any money left your account, it is returned automatically within 5 to 7 working days. You can try again with the same or another payment method.',
  'payment.body.unpaid': 'This order for {plan} ({amount}) hasn’t been paid yet. Finish paying to switch it on for {event}.',
  'payment.body.refunded': '{amount} for {plan} was refunded to your original payment method. Refunds usually reach your account within 5 to 7 working days.',
  'payment.body.cancelled': 'Nothing is due for this order. You can choose a plan again whenever you like.',
  'payment.bankSaid': 'Reason given: {reason}',
  'payment.templateApplied': 'Your chosen template is now on your invitation.',
  'payment.yourAccount': 'your account',
  'payment.action.openEvent': 'Go to your event',
  'payment.action.design': 'Choose a design',
  'payment.action.dashboard': 'Go to your dashboard',
  'payment.action.retry': 'Try again',
  'payment.action.complete': 'Pay {amount}',
  'payment.action.plans': 'See plans',
  'payment.action.check': 'Check again',
  'payment.dontPayTwice': 'Please don’t pay again while we confirm. Your money is safe.',
  'payment.progress': 'Payment progress',
  'payment.step.placed': 'Order placed',
  'payment.step.payment': 'Payment',
  'payment.step.confirmation': 'Confirmation',
  'payment.step.active': 'Plan active',
  'payment.stepState.done': 'completed',
  'payment.stepState.current': 'in progress',
  'payment.stepState.error': 'failed',
  'payment.stepState.todo': 'not started',
  'payment.summary': 'Order summary',
  'payment.field.plan': 'Plan',
  'payment.field.for': 'For',
  'payment.field.amount': 'Amount',
  'payment.field.placed': 'Ordered on',
  'payment.field.paid': 'Paid on',
  'payment.field.validUntil': 'Valid until',
  'payment.field.orderId': 'Order ID',
  'payment.field.paymentId': 'Payment ID',
  'payment.yearly': '12 months',
  'payment.oneEvent': 'one event',
  'payment.inclGst': 'incl. GST',
  'payment.coupon': 'Coupon {code} applied',
  'payment.help': 'Questions about this payment? Quote the order ID when you write to us.',
  'payment.contact': 'Contact support',

  'account.title': 'Account',
  'account.export': 'Download my data',
  'account.export.body': 'A JSON file with your profile, events and payments.',
  'account.delete': 'Delete my account',
  'account.delete.body': 'You can change your mind for {days} days. After that, your account and everything in it are erased for good.',
  'account.delete.point.offline': 'Your events go offline straight away, and guests can no longer open their invitations or photo albums.',
  'account.delete.point.restore': 'To undo it, sign in within {days} days and choose "Restore my account". Everything comes back as it was.',
  'account.delete.point.erase': 'After that your profile, events, guest lists, RSVPs, photos and videos are permanently deleted.',
  'account.delete.point.records': 'Payment and invoice records are kept, without your contact details, for as long as tax law requires.',
  'account.delete.password': 'Enter your password to confirm',
  'account.delete.confirm': 'Type DELETE to confirm',
  'account.delete.submit': 'Delete my account (restorable for {days} days)',
  'rem.title': 'Automatic reminders',
  'rem.subtitle': 'Friendly emails in each guest’s language, sent for you at the right time.',
  'rem.saved': 'Reminders updated.',
  'rem.rsvp.title': 'Remind guests who have not replied',
  'rem.rsvp.pending': '{count} guests have not replied and can be reached by email.',
  'rem.rsvp.pendingWhatsApp': '{count} guests have not replied and can be reached by email or WhatsApp.',
  'rem.whatsappNote': 'Guests with a phone number get reminders on WhatsApp; the others by email.',
  'rem.rsvp.at': 'Send at',
  'rem.rsvp.schedule': 'Schedule reminder',
  'rem.rsvp.cancel': 'Cancel scheduled reminder',
  'rem.rsvp.now': 'Send reminder now',
  'rem.rsvp.queued': 'Reminder on its way. It goes out within a minute.',
  'rem.rsvp.scheduled': 'Scheduled for {when}',
  'rem.rsvp.sent': 'Sent {when} to {count} guests',
  'rem.fn.title': 'Remind guests before each function',
  'rem.fn.when': 'Send a reminder',
  'rem.fn.off': 'Off',
  'rem.fn.h3': '3 hours before',
  'rem.fn.h12': '12 hours before',
  'rem.fn.h24': '1 day before',
  'rem.fn.h48': '2 days before',
  'rem.fn.at': 'reminder {when}',
  'rem.fn.sent': 'reminder sent',
  'rem.note': 'Reminders go by email to guests with an email address and a live invitation. Guests who declined are never reminded.',
  'dash.nav.logistics': 'Stay & travel',
  'logi.title': 'Stay, travel & seating',
  'logi.subtitle': 'Where guests stay, how they arrive and leave, VIP and dietary needs, and table plans. Each guest sees only their own details on their invitation.',
  'logi.stat.vip': 'VIP guests',
  'logi.stat.dietary': 'Dietary needs',
  'logi.stat.stays': 'Rooms assigned',
  'logi.stat.arrivals': 'Arrivals',
  'logi.stat.pickups': '{count} need a pickup',
  'logi.stat.departures': 'Departures',
  'logi.stat.drops': '{count} need a drop',
  'logi.collect': 'Ask guests for their arrival and departure details on their invitation',
  'logi.collectHint': 'Guests can add or change their own travel. Your pickup notes stay yours to edit.',
  'logi.exports': 'Download sheets',
  'logi.export.travel': 'Transport sheet',
  'logi.export.stays': 'Rooming list',
  'logi.export.seating': 'Seating chart',
  'logi.tab.guests': 'Guests',
  'logi.tab.movements': 'Arrivals & departures',
  'logi.tab.seating': 'Seating',
  'logi.search': 'Search guests',
  'logi.none': 'Not set',
  'logi.edit': 'Edit',
  'logi.vip': 'VIP',
  'logi.dietary': 'Dietary needs',
  'logi.dietaryHint': 'e.g. Jain, vegetarian, no onion or garlic',
  'logi.stay': 'Stay',
  'logi.addStay': 'Add a stay',
  'logi.removeStay': 'Remove stay',
  'logi.hotel': 'Hotel or home',
  'logi.room': 'Room',
  'logi.roomType': 'Room type',
  'logi.address': 'Address',
  'logi.mapUrl': 'Map link',
  'logi.checkIn': 'Check-in',
  'logi.checkOut': 'Check-out',
  'logi.notes': 'Notes for the guest',
  'logi.arrival': 'Arrival',
  'logi.departure': 'Departure',
  'logi.addArrival': 'Add arrival',
  'logi.addDeparture': 'Add departure',
  'logi.remove': 'Remove',
  'logi.mode': 'Travelling by',
  'logi.mode.FLIGHT': 'Flight',
  'logi.mode.TRAIN': 'Train',
  'logi.mode.ROAD': 'Car',
  'logi.mode.BUS': 'Bus',
  'logi.mode.OTHER': 'Other',
  'logi.carrier': 'Airline or train',
  'logi.reference': 'Flight / train number',
  'logi.arriveAt': 'Arrives at',
  'logi.leaveAt': 'Departs at',
  'logi.place': 'Airport, station or city',
  'logi.travellers': 'People travelling',
  'logi.pickup': 'Needs a pickup',
  'logi.drop': 'Needs a drop',
  'logi.pickupNote': 'Pickup arrangement (shown to the guest)',
  'logi.pickupNoteHint': 'e.g. Driver Ramesh (98765 43210), white Innova',
  'logi.byGuest': 'Added by guest',
  'logi.noMovements': 'No arrivals or departures yet. Add them per guest, or ask guests to add their own.',
  'logi.seating.function': 'Function',
  'logi.seating.hint': 'Type a table (and optionally a seat) for each guest. Seating never changes who is invited.',
  'logi.seating.table': 'Table',
  'logi.seating.seat': 'Seat',
  'logi.seating.save': 'Save seating',
  'logi.seating.saved': 'Seating saved.',
  'logi.seating.tables': 'Tables: {tables} · Seated: {seated} of {total}',
  'logi.seating.notInvited': 'No longer invited',
  'logi.seating.none': 'No guests are invited to this function yet.',
  'logi.seating.noFunctions': 'Add a function first.',
  'domain.title': 'Your own domain',
  'domain.subtitle': 'Share an address like amanweddsriya.com. Guests see your event page there, and their personal invitation links use it too.',
  'domain.upsell': 'Custom domains are part of the Premium plan.',
  'domain.unavailable': 'Custom domains are coming soon. Your event is live at its Bulava link in the meantime.',
  'domain.upgrade': 'See plans',
  'domain.input': 'Domain',
  'domain.inputHint': 'A domain you own, for example amanweddsriya.com or invite.sharmas.in. Buy one from any registrar first.',
  'domain.connect': 'Connect domain',
  'domain.status.PENDING': 'Waiting for DNS',
  'domain.status.ACTIVE': 'Live',
  'domain.status.FAILED': 'Not working',
  'domain.records': 'Add these records at your domain registrar (DNS settings):',
  'domain.type': 'Type',
  'domain.name': 'Name',
  'domain.value': 'Value',
  'domain.orA': 'For a root domain that cannot use CNAME, add this A record instead.',
  'domain.propagation': 'DNS changes can take from a few minutes to a few hours. We check automatically every 10 minutes.',
  'domain.check': 'Check now',
  'domain.remove': 'Remove domain',
  'domain.confirmRemove': 'Remove {domain}? Links that use it will stop working.',
  'domain.live': 'Your event is live at',
  'domain.lastChecked': 'Last checked {when}',
  'domain.error.TXT_MISSING': 'We cannot see the TXT record yet.',
  'domain.error.ROUTING_MISSING': 'The domain does not point to Bulava yet (CNAME).',
  'domain.error.SSL_PENDING': 'DNS is set. The security certificate is being issued; this usually takes a few minutes.',
  'domain.error.PROVIDER_ERROR': 'The certificate service did not respond. We will try again shortly.',
  'domain.error.EXPIRED': 'We could not verify this domain within a week. Check the records and press Check now.',
  'domain.error.TAKEN': 'This domain is connected to another event on Bulava. Remove it there first, or contact support if it is yours.',
  'methods.title': 'Sign-in methods',
  'methods.google': 'Google',
  'methods.google.hint': 'Sign in with your Google account instead of typing a password.',
  'methods.google.connected': 'Connected',
  'methods.google.notConnected': 'Not connected',
  'methods.google.connect': 'Connect Google',
  'methods.google.disconnect': 'Disconnect',
  'methods.google.linked': 'Google is connected. You can now sign in with it.',
  'methods.google.unlinked': 'Google is disconnected.',
  'methods.password': 'Password',
  'methods.password.none': 'You sign in with Google and have no password yet.',
  'methods.password.set': 'Set a password',
  'methods.password.change': 'Change password',
  'methods.password.current': 'Current password',
  'methods.password.new': 'New password',
  'methods.password.hint': 'At least 10 characters.',
  'methods.password.saved': 'Password saved. Your other devices were signed out.',
  'mfa.needsPassword': 'Set a password first (under Sign-in methods): two-step sign-in asks for it when you turn it on or off.',
  'mfa.title': 'Two-step sign-in',
  'mfa.subtitle': 'Ask for a code from an authenticator app (Google Authenticator, Microsoft Authenticator, 1Password and others) as well as your password.',
  'mfa.on': 'On',
  'mfa.off': 'Off',
  'mfa.enabledSince': 'On since {date}',
  'mfa.turnOn': 'Turn on two-step sign-in',
  'mfa.password': 'Confirm your password',
  'mfa.continue': 'Continue',
  'mfa.scan': '1. Scan this QR code with your authenticator app.',
  'mfa.manual': 'Cannot scan it? Enter this key in the app instead:',
  'mfa.enterCode': '2. Enter the 6-digit code the app shows.',
  'mfa.confirm': 'Turn on',
  'mfa.qrAlt': 'QR code for your authenticator app',
  'mfa.codesTitle': 'Save your recovery codes',
  'mfa.codesBody': 'If you lose your phone, each code lets you sign in once. Keep them somewhere safe: they will not be shown again.',
  'mfa.copy': 'Copy codes',
  'mfa.copied': 'Copied',
  'mfa.download': 'Download as text',
  'mfa.done': 'I have saved them',
  'mfa.remaining': '{count} recovery codes left',
  'mfa.remainingLow': 'Only {count} recovery codes left. Create new ones.',
  'mfa.regenerate': 'New recovery codes',
  'mfa.regenerateBody': 'Your current recovery codes will stop working. Enter a code from your authenticator app to continue.',
  'mfa.turnOff': 'Turn off',
  'mfa.turnOffBody': 'Enter your password and a code from your authenticator app. Your other devices will be signed out.',
  'mfa.code': 'Authenticator code',
  'mfa.cancel': 'Cancel',
  'mfa.enabled': 'Two-step sign-in is on. Your other devices were signed out.',
  'mfa.disabled': 'Two-step sign-in is off.',
  'mfa.codesFile': 'Bulava recovery codes. Each code works once.',

  'notif.title': 'Notifications',
  'notif.empty': 'You are all caught up.',
  'notif.RSVP_RECEIVED': '{guest} replied to {event}',
  'notif.RENDER_COMPLETE': 'Your video is ready',
  'notif.PAYMENT': 'Payment received: {plan}',
  'notif.REGISTRATION_RECEIVED': '{guest} registered for {event}',

  // team
  'team.title': 'Team',
  'team.subtitle': 'Invite co-hosts, planners, photographers and event-day staff. Anyone without a Bulava account gets an email with a code to join. Each role sees only its own sections.',
  'team.email': 'Email',
  'team.role': 'Role',
  'team.add': 'Add to team',
  'team.added': 'Added. They will see this event in their dashboard.',
  'team.remove': 'Remove',
  'team.confirmRemove': 'Remove {name} from the team? They lose access immediately.',
  'team.you': 'You',
  'team.role.OWNER': 'Owner',
  'team.role.ADMIN': 'Admin',
  'team.role.CO_HOST': 'Co-host',
  'team.role.FUNCTION_MANAGER': 'Function manager',
  'team.role.GUEST_MANAGER': 'Guest manager',
  'team.role.MEDIA_MANAGER': 'Photo manager',
  'team.role.PHOTOGRAPHER': 'Photographer',
  'team.role.ADMIN.desc': 'Everything except deleting the event, including managing the team.',
  'team.role.CO_HOST.desc': 'Edit the event, functions, guests, invitations, RSVPs and photos.',
  'team.role.FUNCTION_MANAGER.desc': 'Manage functions and see guests and RSVPs.',
  'team.role.GUEST_MANAGER.desc': 'Manage guests, invitations and RSVPs, and check guests in at the door.',
  'team.role.MEDIA_MANAGER.desc': 'Upload, approve and remove photos.',
  'team.role.PHOTOGRAPHER.desc': 'Upload photos into the album’s folders. Sees only Photos.',
  'notif.MEMBER_ADDED': 'You were added to {event}',

  // email invitations
  'invitation.email.hint': 'Email each guest their personal invitation link (guests with an email address only).',
  'invitation.email.send': 'Email invitations',
  'invitation.email.queued': '{count} invitation emails are on their way.',
  'invitation.email.none': 'No one to email: guests need an email address, and recent sends are skipped.',
  'invitation.whatsapp.hint': 'Send each guest their personal invitation from Bulava’s WhatsApp Business number (guests with a phone number only).',
  'invitation.whatsapp.send': 'Send on WhatsApp',
  'invitation.whatsapp.queued': '{count} WhatsApp invitations are on their way.',
  'invitation.whatsapp.none': 'No one to message: guests need a phone number, and recent sends are skipped.',
  'invitation.whatsapp.skippedLimit': '{count} guests were not messaged because this event’s WhatsApp allowance ran out.',
  'invitation.whatsapp.allowance': '{used} of {limit} WhatsApp messages used',
  'invitation.whatsapp.unlimited': '{used} WhatsApp messages sent',
  'invitation.whatsapp.upgrade': 'Send invitations straight to your guests’ WhatsApp with a paid plan.',
  'invitation.whatsapp.upgradeCta': 'See plans',

  // registrations
  'dash.nav.registrations': 'Registrations',
  'reg.title': 'Registrations',
  'reg.subtitle': 'Let people register on your public event page. Each confirmed registration gets a personal invitation link.',
  'reg.notAvailable': 'Registration works for public and private-link events. Change who can view this event in Settings first.',
  'reg.settings': 'Registration form',
  'reg.enabled': 'Accept registrations',
  'reg.max': 'Maximum confirmed places',
  'reg.maxHint': 'Leave empty for no limit. Your plan’s guest limit still applies.',
  'reg.approval': 'Review each registration before confirming it',
  'reg.waitlist': 'Keep a waiting list when all places are taken',
  'reg.closesAt': 'Close registration on',
  'reg.closesAtHint': 'Optional. Registration closes at the end of the chosen time.',
  'reg.fields': 'Extra questions',
  'reg.fieldsHint': 'Name, email and mobile number are always asked.',
  'reg.save': 'Save registration settings',
  'reg.saved': 'Registration settings saved.',
  'reg.pageLink': 'Registration page',
  'reg.copyLink': 'Copy link',
  'reg.list': 'People who registered',
  'reg.empty': 'No registrations yet.',
  'reg.filter.all': 'All',
  'reg.status.PENDING': 'Awaiting review',
  'reg.status.CONFIRMED': 'Confirmed',
  'reg.status.WAITLISTED': 'Waiting list',
  'reg.status.REJECTED': 'Declined',
  'reg.status.CANCELLED': 'Cancelled',
  'reg.action.CONFIRM': 'Confirm',
  'reg.action.WAITLIST': 'Move to waiting list',
  'reg.action.REJECT': 'Decline',
  'reg.action.CANCEL': 'Cancel registration',
  'reg.confirmCancel': 'Cancel this registration? Their invitation link stops working.',
  'reg.registeredAt': 'Registered {date}',

  // form field builder (RSVP questions and registration fields)
  'fields.add': 'Add question',
  'fields.label': 'Question',
  'fields.key': 'Key',
  'fields.keyHint': 'Lowercase letters, numbers and underscores. Used in exports.',
  'fields.type': 'Answer type',
  'fields.type.TEXT': 'Text',
  'fields.type.NUMBER': 'Number',
  'fields.type.BOOLEAN': 'Yes / no',
  'fields.type.SINGLE_CHOICE': 'One choice',
  'fields.type.MULTI_CHOICE': 'Several choices',
  'fields.required': 'Required',
  'fields.options': 'Choices',
  'fields.optionsHint': 'One choice per line.',
  'fields.remove': 'Remove question',
  'fields.hindiLabel': 'Question in Hindi (optional)',
  'fields.empty': 'No questions yet.',
  'fields.function': 'Ask for',
  'fields.allFunctions': 'Every function',

  // RSVP questions
  'rsvpq.title': 'RSVP questions',
  'rsvpq.subtitle': 'Ask guests for meal preferences, travel plans or anything else when they RSVP.',
  'rsvpq.save': 'Save question',
  'rsvpq.saved': 'Question saved.',
  'rsvpq.remove': 'Remove',
  'rsvpq.confirmRemove': 'Remove this question? Answers already given are kept.',

  // Design v2: grouped event navigation and the dashboard home
  'dash.navGroup.setup': 'Set up',
  'dash.navGroup.guests': 'Guests',
  'dash.navGroup.celebrate': 'Share & celebrate',
  'dash.navGroup.manage': 'Manage',
  'dash.nav.sections': 'Event sections',
  'dash.checklist.progress': '{done} of {total} done',
  'dash.checklist.complete': 'Everything is ready. Time to celebrate!',
  'dash.home.events': 'Your events',
  'dash.home.newHint': 'Wedding, birthday, puja or any celebration',
  'dash.event.noDate': 'Date not set yet',
  'dash.stats.openRate': '{rate}% opened',

  // Roles see only their own sections
  'dash.noAccess.title': 'This section is not part of your role',
  'dash.noAccess.body': 'You are on this event’s team as {role}, which does not include this section. Ask the event owner if you need it.',
  'dash.noAccess.go': 'Go to {section}',

  // Sharing: one link for link-shared events, personal invitations otherwise
  'share.title': 'Share your event',
  'share.subtitle.LINK': 'Send this one link to everyone. Guests open the invitation and can register themselves, so you do not need to add them first.',
  'share.subtitle.PERSONAL': 'This event is “{mode}”: each guest needs their own invitation link. Add guests, then send each their link.',
  'share.copy': 'Copy link',
  'share.whatsapp': 'Share on WhatsApp',
  'share.open': 'Open',
  'share.pin': 'Visitors also need the PIN you set.',
  'share.registration.on': 'Registration is open: anyone with the link can register.',
  'share.registration.off': 'Registration is off, so people can only view the invitation.',
  'share.registration.manage': 'Registration settings',
  'share.draft': 'Publish the event first; the link works once the event is live.',
  'share.expires': 'Link works until {date}',
  'share.expired': 'This link expired on {date}. Choose a new date or make a new link.',
  'share.expiryLabel': 'Link works until',
  'share.changeExpiry': 'Change date',
  'share.saveExpiry': 'Save date',
  'share.rotate': 'New link',
  'share.confirmRotate': 'Make a new link? The current link stops working at once.',
  'share.addGuests': 'Add guests',
  'share.personalInvites': 'Personal invitations',
  'share.personalOptional': 'You can also send personal invitations to guests you add, from the Invitations tab.',

  // Team invitations by code
  'team.invited': 'Invitation sent to {email}. They will get a 6-digit code to join.',
  'team.pending': 'Waiting to join',
  'team.locked': 'Locked after wrong codes',
  'team.resend': 'Resend code',
  'team.resent': 'A new code is on its way to {email}.',
  'team.revokeInvite': 'Cancel invitation',
  'team.confirmRevoke': 'Cancel the invitation for {email}? Their code stops working.',
  'team.invitedBy': 'Invited by {name}',

  // Joining a team from the emailed link
  'join.title': 'Join the team for {event}',
  'join.subtitle': '{name} added you as {role}.',
  'join.subtitleNoName': 'You were added as {role}.',
  'join.codeLabel': 'Code from your email',
  'join.codeHint': 'We sent a 6-digit code to {email}.',
  'join.verify': 'Continue',
  'join.attemptsLeft': 'That code is not correct. Attempts left: {count}.',
  'join.create.title': 'Create your account',
  'join.create.subtitle': 'Choose the name the team will see and a password for {email}.',
  'join.create.submit': 'Join the team',
  'join.signIn.title': 'Sign in to join',
  'join.signIn.body': 'There is already a Bulava account for {email}. Sign in with it to join the team.',
  'join.signIn.cta': 'Sign in',
  'join.signedIn.body': 'You are signed in as {email}. Join the team with the code from your email.',
  'join.signedIn.submit': 'Join the team',
  'join.done': 'Welcome to the team!',
  'join.open': 'Open the event',

  // The event album and its folders
  'album.uploadLink': 'Upload link',
  'album.galleryLink': 'Guest gallery',
  'album.copyUpload': 'Copy upload link',
  'album.copyGallery': 'Copy gallery link',
  'album.settings': 'Album settings',
  'album.folders': 'Folders',
  'album.folders.subtitle': 'Guests and photographers choose a folder when they upload. Choose which folders the guest gallery and the live wall show.',
  'album.inGallery': 'In gallery',
  'album.onWall': 'On live wall',
  'album.count': '{count} photos',
  'album.countOne': '1 photo',
  'album.pending': '{count} waiting',
  'album.functionRemoved': 'Function removed',
  'album.addFolder': 'Add folder',
  'album.folderName': 'Folder name',
  'album.rename': 'Rename',
  'album.removeFolder': 'Remove folder',
  'album.confirmRemove': 'Remove “{name}”? Its photos move to General.',
  'album.upload': 'Upload photos',
  'album.uploadTo': 'Upload to',
  'album.choose': 'Choose photos',
  'album.uploadSubmit': 'Upload {count}',
  'album.uploading': 'Uploading {done} of {total}…',
  'album.uploaded': '{count} uploaded. They appear here once processed.',
  'album.uploadFailed': '{count} could not be uploaded.',
  'album.pendingTitle': '{count} photos waiting for approval',
  'album.pendingTitleOne': '1 photo waiting for approval',
  'album.moveTo': 'Move to another folder',
  'album.empty': 'No photos in this folder yet.',
  'album.open': 'Show photos',
  'album.hide': 'Hide photos',

  // ── Guided setup: the steps, the next-step bar under every event page ──
  'dash.step.design': 'Choose your design',
  'dash.step.design.short': 'Design',
  'dash.step.design.body': 'Pick the look of your invitation. Your names and details fill every design, and you can change it any time.',
  'dash.step.design.action': 'Choose a design',
  'dash.step.functions': 'Add your functions',
  'dash.step.functions.short': 'Functions',
  'dash.step.functions.body': 'Each ceremony with its date, time and venue. Guests see the ones they are invited to.',
  'dash.step.functions.action': 'Add functions',
  'dash.step.guests': 'Add your guests',
  'dash.step.guests.short': 'Guests',
  'dash.step.guests.body': 'Add the people you are inviting, one by one or from a spreadsheet, and put them in groups.',
  'dash.step.guests.bodyLink': 'Optional: everyone can register from your link. Add guests here to send them personal invitations and reminders too.',
  'dash.step.guests.action': 'Add guests',
  'dash.step.publish': 'Preview and publish',
  'dash.step.publish.short': 'Publish',
  'dash.step.publish.body': 'Check the preview, choose who can open the invitation, and make it live.',
  'dash.step.publish.action': 'Publish',
  'dash.step.shareLink': 'Share your invitation link',
  'dash.step.shareLink.short': 'Share',
  'dash.step.shareLink.body': 'Send your one link on WhatsApp or anywhere else. Guests open it and reply.',
  'dash.step.shareLink.action': 'Share the link',
  'dash.step.send': 'Send the invitations',
  'dash.step.send.short': 'Invite',
  'dash.step.send.body': 'Send each guest their personal invitation link on WhatsApp or by email.',
  'dash.step.send.action': 'Send invitations',
  'dash.step.rsvps': 'Track replies',
  'dash.step.rsvps.short': 'Replies',
  'dash.step.rsvps.body': 'See who is coming to each function, with head counts, as replies arrive.',
  'dash.step.rsvps.action': 'View replies',
  'next.setup': 'Setup',
  'next.eyebrow.step': 'Up next · step {n} of {total}',
  'next.eyebrow.todo': 'Up next',
  'next.eyebrow.done': 'All set',
  'next.done.title': 'You’re all set',
  'next.done.body': 'Everything is ready. Keep an eye on replies, photos and updates as the day comes closer.',
  'next.back': 'Back',
  'next.rail': 'Setup steps',
  'next.optional': 'Optional',
  'next.state.done': 'Done',
  'next.state.todo': 'Not done yet',

  // ── Publishing (and choosing who can open the invitation) ──
  'publish.open': 'Publish',
  'publish.title': 'Publish your invitation',
  'publish.subtitle': 'Guests can open it as soon as it is live. You can change who can open it later, in Settings.',
  'publish.warn.design': 'You are still using the starter design.',
  'publish.warn.functions': 'No functions yet, so guests will not see any dates or venues.',
  'publish.publishing': 'Publishing…',
  'publish.cta': 'Publish now',
  'publish.done.title': 'Your invitation is live',
  'publish.done.link': 'Share this link with everyone you are inviting. They can open it and reply straight away.',
  'publish.done.personal': 'Now add your guests and send each one their personal invitation.',
  'publish.done.close': 'Done',
  'publish.done.next.link': 'Open invitations',
  'publish.done.next.personal': 'Add guests',
  'access.recommended': 'Recommended',
  'access.desc.PRIVATE_LINK': 'One link for everyone you send it to. It is not listed anywhere, guests can reply from it, and you can add a PIN.',
  'access.desc.INVITE_ONLY': 'Each guest gets their own link and sees only the functions they are invited to.',
  'access.desc.GROUP_RESTRICTED': 'Only guests in the groups you choose can open it.',
  'access.desc.SECRET_TOKEN': 'A private link that stops working on a date you choose.',
  'access.desc.PUBLIC': 'Anyone can find and open it, like a public event page.',
  'settings.general': 'General',
  'settings.access.draft': 'Your event is a draft, so nobody can open it yet. You choose this when you publish, or you can set it now.',
  'settings.access.live': 'Who can open your invitation. Changes apply straight away.',
  'settings.access.save': 'Save access',
  'settings.access.saved': 'Access updated.',
  'common.saved': 'Saved.',
  'common.close': 'Close',

  // ── Design page and the design browser ──
  'design.edit': 'Edit design',
  'design.starter': 'Starter design',
  'design.yours': 'Your design',
  'design.unsaved': 'Unsaved changes',
  'design.savedBadge': 'Saved',
  'design.browse': 'Browse {count} designs',
  'design.browseShort': 'Browse designs',
  'design.useThis': 'Use this design',
  'design.saveChanges': 'Save changes',
  'design.starterHint': 'This is the starter design for your occasion. Pick from {count} designs made for it.',
  'design.customize': 'Customize your design',
  'design.livePreview': 'Live preview',
  'design.previewSavedHint': 'Opens the saved design. Save first to see your latest changes.',
  'picker.title': 'Choose a design',
  'picker.count': '{count} designs',
  'picker.search': 'Search designs',
  'picker.all': 'All',
  'picker.inPlan': 'In my plan',
  'picker.none': 'No designs match.',
  'picker.reset': 'Clear filters',
  'picker.preview': 'Preview with your names',
  'picker.beyondPlan': 'Beyond your plan: you can design and preview it now, with a watermark. Publishing it needs an upgrade.',
  'picker.keep': 'Keep this design',
  'picker.use': 'Use this design',

  // ── Creating an event ──
  'create.eyebrow': 'New event',
  'create.progress': 'Steps',
  'create.step.occasion': 'Occasion',
  'create.step.details': 'Details',
  'create.step.functions': 'Functions',
  'create.title.0': 'What are you celebrating?',
  'create.title.1': 'Tell us about it',
  'create.title.2': 'Which functions are you planning?',
  'create.subtitle.0': 'Pick the occasion. We will suggest the functions and guest groups that usually go with it.',
  'create.subtitle.1': 'Names, the day and the language of your invitation. You can change any of it later.',
  'create.subtitle.2': 'Keep the ones you are having. You can add, rename or remove functions any time.',
  'create.suggested': 'Suggested functions: {count}',
  'create.who.couple': 'Whose celebration is it?',
  'create.who.honoree': 'Who are we celebrating?',
  'create.who.event': 'Name your event',
  'create.autoTitle.couple': '{one} & {two}’s {occasion}',
  'create.autoTitle.honoree': '{name}’s {occasion}',
  'create.titleAuto': 'Made from the names. Edit it if you like.',
  'create.titleHint': 'Shown on your dashboard and at the top of your invitation.',
  'create.titlePlaceholder': 'Our {occasion}',
  'create.when': 'When is it?',
  'create.date': 'Main day',
  'create.dateHint': 'Optional. You will add each function’s date, time and venue next.',
  'create.languageHint': 'The language your guests read the invitation in.',
  'create.functions': 'Functions',
  'create.functionsHint': 'Tap to leave out the ones you are not having.',
  'create.all': 'Select all',
  'create.none': 'Clear all',
  'create.functionsLater': 'Dates, times and venues come next, on the Functions page.',
  'create.noSuggestions': 'This occasion has no suggested functions. You will add your own after creating the event.',
  'create.groups': 'Guest groups',
  'create.groupsHint': 'We will also set these up, to keep your guest list tidy.',
  'create.privacy': 'Your invitation stays private until you publish it. When you publish, you choose who can open it; one private link is the default.',
  'create.back': 'Back',
  'create.continue': 'Continue',
  'create.creating': 'Creating…',
  'create.submit': 'Create my event',
  'create.notSure': 'Want to see the designs first?',
  'create.preview.eyebrow': 'Your celebration',
  'create.preview.invited': 'You are invited',
  'create.preview.one': 'First name',
  'create.preview.two': 'Second name',
  'create.preview.name': 'Their name',
  'create.preview.event': 'Your event',
  'create.preview.date': 'Date to be announced',
  'create.templateChosen': 'Your event starts with the design you chose. You can change it any time.',
  'create.next.title': 'What happens next',
  'create.next.design': 'Choose your design',
  'create.next.designChosen': 'Personalise your design',
  'create.next.functions': 'Add functions and venues',
  'create.next.guests': 'Add your guests',
  'create.next.publish': 'Publish and share',

  // ── Home and My events ──
  'dash.nav.home': 'Home',
  'home.summary': '{drafts} in progress · {live} live',
  'home.summaryEmpty': 'Let’s plan your first celebration.',
  'home.allEvents': 'All events ({count})',
  'home.today': 'Today',
  'home.tomorrow': 'Tomorrow',
  'home.inDays': 'In {count} days',
  'home.setup': 'Setup {done} of {total}',
  'home.nextCelebration': 'Next celebration',
  'home.dayToGo': 'day to go',
  'home.daysToGo': 'days to go',
  'home.continue': 'Pick up where you left off',
  'home.openEvent': 'Open event',
  'home.glance': 'At a glance',
  'home.stat.events': 'Events',
  'home.stat.live': 'Live',
  'home.stat.functions': 'Functions',
  'home.stat.guests': 'Guests',
  'home.activity': 'Recent activity',
  'home.activityEmpty': 'Replies, registrations and payments show up here.',
  'home.shortcuts': 'Shortcuts',
  'home.explore': 'Designs for you',
  'home.exploreAll': 'See all designs',
  'home.startWith': 'What are you celebrating?',
  'home.startWithBody': 'Start from an occasion and we will set up the usual functions and guest groups.',
  'home.otherOccasion': 'See every occasion',
  'home.how': 'How Bulava works',
  'home.how.step': 'Step {n}',
  'home.how.create': 'Create your event',
  'home.how.create.body': 'Pick the occasion and add the names and the day.',
  'home.how.design': 'Choose a design',
  'home.how.design.body': 'Your names fill every design. Change the words, colours and photos.',
  'home.how.invite': 'Invite your guests',
  'home.how.invite.body': 'Share one link on WhatsApp, or send personal invitations.',
  'home.how.celebrate': 'Celebrate together',
  'home.how.celebrate.body': 'Track replies, share updates and collect everyone’s photos.',
  'events.subtitle': 'Every celebration you are planning or helping with.',
  'events.filter.label': 'Filter events',
  'events.filter.all': 'All',
  'events.filter.draft': 'Drafts',
  'events.filter.live': 'Live',
  'events.filter.past': 'Past',
  'events.filter.none': 'No events here yet.',

  // ── Account area ──
  'account.eyebrow': 'Your account',
  'account.nav.label': 'Account sections',
  'account.nav.profile': 'Profile',
  'account.nav.profile.hint': 'Name, email and WhatsApp',
  'account.nav.security': 'Sign-in & security',
  'account.nav.security.hint': 'Password, Google, two-step',
  'account.nav.payments': 'Payments',
  'account.nav.payments.hint': 'Plans, receipts and refunds',
  'account.nav.privacy': 'Privacy & data',
  'account.nav.privacy.hint': 'Export or delete your data',
  'account.nav.note': 'Bulava never asks for your password or sign-in codes on WhatsApp or by phone.',
  'account.fact.provisional': 'Not secured yet',
  'account.fact.password': 'Password set',
  'account.fact.noPassword': 'No password',
  'account.fact.google': 'Google connected',
  'account.fact.twoStep': 'Two-step on',
  'account.fact.noTwoStep': 'Two-step off',
  'account.tile.events': 'Events',
  'account.tile.eventsHint': 'Open my events',
  'account.tile.plans': 'Plans bought',
  'account.tile.plansHint': 'Payments and receipts',
  'account.tile.security': 'Sign-in methods',
  'account.tile.securityValue': '{count} of 3',
  'account.tile.securityHint': 'Turn on two-step sign-in',
  'account.details': 'Personal details',
  'account.detailsHint': 'How you sign in and how Bulava reaches you.',
  'account.emailHint': 'Your sign-in email.',
  'account.unsaved': 'Unsaved changes',
  'security.strong': 'Your account is well protected',
  'security.weak': 'Make your account safer',
  'security.score': '{count} of {total} protections on',
  'security.check.password': 'Password',
  'security.check.passwordOn': 'You can sign in with your email and password.',
  'security.check.passwordOff': 'Set a password so you can sign in without Google or WhatsApp.',
  'security.check.google': 'Google',
  'security.check.googleOn': 'You can sign in with your Google account.',
  'security.check.googleOff': 'Connect Google for one-tap sign-in.',
  'security.check.twoStep': 'Two-step sign-in',
  'security.check.twoStepOn': 'A code from your authenticator app protects every sign-in.',
  'security.check.twoStepOff': 'Add a code from an authenticator app to every sign-in.',
  'privacy.policies': 'Policies',
  'privacy.policiesBody': 'How Bulava collects, uses and protects your data and your guests’ data.',
  'privacy.link.privacy': 'Privacy policy',
  'privacy.link.terms': 'Terms of service',
  'privacy.link.cookies': 'Cookie policy',
  'privacy.link.deletion': 'Account deletion policy',
  'privacy.link.grievance': 'Grievance redressal',
  'payments.grants': 'Complimentary',
  'payments.last': 'Last payment',
  'payments.filter.label': 'Filter payments',
  'payments.filter.all': 'All',
  'payments.filter.paid': 'Paid',
  'payments.filter.open': 'Open or failed',
  'payments.filter.closed': 'Refunded or cancelled',
  'payments.filter.none': 'No payments here.',
  'payment.back': 'All payments',
} as const;
