/** Marketing site copy (homepage, templates, pricing, legal). Merged into the English catalog. */
export const enMarketing = {
  'nav.templates': 'Templates',
  'nav.howItWorks': 'How it works',
  'nav.features': 'Features',
  'nav.pricing': 'Pricing',
  'nav.signIn': 'Sign in',
  'nav.getStarted': 'Get started',
  'nav.myEvents': 'My events',
  'nav.account': 'Account of {name}',
  'nav.signedInAs': 'Signed in as {name}',
  'nav.dashboard': 'Dashboard',
  'nav.menu': 'Menu',
  'nav.announcement': 'Site announcement',
  'content.updated': 'Last updated {date}',
  'content.onThisPage': 'On this page',
  'content.readingTime': '{minutes} min read',
  'content.legal': 'Legal',
  'content.questions': 'Questions about this policy?',
  'content.questionsBody': 'Write to us and a real person will reply, usually within one working day.',
  'content.contactUs': 'Contact us',
  'content.related': 'Related policies',
  'gallery.filters': 'Filters',
  'gallery.showing': 'Showing {shown} of {total} templates',
  'gallery.active': 'Active filters',
  'gallery.remove': 'Remove filter: {filter}',
  'gallery.clear': 'Clear all',
  'gallery.more': '+ {count} more',
  'gallery.fewer': 'Show fewer',
  'gallery.emptyTitle': 'No templates match these filters',
  'gallery.emptyBody': 'Try removing a filter, or browse every design.',
  'gallery.occasion': 'Occasion',
  'gallery.tradition': 'Tradition',
  'gallery.plan': 'Plan',
  'gallery.format': 'Format',
  'contact.action.email': 'Email us',
  'contact.action.call': 'Call us',
  'contact.action.whatsapp': 'Chat on WhatsApp',
  'contact.reach': 'Other ways to reach us',
  'contact.form.title': 'Send us a message',
  'contact.form.subtitle': 'Tell us what you need and we will get back to you by email.',
  'contact.form.name': 'Your name',
  'contact.form.email': 'Email address',
  'contact.form.phone': 'Phone (optional)',
  'contact.form.phoneHint': 'Only if you would like a call back.',
  'contact.form.topic': 'What is it about?',
  'contact.form.message': 'Your message',
  'contact.form.messageHint': 'Include your event name, and the payment ID for anything about a payment.',
  'contact.form.privacy': 'We use these details only to answer you.',
  'contact.form.privacyLink': 'Privacy policy',
  'contact.form.send': 'Send message',
  'contact.form.sending': 'Sending…',
  'contact.form.orEmail': 'or email',
  'contact.form.sentTitle': 'Thank you, {name}',
  'contact.form.sentBody': 'Your message is with our team. We will reply to {email}, usually within one working day.',
  'contact.form.reference': 'Reference {reference}',
  'contact.form.another': 'Send another message',
  'contact.topic.GENERAL': 'General question',
  'contact.topic.EVENT_HELP': 'Help with my event',
  'contact.topic.BILLING': 'Payments and refunds',
  'contact.topic.PARTNERSHIP': 'Planners and partnerships',
  'contact.topic.PRIVACY': 'Privacy and my data',
  'contact.topic.FEEDBACK': 'Feedback or an idea',

  'home.hero.eyebrow': 'Digital invitations for every Indian celebration',
  'home.hero.title': 'Invitations that feel like the occasion itself',
  'home.hero.subtitle': 'Wedding websites, video invites and RSVPs for Hindu, Sikh, Muslim, South Indian and Christian weddings, and every celebration after: birthdays, griha pravesh, pujas and more.',
  'home.hero.support': 'Personalise in minutes. Share one link on WhatsApp. Every guest sees only the functions they are invited to.',
  'home.hero.browse': 'Browse templates',
  'home.hero.how': 'See how it works',
  'home.proof.templates': '{count} designs',
  'home.proof.languages': '{count} Indian languages',
  'home.proof.events': '{count} celebrations hosted',
  'home.proof.rsvps': '{count} RSVPs collected',

  'home.showcase.eyebrow': 'Template preview',
  'home.showcase.title': 'See every invite come to life',
  'home.showcase.subtitle': 'These are live previews, rendered from the same templates your guests will open.',
  'home.showcase.cta': 'Browse all templates',

  'home.categories.eyebrow': 'For every occasion',
  'home.categories.title': 'One platform, every celebration',
  'home.cat.weddings': 'Weddings',
  'home.cat.weddings.desc': 'Hindu, Sikh, Muslim, South Indian, Christian, Bengali, Marathi, Gujarati',
  'home.cat.preWedding': 'Haldi, Mehendi & Sangeet',
  'home.cat.preWedding.desc': 'Function-by-function invites and RSVPs',
  'home.cat.saveTheDate': 'Save the Date',
  'home.cat.saveTheDate.desc': 'Countdown pages and short films',
  'home.cat.engagement': 'Engagement & Roka',
  'home.cat.engagement.desc': 'Ring ceremonies and roka',
  'home.cat.birthday': 'Birthdays',
  'home.cat.birthday.desc': 'First birthdays to 75th milestones',
  'home.cat.anniversary': 'Anniversaries',
  'home.cat.anniversary.desc': 'Silver and golden jubilees',
  'home.cat.family': 'Baby shower, Namkaran & Mundan',
  'home.cat.family.desc': 'Godh bharai, naming, mundan, upanayanam',
  'home.cat.home': 'Griha Pravesh',
  'home.cat.home.desc': 'Housewarming pujas and parties',
  'home.cat.faith': 'Pujas & Festivals',
  'home.cat.faith.desc': 'Katha, Gurpurab, Diwali, Eid gatherings',
  'home.cat.corporate': 'Corporate & Community',
  'home.cat.corporate.desc': 'Summits, launches, utsavs, school events',

  'home.grid.eyebrow': 'The collection',
  'home.grid.title': 'Templates for every tradition',
  'home.grid.subtitle': 'New designs added regularly. Filter by tradition or plan.',
  'home.grid.more': 'View all {count} templates',
  'home.grid.empty': 'No templates match these filters yet.',
  'filter.all': 'All',
  'filter.tier.FREE': 'Free',
  'filter.tier.STANDARD': 'Standard',
  'filter.tier.PREMIUM': 'Premium',
  'filter.type.WEBSITE': 'Invitation websites',
  'filter.type.VIDEO': 'Video invites',
  'filter.type.DIGITAL_CARD': 'Image cards',
  'tag.signature': '✦ Signature',
  'tag.hindu': 'Hindu',
  'tag.sikh': 'Sikh',
  'tag.muslim': 'Muslim',
  'tag.south-indian': 'South Indian',
  'tag.christian': 'Christian',
  'tag.bengali': 'Bengali',
  'tag.marathi': 'Marathi',
  'tag.gujarati': 'Gujarati',
  'tag.punjabi': 'Punjabi',
  'tag.rajasthani': 'Rajasthani',
  'tag.destination': 'Destination',
  'tag.modern': 'Modern',
  'template.badge.NEW': 'New',
  'template.badge.POPULAR': 'Popular',
  'template.badge.BESTSELLER': 'Bestseller',
  'template.use': 'Use this template',
  'template.view': 'Preview',
  'template.included': 'Included with {plan}',
  'template.free': 'Free',

  'home.signature.eyebrow': 'The Signature Collection',
  'home.signature.title': 'Invitations that open like a celebration',
  'home.signature.subtitle': 'Lanterns that rise, gates that swing open, a wax seal to break, a gold card to scratch. Every Signature invitation plays your music and carries your verse, menu, schedule, RSVP and photos.',
  'home.signature.cta': 'Explore the Signature collection',
  'signature.opens': 'Opens with {intro}',
  'signature.music': 'Plays your music',
  'signature.menu': 'Verse, menu and countdown included',
  'signature.play': 'Play the opening',
  'intro.name.envelope': 'a sealed envelope',
  'intro.name.curtain': 'theatre curtains',
  'intro.name.doors': 'palace doors',
  'intro.name.gates': 'golden gates',
  'intro.name.seal': 'a wax seal',
  'intro.name.lanterns': 'rising lanterns',
  'intro.name.petals': 'a shower of petals',
  'intro.name.celestial': 'a starry night',
  'intro.name.scratch': 'a scratch-to-reveal card',
  'home.spotlight.eyebrow': 'Spotlight',
  'home.spotlight.point1': 'Opens like a sealed envelope, with your monogram on the wax seal',
  'home.spotlight.point2': 'One page per guest, showing only their functions',
  'home.spotlight.point3': 'Per-function RSVP with headcount and meal choice',
  'home.spotlight.point4': 'English, हिन्दी and Hinglish from the same design',

  'home.video.eyebrow': 'Video invitations',
  'home.video.title': 'Watch them in action',
  'home.video.subtitle': 'Short 9:16 films made from your details, ready for WhatsApp status and Reels. Rendered in HD in minutes.',
  'home.video.play': 'Play preview',

  'home.how.eyebrow': 'How it works',
  'home.how.title': 'From idea to RSVPs in four steps',
  'home.how.1.title': 'Pick a design',
  'home.how.1.body': 'Choose from designs for your tradition and occasion, then set your colours and words.',
  'home.how.2.title': 'Add functions and guests',
  'home.how.2.body': 'Create Haldi, Sangeet, Wedding and more. Add guests once and put them in groups.',
  'home.how.3.title': 'Share personal links',
  'home.how.3.body': 'Send each guest their own link on WhatsApp. They see only what they are invited to.',
  'home.how.4.title': 'Track and celebrate',
  'home.how.4.body': 'Watch RSVPs arrive, post updates, check guests in and collect photos by QR.',

  'home.features.eyebrow': 'Features',
  'home.features.title': 'Not just a card. The whole celebration.',
  'home.feature.private.title': 'Private by design',
  'home.feature.private.body': 'Invite-only links, group-restricted functions, PIN and OTP protection. Guests never see what they are not invited to.',
  'home.feature.rsvp.title': 'RSVP per function',
  'home.feature.rsvp.body': 'Guests reply for each function, with headcount, meal preference and your own questions.',
  'home.feature.languages.title': 'Made for India',
  'home.feature.languages.body': 'Hindi, Hinglish and more, with Indian date formats, invocations and scripts that render correctly.',
  'home.feature.whatsapp.title': 'WhatsApp-first sharing',
  'home.feature.whatsapp.body': 'One tap to share each personal invitation, with the message already written in your guest’s language.',
  'home.feature.photos.title': 'QR photo sharing',
  'home.feature.photos.body': 'Print a QR at the venue. Guests upload photos from their phone, no app needed, into a private gallery.',
  'home.feature.video.title': 'Video invitations',
  'home.feature.video.body': 'Turn your invitation into a short film with licensed music, rendered in HD.',
  'home.feature.checkin.title': 'Event-day check-in',
  'home.feature.checkin.body': 'Every guest gets a QR. Your team scans at the entrance and sees VIP status, table and meal.',
  'home.feature.updates.title': 'Live updates',
  'home.feature.updates.body': 'Venue changed? Post one update and it reaches exactly the right guests by email and on their invitation.',

  'home.compare.eyebrow': 'Compare',
  'home.compare.title': 'Why hosts are moving to Bulava',
  'home.compare.bulava': 'Bulava',
  'home.compare.print': 'Printed cards',
  'home.compare.video': 'WhatsApp video',
  'home.compare.cost': 'Cost for 300 guests',
  'home.compare.cost.bulava': 'From free',
  'home.compare.cost.print': '₹15,000+',
  'home.compare.cost.video': '₹2,000–5,000',
  'home.compare.edit': 'Edit after sending',
  'home.compare.rsvp': 'RSVP tracking',
  'home.compare.perGuest': 'Different functions per guest',
  'home.compare.map': 'Venue map and directions',
  'home.compare.photos': 'Guest photo collection',
  'home.compare.languages': 'Multiple languages',

  'home.pricing.eyebrow': 'Pricing',
  'home.pricing.title': 'Simple. No surprises.',
  'home.pricing.subtitle': 'Start free. Upgrade a single event when you need more. Prices include GST.',
  'home.pricing.oneTime': 'one-time, per event',
  'home.pricing.yearly': 'per year',
  'home.pricing.free': 'Free forever',
  'home.pricing.popular': 'Most popular',
  'home.pricing.choose': 'Choose {plan}',
  'home.pricing.start': 'Start free',
  'plan.feature.events.max': '{limit} active event',
  'plan.feature.events.max.many': 'Up to {limit} events',
  'plan.feature.functions.max': 'Up to {limit} functions',
  'plan.feature.functions.unlimited': 'Unlimited functions',
  'plan.feature.guests.max': 'Up to {limit} guests',
  'plan.feature.guests.unlimited': 'Unlimited guests',
  'plan.feature.templates.0': 'Free templates',
  'plan.feature.templates.1': 'Free and Standard templates',
  'plan.feature.templates.2': 'Every template, including Premium',
  'plan.feature.photos': '{limit} guest photos',
  'plan.feature.video': '{limit} video renders',
  'plan.feature.videoHd': 'HD video',
  'plan.feature.noWatermark': 'No Bulava branding',
  'plan.feature.watermark': 'Small Bulava mark',
  'plan.feature.planner': 'Client workspace for planners',
  'plan.feature.rsvp': 'RSVP per function',
  'plan.feature.whatsapp': 'WhatsApp sharing',
  'plan.feature.whatsappMessages': '{limit} WhatsApp messages from Bulava',
  'plan.feature.whatsappMessages.unlimited': 'Unlimited WhatsApp messages from Bulava',

  'home.testimonials.eyebrow': 'Loved by hosts',
  'home.testimonials.title': 'Families who celebrated with Bulava',

  'home.faq.title': 'Questions, answered',
  'home.faq.1.q': 'Do guests need to install an app?',
  'home.faq.1.a': 'No. Guests open their invitation in any phone browser. Photo uploads by QR work the same way.',
  'home.faq.2.q': 'Can I invite some guests only to certain functions?',
  'home.faq.2.a': 'Yes. Add guests to groups such as Family or Friends and choose who is invited to each function. Each guest’s link shows only their functions.',
  'home.faq.3.q': 'Can I change details after sending?',
  'home.faq.3.a': 'Yes. Your invitation is a live page, so changes appear instantly. You can also post an update that reaches the right guests.',
  'home.faq.4.q': 'Which languages are supported?',
  'home.faq.4.a': 'Invitations are available in English, Hindi and Hinglish today, with more Indian languages being added. Dates are shown the Indian way.',
  'home.faq.5.q': 'Is my guest list private?',
  'home.faq.5.a': 'Yes. Invitations use secret links that you can revoke at any time, and you can add a PIN or one-time code. We never sell your data.',
  'home.faq.6.q': 'How do payments work?',
  'home.faq.6.a': 'You can start free. Upgrades are one-time payments per event through Razorpay (UPI, cards, net banking). Planners can choose the yearly Studio plan.',

  'home.final.title': 'Ready to send an invitation your guests will remember?',
  'home.final.subtitle': 'Create your event for free. Upgrade only if you need to.',

  'footer.templates': 'Templates',
  'footer.product': 'Product',
  'footer.company': 'Company',
  'footer.legal': 'Legal',
  'footer.support': 'Support',
  'footer.follow': 'Follow us',
  'footer.whatsappChat': 'Chat with us on WhatsApp',
  'social.instagram': 'Instagram',
  'social.facebook': 'Facebook',
  'social.youtube': 'YouTube',
  'social.x': 'X (Twitter)',
  'social.linkedin': 'LinkedIn',
  'social.pinterest': 'Pinterest',

  'templates.title': 'Invitation templates',
  'templates.subtitle': 'Live, personalised designs for weddings and every celebration. Filter by occasion, tradition and plan.',
  'templates.occasion': 'Occasion',
  'templates.tradition': 'Tradition',
  'templates.plan': 'Plan',
  'templates.format': 'Format',
  'templates.count': '{count} templates',
  'templates.showMore': 'Show more templates ({count} more)',
  'templates.detail.back': 'All templates',
  'templates.detail.demo': 'Open the live demo',
  'home.hero.demo': 'Watch a live demo',
  'home.scenes.eyebrow': 'New · Illustrated 3D collection',
  'home.scenes.title': 'Invitations that come alive',
  'home.scenes.subtitle': 'Temple gopurams at sunrise, palaces on the lake, marigold torans and sky lanterns: hand-drawn scenes in layered 3D that move as your guests scroll.',
  'home.scenes.demo': 'Open live demo',
  'home.scenes.details': 'Illustrated invitation templates',
  'home.scenes.previous': 'Previous design',
  'home.scenes.next': 'Next design',
  'template.demo': 'Live demo',
  'templates.demo.back': 'Back to {name}',
  'templates.demo.language': 'Switch language',

  // Quick start (the template page): a preview with real names before signing up
  'quick.title': 'See it with your names',
  'quick.subtitle': 'Three details and your invitation is ready to preview in under a minute. No password, nothing to pay.',
  'quick.eventType': 'What are you celebrating?',
  'quick.partnerOne': 'First name of the couple',
  'quick.partnerTwo': 'Second name',
  'quick.honoree': 'Who is being celebrated?',
  'quick.eventName': 'Name of the event',
  'quick.date': 'Date (you can change it later)',
  'quick.phone': 'WhatsApp number',
  'quick.phoneHint': 'We send your preview link here. Indian numbers need no country code.',
  'quick.updates': 'Keep me posted on WhatsApp about my invitation (optional)',
  'quick.submit': 'Create my preview',
  'quick.submitting': 'Setting up your invitation…',
  'quick.haveAccount': 'Already have an account?',
  'quick.signIn': 'Sign in',
  'quick.otp.title': 'Welcome back',
  'quick.otp.body': 'This number already has an account. We sent a 6-digit code to {target}. Enter it to continue with this design.',
  'quick.otp.code': 'Code from WhatsApp',
  'quick.otp.submit': 'Verify and continue',
  'quick.otp.change': 'Use another number',
  'quick.consentRequired': 'Please accept the Terms of Service and the Privacy Policy to continue.',
  'quick.close': 'Close',
  'templates.detail.for': 'Designed for',
  'templates.detail.languages': 'Languages',
  'templates.detail.includes': 'What’s included',
  'templates.detail.include.1': 'Personal link for every guest',
  'templates.detail.include.2': 'RSVP for each function',
  'templates.detail.include.3': 'Schedule, venue and directions',
  'templates.detail.include.4': 'Photo gallery and QR uploads',
  'templates.detail.include.5': 'Updates and reminders',
  'templates.detail.previewNote': 'Preview with sample details. Your names, dates and photos appear once you use it.',
  'templates.detail.mobile': 'Phone',
  'templates.detail.desktop': 'Desktop',

  'pricing.title': 'Plans for every celebration',
  'pricing.subtitle': 'Pay once per event. No subscriptions for families.',

  // Design v2: cursor label, hero status chips, section captions
  'cursor.view': 'View',
  'home.hero.chip.opened': 'Meera opened her invitation',
  'home.hero.chip.rsvp': 'Rahul is coming, with 2 guests',
  'home.hero.chip.event': 'Haldi · 14 Dec, 11 am',
  'home.hero.live': 'Live preview',
  'home.hero.scroll': 'Scroll to explore',
  'home.marquee.label': 'Designed for every tradition',
  'home.features.subtitle': 'Everything between the first invitation and the last photo, in one place your family can trust.',
  'home.how.subtitle': 'Most families send their first invitation the same evening.',
  'home.faq.subtitle': 'Still wondering? These are the questions families ask us most.',
  'home.faq.eyebrow': 'FAQ',
  'home.faq.more': 'Ask us anything',
  'home.compare.yes': 'Yes',
  'home.compare.no': 'No',
  'home.compare.partly': 'Partly',
  'home.testimonials.rating': '{rating} out of 5',

  // Not found and error pages
  'notFound.eyebrow': 'Error 404',
  'notFound.title': 'This page is not on the guest list',
  'notFound.body': 'The link may be old or mistyped. Let us take you back to the celebration.',
  'notFound.home': 'Back to home',
  'errorPage.title': 'Something went wrong',
  'errorPage.body': 'This page could not be loaded. Please try again in a moment.',
  'errorPage.retry': 'Try again',
  'errorPage.home': 'Go to the homepage',
  'errorPage.reference': 'Reference {id}',
} as const;
