/**
 * English source catalog. Every key used in the product must exist here;
 * other catalogs may be partial and fall back through fallbackChain().
 * Placeholders use {name} syntax.
 */
import { enDashboard } from './en-dashboard';
import { enMarketing } from './en-marketing';

const core = {
  // common
  'common.appName': 'Bulava',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.cancel': 'Cancel',
  'common.create': 'Create',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.back': 'Back',
  'common.loading': 'Loading…',
  'common.optional': 'Optional',
  'common.none': 'None',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.error': 'Something went wrong. Please try again.',
  'common.language': 'Language',
  'common.loadMore': 'Load more',

  // auth
  'auth.signup.title': 'Create your Bulava account',
  'auth.signup.submit': 'Create account',
  'auth.signup.haveAccount': 'Already have an account?',
  'auth.login.title': 'Sign in to Bulava',
  'auth.login.submit': 'Sign in',
  'auth.login.noAccount': 'New to Bulava?',
  'auth.google': 'Continue with Google',
  'auth.or': 'or',
  'auth.mfa.title': 'Two-step verification',
  'auth.mfa.body': 'Enter the 6-digit code from your authenticator app.',
  'auth.mfa.recoveryBody': 'Enter one of the recovery codes you saved when you turned on two-step sign-in. Each code works once.',
  'auth.mfa.code': 'Authenticator code',
  'auth.mfa.recovery': 'Recovery code',
  'auth.mfa.useRecovery': 'Use a recovery code instead',
  'auth.mfa.useCode': 'Use my authenticator app',
  'auth.mfa.verify': 'Verify and sign in',
  'auth.mfa.back': 'Back to sign in',
  'auth.logout': 'Sign out',
  'auth.field.name': 'Your name',
  'auth.field.email': 'Email',
  'auth.field.password': 'Password',
  'auth.field.passwordHint': 'At least 10 characters',
  'auth.consent.before': 'I have read and agree to the',
  'auth.consent.terms': 'Terms of Service',
  'auth.consent.and': 'and the',
  'auth.consent.privacy': 'Privacy Policy',
  'auth.consent.notice': 'We use your name and email address to create and secure your account and to send you messages about your events. You can download or delete your data at any time from Account settings, withdraw consent by deleting your account, and raise a complaint as the Privacy Policy explains.',
  'auth.consent.google': 'Please tick the box below to accept the Terms and the Privacy Policy, then continue with Google.',
  'auth.restore.title': 'Restore your account?',
  'auth.restore.body': 'You asked us to delete this account. It will be erased for good on {date}. Restore it now to get your events, guests and photos back.',
  'auth.restore.bodyNoDate': 'You asked us to delete this account. Restore it now to get your events, guests and photos back.',
  'auth.restore.submit': 'Restore my account',
  'auth.restore.cancel': 'Not now',
  'auth.deleted.notice': 'Your account is scheduled for deletion on {date}. Changed your mind? Sign in before then to restore it.',

  // landing
  'landing.headline': 'Invitations, RSVPs and memories for every Indian celebration',
  'landing.subheadline': 'Create an event, add your functions and guests, and share personal invitations that show each guest only what they are invited to.',
  'landing.cta': 'Get started free',

  // dashboard
  'dashboard.title': 'Your events',
  'dashboard.empty': 'You have not created any events yet.',
  'dashboard.createEvent': 'Create event',
  'dashboard.nav.overview': 'Overview',
  'dashboard.nav.functions': 'Functions',
  'dashboard.nav.groups': 'Guest groups',
  'dashboard.nav.guests': 'Guests',
  'dashboard.nav.invitations': 'Invitations',
  'dashboard.nav.rsvps': 'RSVPs',

  // event
  'event.field.title': 'Event title',
  'event.field.type': 'Event type',
  'event.field.language': 'Invitation language',
  'event.field.timezone': 'Time zone',
  'event.field.description': 'Description',
  'event.field.accessMode': 'Who can open the invitation',
  'event.field.partnerOne': 'Bride / first partner name',
  'event.field.partnerTwo': 'Groom / second partner name',
  'event.field.honoree': 'Name of the person being celebrated',
  'event.field.applyDefaults': 'Add suggested functions and guest groups',
  'event.create.title': 'Create an event',
  'event.status.DRAFT': 'Draft',
  'event.status.ACTIVE': 'Active',
  'event.status.COMPLETED': 'Completed',
  'event.status.ARCHIVED': 'Archived',
  'event.status.CANCELLED': 'Cancelled',
  'event.publish': 'Publish event',
  'event.published': 'Published',

  // access modes
  'access.PUBLIC': 'Public: anyone can open it',
  'access.PRIVATE_LINK': 'Private link: anyone with the link (you can add a PIN)',
  'access.INVITE_ONLY': 'Invite only: personal invitation links',
  'access.GROUP_RESTRICTED': 'Group restricted: only assigned guest groups',
  'access.SECRET_TOKEN': 'Secret link: a private link that stops working on a date you choose',
  'access.inherit': 'Same as event',
  'access.short.PUBLIC': 'Public',
  'access.short.PRIVATE_LINK': 'Private link',
  'access.short.INVITE_ONLY': 'Invite only',
  'access.short.GROUP_RESTRICTED': 'Group only',
  'access.short.SECRET_TOKEN': 'Secret link',

  // functions
  'function.title': 'Functions',
  'function.empty': 'No functions yet. Add Haldi, Sangeet, Reception and more.',
  'function.add': 'Add function',
  'function.field.name': 'Function name',
  'function.field.startsAt': 'Starts',
  'function.field.endsAt': 'Ends',
  'function.field.venueName': 'Venue name',
  'function.field.venueAddress': 'Venue address',
  'function.field.accessMode': 'Access',
  'function.field.audienceGroups': 'Invited guest groups',
  'function.status.CANCELLED': 'Cancelled',
  'function.status.POSTPONED': 'Postponed',

  // groups
  'group.title': 'Guest groups',
  'group.empty': 'No guest groups yet.',
  'group.add': 'Add group',
  'group.field.name': 'Group name',
  'group.memberCount': '{count} guests',

  // guests
  'guest.title': 'Guests',
  'guest.empty': 'No guests yet.',
  'guest.add': 'Add guest',
  'guest.field.name': 'Guest name',
  'guest.field.phone': 'Phone',
  'guest.field.email': 'Email',
  'guest.field.groups': 'Groups',
  'guest.field.functions': 'Invited to functions',
  'guest.field.guestLimit': 'Max attendees',
  'guest.field.plusOne': 'Plus-one allowed',
  'guest.assignFunctions': 'Function access',
  'guest.viaGroup': 'via group',
  'guest.denied': 'Blocked',
  'guest.assign.invite': 'Invited',

  // invitations (host side)
  'invitation.title': 'Invitations',
  'invitation.generate': 'Generate invitation',
  'invitation.regenerate': 'Regenerate link',
  'invitation.revoke': 'Revoke',
  'invitation.revoked': 'Revoked',
  'invitation.copyLink': 'Copy link',
  'invitation.shareWhatsApp': 'Share on WhatsApp',
  'invitation.whatsappMessage': 'Dear {guestName}, you are warmly invited to {eventTitle}. Please open your personal invitation: {url}',
  'invitation.scope.event': 'All authorized functions',
  'invitation.noInvitation': 'Not invited yet',
  'invitation.draftNotice': 'Your event is still a draft. Guests will see their invitation once you publish it from the Overview tab.',
  'invitation.uninvitedCount': '{count} guests do not have an invitation link yet.',
  'invitation.uninvitedCountOne': '1 guest does not have an invitation link yet.',
  'invitation.status.ACTIVE': 'Ready to share',
  'invitation.status.SENT': 'Sent',
  'invitation.status.OPENED': 'Opened',
  'invitation.status.RESPONDED': 'Responded',
  'invitation.status.REVOKED': 'Revoked',
  'invitation.status.EXPIRED': 'Expired',

  // invitation (guest side)
  'invitation.welcome': 'Welcome',
  'invitation.dear': 'Dear {guestName},',
  'invitation.youAreInvited': 'You are warmly invited',
  'invitation.wedding': 'Wedding',
  'invitation.reception': 'Reception',
  'invitation.venue': 'Venue',
  'invitation.when': 'When',
  'invitation.viewMap': 'View on map',
  'invitation.yourFunctions': 'Your invitation includes',
  'invitation.noFunctions': 'Details for your invitation will be shared soon.',
  'invitation.rsvp': 'RSVP',
  'invitation.expired': 'This invitation has expired.',
  'invitation.invalid': 'This invitation link is not valid.',
  'invitation.revokedMessage': 'This invitation is no longer active. Please contact your host.',
  'invitation.cancelled': 'This function has been cancelled.',
  'invitation.openPrompt': 'Open this link on your phone to see your personal invitation.',
  'invitation.notPublished': 'This invitation is not available yet. Please check back soon.',

// template sections
  'template.couple.title': 'The Couple',
  'template.about.title': 'About',
  'template.agenda.title': 'Agenda',
  'template.family.title': 'With the blessings of',
  'template.story.title': 'Our Story',
  'template.schedule.title': 'The Celebrations',
  'template.venue.title': 'The Venue',
  'template.gallery.title': 'Moments',
  'template.gallery.open': 'Open photo {number} of {total}',
  'template.gallery.next': 'Next photo',
  'template.gallery.previous': 'Previous photo',
  'template.gallery.swipe': 'Swipe to explore',
  'template.couple.flip': 'Turn over the card for {name}',
  'template.couple.tapToTurn': 'Tap to turn',
  'template.tapToReveal': 'Tap to reveal',
  'template.schedule.flip': 'Turn over {name} for the time and venue',
  'template.accommodation.title': 'Stay',
  'template.travel.title': 'Travel',
  'template.gift.title': 'Gifts',
  'template.announcements.title': 'Updates from the hosts',
  'template.photoShare.title': 'Share your photos',
  'template.countdown.title': 'Counting down',
  'template.countdown.days': 'Days',
  'template.countdown.hours': 'Hours',
  'template.countdown.minutes': 'Minutes',
  'template.countdown.seconds': 'Seconds',
  'template.getDirections': 'Get directions',
  'template.venue.map': 'Map of {venue}',
  'template.status.postponed': 'This function has been postponed.',
  'template.footer.thanks': 'We look forward to celebrating with you',
  'template.madeWith': 'Made with Bulava',
  'template.openInvite': 'Tap to open',
  'template.intro.lanterns': 'Tap to light the lanterns',
  'template.intro.seal': 'Tap to break the seal',
  'template.intro.scratch': 'Scratch to reveal',
  'template.intro.reveal': 'Reveal',
  'template.music.play': 'Play music',
  'template.music.pause': 'Pause music',
  'template.menu.title': 'The Menu',
  'template.saveTheDate': 'Save the Date',
  'template.joinUs': 'Please join us',
  'template.celebrateWith': 'Come celebrate with us',
  'template.weddingOf': 'The wedding of',
  'template.weds': 'weds',
  'template.film.families': 'Together with their families',
  'template.film.celebrations': 'The celebrations',
  'template.engagementOf': 'The engagement of',
  'template.birthdayOf': 'Birthday celebration',
  'template.blessings': 'Your presence and blessings are requested',

// guest pages
  'invite.photos.upload': 'Upload photos',
  'invite.photos.gallery': 'View gallery',
  'invite.checkin.title': 'Your entry pass',
  'invite.checkin.body': 'Show this QR code at the entrance.',
  'email.reminder.rsvp.subject': 'Will you join us? {event}',
  'email.reminder.rsvp.body': 'We would love to know if you can make it to {event}. Please let the hosts know with a quick reply.',
  'email.reminder.rsvp.cta': 'Reply now',
  'email.reminder.function.subject': 'Reminder: {function} · {when}',
  'email.reminder.function.body': 'A reminder that {function} for {event} is coming up. We look forward to seeing you!',
  'wall.screen.live': 'Live',
  'wall.screen.count': '{count} photos',
  'wall.screen.scan': 'Scan to share your photos',
  'wall.screen.empty': 'Photos will appear here as guests share them.',
  'wall.screen.sharedBy': 'Shared by {name}',
  'wall.screen.justNow': 'Just shared',
  'wall.screen.unavailable': 'This photo wall is not available right now.',
  'wall.screen.fullscreen': 'Full screen',
  'invite.logistics.title': 'Your stay & travel',
  'invite.logistics.stay': 'Where you are staying',
  'invite.logistics.room': 'Room {room}',
  'invite.logistics.checkIn': 'Check-in: {when}',
  'invite.logistics.checkOut': 'Check-out: {when}',
  'invite.logistics.map': 'Open map',
  'invite.logistics.seats': 'Your table',
  'invite.logistics.seat': 'Table {table}',
  'invite.logistics.seatWithSeat': 'Table {table}, seat {seat}',
  'invite.logistics.arrival': 'Your arrival',
  'invite.logistics.departure': 'Your departure',
  'invite.logistics.travellers': '{count} travelling',
  'invite.logistics.pickupRequested': 'Pickup requested',
  'invite.logistics.dropRequested': 'Drop requested',
  'invite.logistics.arranged': 'Arranged: {note}',
  'invite.logistics.share': 'Share your travel plans',
  'invite.logistics.shareHint': 'Tell the hosts when you arrive and leave, so they can plan pickups and rooms.',
  'invite.logistics.change': 'Change travel plans',
  'invite.logistics.save': 'Save travel plans',
  'invite.logistics.saved': 'Thank you! Your travel plans are saved.',
  'invite.logistics.addArrival': 'Add your arrival',
  'invite.logistics.addDeparture': 'Add your departure',
  'invite.logistics.remove': 'Remove',
  'invite.logistics.cancel': 'Cancel',
  'invite.logistics.mode': 'Travelling by',
  'invite.logistics.mode.FLIGHT': 'Flight',
  'invite.logistics.mode.TRAIN': 'Train',
  'invite.logistics.mode.ROAD': 'Car',
  'invite.logistics.mode.BUS': 'Bus',
  'invite.logistics.mode.OTHER': 'Other',
  'invite.logistics.carrier': 'Airline or train name',
  'invite.logistics.number': 'Flight or train number',
  'invite.logistics.arriveAt': 'Arriving (date and time)',
  'invite.logistics.leaveAt': 'Leaving (date and time)',
  'invite.logistics.place': 'Airport, station or city',
  'invite.logistics.people': 'People travelling',
  'invite.logistics.needPickup': 'Please arrange a pickup',
  'invite.logistics.needDrop': 'Please arrange a drop',
  'invite.seat': 'Your table: {table}',
  'otp.title': 'Confirm it’s you',
  'otp.body': 'For privacy, your host asks guests to confirm with a one-time code. We will send it to {target}.',
  'otp.send': 'Send code',
  'otp.sent': 'We sent a 6-digit code to {target}.',
  'otp.code': '6-digit code',
  'otp.verify': 'Verify',
  'otp.resend': 'Send a new code',
  'pin.title': 'This event is protected',
  'pin.body': 'Enter the PIN shared by your host.',
  'pin.label': 'PIN',
  'pin.submit': 'Open',
  'event.private.title': 'This is a private event',
  'event.private.body': 'Please open the invitation link your host shared with you.',
  'upload.title': 'Share your photos',
  'upload.subtitle': 'Add your photos and videos from {event}. No app needed.',
  'upload.select': 'Choose photos',
  'upload.camera': 'Take a photo',
  'upload.name': 'Your name',
  'upload.submit': 'Upload {count}',
  'upload.submitNone': 'Upload',
  'upload.uploading': 'Uploading {done} of {total}…',
  'upload.done': 'Thank you! {count} uploaded.',
  'upload.moderated': 'Your photos will appear after the hosts approve them.',
  'upload.failed': '{count} could not be uploaded.',
  'upload.closed': 'Uploads for this album are closed.',
  'upload.more': 'Upload more',
  'upload.gallery': 'See the gallery',
  'gallery.title': 'Gallery',
  'gallery.empty': 'No photos yet. Be the first to share!',
  'gallery.private': 'This gallery is only visible to invited guests. Open it from your invitation.',
  'gallery.download': 'Download',
  'checkin.title': 'Guest check-in',
  'checkin.vip': 'VIP',
  'checkin.invitedTo': 'Invited to',
  'checkin.headcount': 'People arriving',
  'checkin.action': 'Check in',
  'checkin.reentry': 'Allow re-entry',
  'checkin.done': '{name} checked in.',
  'checkin.already': 'Already checked in at {time}',
  'checkin.table': 'Table {table}',
  'checkin.tableSeat': 'Table {table} · Seat {seat}',
  'checkin.dietary': 'Dietary: {dietary}',
  'checkin.stayRoom': '{hotel} · Room {room}',
  'checkin.notFound': 'This QR code does not match a guest you can check in.',

  // email
  'email.openInvitation': 'Open your invitation',
  'email.registration.subject': 'Your registration for {event}',
  'email.registration.PENDING': 'Thank you for registering. The hosts will review your registration and you will hear from us soon.',
  'email.registration.WAITLISTED': 'All places are currently taken, so you are on the waiting list. We will email you if a place opens up.',
  'email.registration.REJECTED': 'Unfortunately the hosts could not confirm your registration this time.',
  'email.registration.CANCELLED': 'Your registration has been cancelled by the hosts.',

  // public registration
  'register.title': 'Register to attend',
  'register.intro': 'Share your details to receive your personal invitation.',
  'register.approvalNote': 'The hosts review every registration before confirming it.',
  'register.name': 'Your name',
  'register.email': 'Email',
  'register.phone': 'Mobile number',
  'register.contactHint': 'Enter an email address or a mobile number (or both).',
  'register.consent': 'I agree to share these details with the hosts of this event.',
  'register.submit': 'Register',
  'register.joinWaitlist': 'Join the waiting list',
  'register.sending': 'Registering…',
  'register.spotsLeft': '{count} places left',
  'register.full': 'Registration is full.',
  'register.waitlistNote': 'All places are taken. You can join the waiting list.',
  'register.closed': 'Registration is closed.',
  'register.closesAt': 'Registration closes on {date}',
  'register.yes': 'Yes',
  'register.no': 'No',
  'register.choose': 'Choose one',
  'register.done.CONFIRMED': 'You are registered!',
  'register.done.CONFIRMED.body': 'Your personal invitation is ready. This link is yours alone, so please do not share it.',
  'register.done.PENDING': 'Thank you! Your registration is waiting for the hosts to confirm it.',
  'register.done.WAITLISTED': 'You are on the waiting list. We will let you know if a place opens up.',
  'register.openInvitation': 'Open my invitation',

  // rsvp
  'rsvp.title': 'Will you attend?',
  'rsvp.attending': 'Yes, I will attend',
  'rsvp.declined': 'Sorry, I cannot attend',
  'rsvp.maybe': 'Maybe',
  'rsvp.attendeeCount': 'Number of guests',
  'rsvp.attendeeLimit': 'Up to {count} people',
  'rsvp.message': 'Message for the hosts',
  'rsvp.submit': 'Send RSVP',
  'rsvp.update': 'Update RSVP',
  'rsvp.chooseOne': 'Please choose a response for at least one function.',
  'rsvp.thanks': 'Thank you! Your response has been saved.',
  'rsvp.status.PENDING': 'Awaiting reply',
  'rsvp.status.ATTENDING': 'Attending',
  'rsvp.status.DECLINED': 'Not attending',
  'rsvp.status.MAYBE': 'Maybe',
  'rsvp.summary.title': 'RSVP summary',
  'rsvp.summary.headcount': 'Expected headcount',
  'rsvp.summary.invited': 'Invited',

  // errors (codes returned by the API)
  'error.UNAUTHENTICATED': 'Please sign in to continue.',
  'error.FORBIDDEN': 'You do not have permission to do that.',
  'error.NOT_FOUND': 'Not found.',
  'error.VALIDATION_FAILED': 'Please check the highlighted fields.',
  'error.EMAIL_TAKEN': 'An account with this email already exists.',
  'error.INVALID_CREDENTIALS': 'Email or password is incorrect.',
  'error.INVITATION_EXPIRED': 'This invitation has expired.',
  'error.INVITATION_REVOKED': 'This invitation is no longer active.',
  'error.INVITATION_INVALID': 'This invitation link is not valid.',
  'error.FUNCTION_NOT_AUTHORIZED': 'This invitation does not include that function.',
  'error.RATE_LIMITED': 'Too many attempts. Please wait a moment and try again.',
  'error.ATTENDEE_LIMIT_EXCEEDED': 'The number of guests exceeds your invitation limit.',
  'error.MFA_REQUIRED': 'Staff tools need two-step sign-in. Turn it on in Security, then sign in again.',
  'error.MFA_INVALID': 'That code did not work. Check your authenticator app and try again.',
  'error.MFA_CHALLENGE_EXPIRED': 'This step expired. Please start again.',
  'error.MFA_ALREADY_ENABLED': 'Two-step sign-in is already on.',
  'error.MFA_NOT_ENABLED': 'Two-step sign-in is not on.',
  'error.REMINDER_INVALID': 'Choose a reminder time in the future.',
  'error.DOMAIN_INVALID': 'That does not look like a domain you can use. Enter something like amanweddsriya.com or invite.yourname.in.',
  'error.DOMAIN_TAKEN': 'This domain is already connected to another event.',
  'error.DOMAIN_UNAVAILABLE': 'Custom domains are not available yet.',
  'error.SUPER_ADMIN_PROTECTED': 'The Super Admin cannot be changed or suspended.',
  'error.CONSENT_REQUIRED': 'To create an account, please accept the Terms of Service and the Privacy Policy first.',
  'error.RESTORE_EXPIRED': 'This step expired. Please sign in again to restore your account.',
  'error.ORDER_NOT_PAYABLE': 'This order can no longer be paid. Choose a plan to start again.',
  'error.PAYMENTS_UNAVAILABLE': 'Online payment is not available right now. Please try again in a little while.',
  'error.PAYMENT_VERIFICATION_FAILED': 'We could not confirm this payment yet. If money left your account, it will be confirmed or refunded automatically.',
  'error.PAGE_SLUG_TAKEN': 'Another page already uses this address.',
  'error.PAGE_PROTECTED': 'Built-in pages keep their address and layout, stay published and cannot be deleted.',
  'error.EMAIL_UNAVAILABLE': 'Email is not set up yet, so the reply cannot be sent. Set up email under Integrations first.',
  'error.WHATSAPP_UNAVAILABLE': 'Sending on WhatsApp is not available right now. Share each invitation with the WhatsApp button instead.',
  'error.GOOGLE_UNAVAILABLE': 'Google sign-in is not available right now. Please use your email and password.',
  'error.GOOGLE_FAILED': 'Google sign-in did not complete. Please try again.',
  'error.GOOGLE_CANCELLED': 'Google sign-in was cancelled.',
  'error.GOOGLE_LINK_REQUIRED': 'An account with this email already exists. Sign in with your password, then connect Google under Account.',
  'error.GOOGLE_ALREADY_LINKED': 'That Google account is already connected to another Bulava account.',
  'error.GOOGLE_UNLINK_BLOCKED': 'Set a password before disconnecting Google, so you can still sign in.',
  'error.REMINDER_TOO_SOON': 'A reminder went out recently. Please wait a few hours before sending another.',
  'error.MEMBER_NOT_REGISTERED': 'This account is closed or suspended, so it cannot join the team.',
  'error.REGISTRATION_NOT_AVAILABLE': 'Registration needs an event shared by link: public, private link or secret link.',
  'error.REGISTRATION_CLOSED': 'Registration is closed for this event.',
  'error.REGISTRATION_FULL': 'Sorry, registration is full.',
  'error.REGISTRATION_INVALID': 'Please check your answers and try again.',
  'error.ALREADY_REGISTERED': 'You are already registered. Check your email or messages for your invitation link.',
  // Shared event links, photo album folders, team invitations
  'event.linkExpired.title': 'This link has expired',
  'event.linkExpired.body': 'Ask your host for a new invitation link.',
  'event.linkInvalid.title': 'This link is no longer valid',
  'event.linkInvalid.body': 'Your host may have replaced it. Ask them for the current link.',
  'share.whatsappMessage': '{eventTitle}\n\nYou are warmly invited! Open the invitation: {url}',
  'upload.album': 'Which function are these from?',
  'gallery.all': 'All',
  'error.EVENT_LINK_EXPIRED': 'This invitation link has expired. Ask your host for a new one.',
  'error.TEAM_INVITE_INVALID': 'This invitation link is not valid any more. Ask the host to send a new one.',
  'error.TEAM_INVITE_CODE_INVALID': 'That code is not correct.',
  'error.TEAM_INVITE_LOCKED': 'This invitation was locked after too many wrong codes. Ask the host to send a new one.',
  'error.TEAM_INVITE_SIGN_IN': 'An account with this email already exists. Sign in to join the team.',
  'error.TEAM_INVITE_WRONG_ACCOUNT': 'This invitation was sent to another email. Sign in with that account to join.',
} as const;

export const en = { ...core, ...enMarketing, ...enDashboard } as const;

export type MessageKey = keyof typeof en;
export type Catalog = Partial<Record<MessageKey, string>>;
