import type { Catalog } from './en';

/**
 * Hindi catalog. Guest-facing strings are complete; host-dashboard strings fall
 * back to English until professionally translated.
 * NOTE: Translations should be reviewed by a native speaker before launch.
 */
export const hi: Catalog = {
  'common.appName': 'बुलावा',
  'common.save': 'सहेजें',
  'common.cancel': 'रद्द करें',
  'common.loading': 'लोड हो रहा है…',
  'common.optional': 'वैकल्पिक',
  'common.yes': 'हाँ',
  'common.no': 'नहीं',
  'common.error': 'कुछ गड़बड़ हो गई। कृपया फिर से प्रयास करें।',
  'common.language': 'भाषा',

  'invitation.welcome': 'स्वागत है',
  'invitation.dear': 'प्रिय {guestName},',
  'invitation.youAreInvited': 'आप सादर आमंत्रित हैं',
  'invitation.wedding': 'विवाह',
  'invitation.reception': 'रिसेप्शन',
  'invitation.venue': 'स्थान',
  'invitation.when': 'समय',
  'invitation.viewMap': 'नक्शे पर देखें',
  'invitation.yourFunctions': 'आपके निमंत्रण में शामिल है',
  'invitation.noFunctions': 'आपके निमंत्रण का विवरण जल्द ही साझा किया जाएगा।',
  'invitation.rsvp': 'उत्तर दें',
  'invitation.expired': 'इस निमंत्रण की अवधि समाप्त हो गई है।',
  'invitation.invalid': 'यह निमंत्रण लिंक मान्य नहीं है।',
  'invitation.revokedMessage': 'यह निमंत्रण अब सक्रिय नहीं है। कृपया अपने मेज़बान से संपर्क करें।',
  'invitation.cancelled': 'यह कार्यक्रम रद्द कर दिया गया है।',
  'invitation.openPrompt': 'अपना व्यक्तिगत निमंत्रण देखने के लिए यह लिंक अपने फ़ोन पर खोलें।',
  'invitation.notPublished': 'यह निमंत्रण अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद देखें।',
  'invitation.whatsappMessage': 'प्रिय {guestName}, {eventTitle} में आप सादर आमंत्रित हैं। कृपया अपना निमंत्रण खोलें: {url}',

  'template.couple.title': 'वर-वधू',
  'template.about.title': 'परिचय',
  'template.agenda.title': 'कार्यक्रम सूची',
  'template.family.title': 'आशीर्वाद सहित',
  'template.story.title': 'हमारी कहानी',
  'template.schedule.title': 'शुभ कार्यक्रम',
  'template.venue.title': 'स्थान',
  'template.gallery.title': 'यादगार पल',
  'template.gallery.open': 'फ़ोटो {number} / {total} खोलें',
  'template.gallery.next': 'अगली फ़ोटो',
  'template.gallery.previous': 'पिछली फ़ोटो',
  'template.gallery.swipe': 'स्वाइप करके देखें',
  'template.couple.flip': '{name} का कार्ड पलटें',
  'template.couple.tapToTurn': 'पलटने के लिए छुएँ',
  'template.tapToReveal': 'देखने के लिए छुएँ',
  'template.schedule.flip': 'समय और स्थान के लिए {name} पलटें',
  'template.accommodation.title': 'ठहरने की व्यवस्था',
  'template.travel.title': 'यात्रा',
  'template.gift.title': 'उपहार',
  'template.announcements.title': 'मेज़बान की ओर से सूचना',
  'template.photoShare.title': 'अपनी तस्वीरें साझा करें',
  'template.countdown.title': 'शुभ घड़ी में बाकी',
  'template.countdown.days': 'दिन',
  'template.countdown.hours': 'घंटे',
  'template.countdown.minutes': 'मिनट',
  'template.countdown.seconds': 'सेकंड',
  'template.countdown.short.days': 'दिन',
  'template.countdown.short.hours': 'घंटे',
  'template.countdown.short.minutes': 'मिनट',
  'template.countdown.short.seconds': 'सेकंड',
  'template.getDirections': 'रास्ता देखें',
  'template.addToCalendar': 'कैलेंडर में जोड़ें',
  'template.details.date': 'तारीख',
  'template.details.time': 'समय',
  'template.details.venue': 'स्थान',
  'template.details.address': 'पता',
  'template.details.city': 'शहर',
  'template.venue.map': '{venue} का नक्शा',
  'template.status.postponed': 'यह कार्यक्रम स्थगित कर दिया गया है।',
  'template.footer.thanks': 'आपके आगमन की प्रतीक्षा रहेगी',
  'template.madeWith': 'बुलावा द्वारा निर्मित',
  'template.openInvite': 'खोलने के लिए छुएँ',
  'template.saveTheDate': 'तारीख याद रखें',
  'template.joinUs': 'कृपया पधारें',
  'template.celebrateWith': 'हमारे साथ उत्सव मनाएँ',
  'template.weddingOf': 'शुभ विवाह',
  'template.weds': 'संग',
  'template.film.families': 'परिवारों के आशीर्वाद सहित',
  'template.film.celebrations': 'मांगलिक कार्यक्रम',
  'template.engagementOf': 'सगाई समारोह',
  'template.birthdayOf': 'जन्मदिन समारोह',
  'template.mehendi': 'मेहंदी समारोह',
  'template.haldi': 'हल्दी की रस्म',
  'template.sangeet': 'संगीत संध्या',
  'template.reception': 'विवाह स्वागत समारोह',
  'template.anniversary': 'वर्षगांठ समारोह',
  'template.babyShower': 'गोद भराई',
  'template.naming': 'नामकरण संस्कार',
  'template.mundan': 'मुंडन संस्कार',
  'template.puja': 'ईश्वर के आशीर्वाद से',
  'template.blessings': 'आपकी उपस्थिति एवं आशीर्वाद प्रार्थनीय है',

  'invite.photos.upload': 'तस्वीरें अपलोड करें',
  'invite.photos.gallery': 'गैलरी देखें',
  'invite.checkin.title': 'आपका प्रवेश पास',
  'invite.checkin.body': 'प्रवेश द्वार पर यह QR कोड दिखाएँ।',
  'email.reminder.rsvp.subject': 'क्या आप हमारे साथ होंगे? {event}',
  'email.reminder.rsvp.body': 'हमें जानकर खुशी होगी कि आप {event} में आ पाएँगे या नहीं। कृपया मेज़बानों को जल्दी से जवाब दें।',
  'email.reminder.rsvp.cta': 'अभी जवाब दें',
  'email.reminder.function.subject': 'याद दिला रहे हैं: {function} · {when}',
  'email.reminder.function.body': 'याद दिला दें कि {event} का {function} जल्द ही है। हमें आपसे मिलने का इंतज़ार है!',
  'wall.screen.live': 'लाइव',
  'wall.screen.count': '{count} तस्वीरें',
  'wall.screen.scan': 'तस्वीरें देखने और डाउनलोड करने के लिए स्कैन करें',
  'wall.screen.empty': 'मेहमानों की साझा की गई तस्वीरें यहाँ दिखाई देंगी।',
  'wall.screen.sharedBy': '{name} द्वारा साझा',
  'wall.screen.justNow': 'अभी साझा की गई',
  'wall.screen.unavailable': 'यह फ़ोटो वॉल अभी उपलब्ध नहीं है।',
  'wall.screen.fullscreen': 'पूर्ण स्क्रीन',
  'invite.logistics.title': 'आपका ठहराव और यात्रा',
  'invite.logistics.stay': 'आप कहाँ ठहरेंगे',
  'invite.logistics.room': 'कमरा {room}',
  'invite.logistics.checkIn': 'चेक-इन: {when}',
  'invite.logistics.checkOut': 'चेक-आउट: {when}',
  'invite.logistics.map': 'नक्शा खोलें',
  'invite.logistics.seats': 'आपकी टेबल',
  'invite.logistics.seat': 'टेबल {table}',
  'invite.logistics.seatWithSeat': 'टेबल {table}, सीट {seat}',
  'invite.logistics.arrival': 'आपका आगमन',
  'invite.logistics.departure': 'आपकी वापसी',
  'invite.logistics.travellers': '{count} लोग यात्रा कर रहे हैं',
  'invite.logistics.pickupRequested': 'पिकअप का अनुरोध किया गया',
  'invite.logistics.dropRequested': 'ड्रॉप का अनुरोध किया गया',
  'invite.logistics.arranged': 'व्यवस्था: {note}',
  'invite.logistics.share': 'अपनी यात्रा की जानकारी दें',
  'invite.logistics.shareHint': 'मेज़बानों को बताएँ कि आप कब पहुँचेंगे और कब जाएँगे, ताकि वे पिकअप और कमरों की व्यवस्था कर सकें।',
  'invite.logistics.change': 'यात्रा की जानकारी बदलें',
  'invite.logistics.save': 'यात्रा की जानकारी सहेजें',
  'invite.logistics.saved': 'धन्यवाद! आपकी यात्रा की जानकारी सहेज ली गई है।',
  'invite.logistics.addArrival': 'अपना आगमन जोड़ें',
  'invite.logistics.addDeparture': 'अपनी वापसी जोड़ें',
  'invite.logistics.remove': 'हटाएँ',
  'invite.logistics.cancel': 'रद्द करें',
  'invite.logistics.mode': 'यात्रा का साधन',
  'invite.logistics.mode.FLIGHT': 'हवाई जहाज़',
  'invite.logistics.mode.TRAIN': 'ट्रेन',
  'invite.logistics.mode.ROAD': 'कार',
  'invite.logistics.mode.BUS': 'बस',
  'invite.logistics.mode.OTHER': 'अन्य',
  'invite.logistics.carrier': 'एयरलाइन या ट्रेन का नाम',
  'invite.logistics.number': 'फ़्लाइट या ट्रेन नंबर',
  'invite.logistics.arriveAt': 'पहुँचने का समय (तारीख़ और समय)',
  'invite.logistics.leaveAt': 'जाने का समय (तारीख़ और समय)',
  'invite.logistics.place': 'हवाई अड्डा, स्टेशन या शहर',
  'invite.logistics.people': 'यात्रा करने वाले लोग',
  'invite.logistics.needPickup': 'कृपया पिकअप की व्यवस्था करें',
  'invite.logistics.needDrop': 'कृपया ड्रॉप की व्यवस्था करें',
  'invite.seat': 'आपकी टेबल: {table}',
  'otp.title': 'पुष्टि करें कि यह आप हैं',
  'otp.body': 'गोपनीयता के लिए, मेज़बान ने एक बार का कोड माँगा है। हम इसे {target} पर भेजेंगे।',
  'otp.send': 'कोड भेजें',
  'otp.sent': 'हमने {target} पर 6 अंकों का कोड भेजा है।',
  'otp.code': '6 अंकों का कोड',
  'otp.verify': 'पुष्टि करें',
  'otp.resend': 'नया कोड भेजें',
  'upload.title': 'अपनी तस्वीरें साझा करें',
  'upload.subtitle': '{event} की अपनी तस्वीरें और वीडियो जोड़ें। किसी ऐप की ज़रूरत नहीं।',
  'upload.select': 'तस्वीरें चुनें',
  'upload.camera': 'फ़ोटो लें',
  'upload.name': 'आपका नाम',
  'upload.submit': '{count} अपलोड करें',
  'upload.submitNone': 'अपलोड करें',
  'upload.uploading': '{total} में से {done} अपलोड हो रही हैं…',
  'upload.done': 'धन्यवाद! {count} अपलोड हो गईं।',
  'upload.moderated': 'मेज़बान की स्वीकृति के बाद आपकी तस्वीरें दिखेंगी।',
  'upload.more': 'और अपलोड करें',
  'upload.gallery': 'गैलरी देखें',
  'gallery.title': 'गैलरी',
  'gallery.empty': 'अभी कोई तस्वीर नहीं। सबसे पहले साझा करें!',
  'gallery.downloadPhoto': 'तस्वीर डाउनलोड करें',
  'upload.teamOnly': 'इस एल्बम में तस्वीरें मेज़बान और उनकी टीम जोड़ते हैं।',
  'upload.fromInvitation': 'आमंत्रित मेहमान अपने निमंत्रण के लिंक से तस्वीरें जोड़ सकते हैं।',
  'phone.countryCode': 'देश कोड',
  'error.UPLOADS_CLOSED': 'इस एल्बम में तस्वीरें केवल मेज़बान और उनकी टीम जोड़ते हैं।',
  'error.UPLOAD_NEEDS_INVITATION': 'तस्वीरें जोड़ने के लिए एल्बम अपने निमंत्रण से खोलें।',

  'email.openInvitation': 'अपना निमंत्रण खोलें',

  'rsvp.title': 'क्या आप आएँगे?',
  'rsvp.attending': 'हाँ, मैं आऊँगा/आऊँगी',
  'rsvp.declined': 'क्षमा करें, नहीं आ पाऊँगा/पाऊँगी',
  'rsvp.maybe': 'शायद',
  'rsvp.attendeeCount': 'मेहमानों की संख्या',
  'rsvp.attendeeLimit': 'अधिकतम {count} लोग',
  'rsvp.message': 'मेज़बान के लिए संदेश',
  'rsvp.submit': 'उत्तर भेजें',
  'rsvp.update': 'उत्तर बदलें',
  'rsvp.chooseOne': 'कृपया कम से कम एक कार्यक्रम के लिए उत्तर चुनें।',
  'rsvp.thanks': 'धन्यवाद! आपका उत्तर सहेज लिया गया है।',
  'rsvp.status.PENDING': 'उत्तर प्रतीक्षित',
  'rsvp.status.ATTENDING': 'आ रहे हैं',
  'rsvp.status.DECLINED': 'नहीं आ रहे',
  'rsvp.status.MAYBE': 'शायद',

  'error.INVITATION_EXPIRED': 'इस निमंत्रण की अवधि समाप्त हो गई है।',
  'error.INVITATION_REVOKED': 'यह निमंत्रण अब सक्रिय नहीं है।',
  'error.INVITATION_INVALID': 'यह निमंत्रण लिंक मान्य नहीं है।',
  'error.RATE_LIMITED': 'बहुत अधिक प्रयास। कृपया थोड़ी देर बाद फिर से प्रयास करें।',
  'error.PHONE_TAKEN': 'इस WhatsApp नंबर से पहले से एक खाता है। उसी से साइन इन करें।',
  'error.ACCOUNT_UNVERIFIED': 'पहले अपना खाता सुरक्षित करें: WhatsApp नंबर सत्यापित करें, या ईमेल और पासवर्ड जोड़ें।',
  'error.PHONE_OTP_UNAVAILABLE': 'WhatsApp कोड अभी उपलब्ध नहीं हैं। कृपया ईमेल से साइन इन करें।',

  'preview.badge': 'पूर्वावलोकन',
  'preview.note': 'यह निमंत्रण का पूर्वावलोकन है। प्रकाशित होने के बाद मेहमान इसे बिना निशान के देखेंगे।',
  'preview.share': 'WhatsApp पर साझा करें',
  'preview.shareText': 'हमारा निमंत्रण देखिए: {url}',
  'preview.edit': 'डिज़ाइन बदलें',
  'preview.publish': 'निमंत्रण प्रकाशित करें',
  'preview.makeYourOwn': 'अपना निमंत्रण बनाएँ',
  'preview.notFound.title': 'यह पूर्वावलोकन लिंक मान्य नहीं है',
  'preview.notFound.body': 'हो सकता है मेज़बान ने इसे बदल दिया हो। उनसे नया लिंक माँगें।',
  'error.ATTENDEE_LIMIT_EXCEEDED': 'मेहमानों की संख्या आपके निमंत्रण की सीमा से अधिक है।',
  'error.REGISTRATION_CLOSED': 'इस कार्यक्रम के लिए पंजीकरण बंद है।',
  'error.REGISTRATION_FULL': 'क्षमा करें, पंजीकरण पूरा हो चुका है।',
  'error.REGISTRATION_INVALID': 'कृपया अपने उत्तर जाँचें और फिर से प्रयास करें।',
  'error.ALREADY_REGISTERED': 'आप पहले से पंजीकृत हैं। अपने निमंत्रण लिंक के लिए ईमेल या संदेश देखें।',
  'register.title': 'शामिल होने के लिए पंजीकरण करें',
  'register.intro': 'अपना व्यक्तिगत निमंत्रण पाने के लिए अपनी जानकारी दें।',
  'register.approvalNote': 'मेज़बान हर पंजीकरण की पुष्टि से पहले समीक्षा करते हैं।',
  'register.name': 'आपका नाम',
  'register.email': 'ईमेल',
  'register.phone': 'मोबाइल नंबर',
  'register.contactHint': 'ईमेल पता या मोबाइल नंबर (या दोनों) दर्ज करें।',
  'register.consent': 'मैं इस कार्यक्रम के मेज़बानों के साथ यह जानकारी साझा करने के लिए सहमत हूँ।',
  'register.submit': 'पंजीकरण करें',
  'register.joinWaitlist': 'प्रतीक्षा सूची में शामिल हों',
  'register.sending': 'पंजीकरण हो रहा है…',
  'register.spotsLeft': '{count} स्थान शेष',
  'register.full': 'पंजीकरण पूरा हो चुका है।',
  'register.waitlistNote': 'सभी स्थान भर चुके हैं। आप प्रतीक्षा सूची में शामिल हो सकते हैं।',
  'register.closed': 'पंजीकरण बंद है।',
  'register.closesAt': 'पंजीकरण {date} को बंद होगा',
  'register.yes': 'हाँ',
  'register.no': 'नहीं',
  'register.choose': 'एक चुनें',
  'register.done.CONFIRMED': 'आपका पंजीकरण हो गया!',
  'register.done.CONFIRMED.body': 'आपका व्यक्तिगत निमंत्रण तैयार है। यह लिंक केवल आपके लिए है, कृपया इसे साझा न करें।',
  'register.done.PENDING': 'धन्यवाद! आपका पंजीकरण मेज़बानों की पुष्टि की प्रतीक्षा में है।',
  'register.done.WAITLISTED': 'आप प्रतीक्षा सूची में हैं। स्थान खाली होने पर हम आपको बताएँगे।',
  'register.openInvitation': 'मेरा निमंत्रण खोलें',
  'email.registration.subject': '{event} के लिए आपका पंजीकरण',
  'email.registration.PENDING': 'पंजीकरण के लिए धन्यवाद। मेज़बान आपके पंजीकरण की समीक्षा करेंगे और जल्द ही आपको सूचित किया जाएगा।',
  'email.registration.WAITLISTED': 'अभी सभी स्थान भरे हुए हैं, इसलिए आप प्रतीक्षा सूची में हैं। स्थान खाली होने पर हम आपको ईमेल करेंगे।',
  'email.registration.REJECTED': 'क्षमा करें, इस बार मेज़बान आपके पंजीकरण की पुष्टि नहीं कर सके।',
  'email.registration.CANCELLED': 'मेज़बानों ने आपका पंजीकरण रद्द कर दिया है।',
  'template.intro.lanterns': 'दीप जलाने के लिए टैप करें',
  'template.intro.seal': 'मुहर खोलने के लिए टैप करें',
  'template.intro.scratch': 'खुरचकर देखें',
  'template.intro.reveal': 'देखें',
  'template.music.play': 'संगीत चलाएँ',
  'template.music.pause': 'संगीत रोकें',
  'template.menu.title': 'भोज सूची',

  'event.linkExpired.title': 'यह लिंक समाप्त हो गया है',
  'event.linkExpired.body': 'नए निमंत्रण लिंक के लिए अपने मेज़बान से संपर्क करें।',
  'event.linkInvalid.title': 'यह लिंक अब मान्य नहीं है',
  'event.linkInvalid.body': 'हो सकता है मेज़बान ने इसे बदल दिया हो। नया लिंक उनसे माँगें।',
  'share.whatsappMessage': '{eventTitle}\n\nआप सादर आमंत्रित हैं! निमंत्रण खोलें: {url}',
  'upload.album': 'ये तस्वीरें किस कार्यक्रम की हैं?',
  'gallery.all': 'सभी',
  'error.EVENT_LINK_EXPIRED': 'यह निमंत्रण लिंक समाप्त हो गया है। नए लिंक के लिए अपने मेज़बान से संपर्क करें।',
};
