import { L, palette as p, type Theme } from './theme';

const GANESH = '॥ श्री गणेशाय नमः ॥';

/** Birthday themes: children (girls, boys, first birthdays), teens, milestones and elders. */
export const BIRTHDAY_THEMES: Theme[] = [
  {
    key: 'unicorn',
    word: 'Unicorn',
    phrase: 'Pastel pinks and lilac, a unicorn, balloons and stars',
    occasion: 'birthday',
    style: 'Playful',
    tags: ['kids', 'girl', 'unicorn', 'pastel'],
    colors: ['Candy Pink', p('#c2417a', '#f2b33d', '#f9c6dc', '#fff7fb', '#ffffff', '#3a1430', '#86607a')],
    presets: [
      ['Lilac Dream', p('#7a4fb0', '#f2b33d', '#e2d4f6', '#faf7ff', '#ffffff', '#2a1a40', '#76688a')],
      ['Mint & Peach', p('#2a9d8f', '#f4a261', '#ffd6c0', '#f4fbf9', '#ffffff', '#123a35', '#5e7a76')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'script',
      hero: { name: 'unicorn', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'secondary' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'accent' },
      card: 'header',
    },
    layouts: [
      L('party', 'Party', undefined, 'FREE', true),
      L('dream', 'Dreams'),
      L('couple', 'Magic'),
      L('arch', 'Rainbow'),
      L('floral', 'Meadow', { corner: { name: 'roseCluster', tint: '#7d9a7f' } }),
      L('photo', 'Sparkle'),
      L('minimal', 'Wishes'),
    ],
  },
  {
    key: 'dino',
    word: 'Dino',
    phrase: 'A friendly dinosaur in jungle greens and sunny orange',
    occasion: 'birthday',
    style: 'Playful',
    tags: ['kids', 'boy', 'dinosaur', 'jungle'],
    colors: ['Jungle', p('#2e7d32', '#f9a825', '#c5e1a5', '#f6fbef', '#ffffff', '#16301a', '#5e735f')],
    presets: [
      ['Volcano', p('#d84315', '#fbc02d', '#ffccbc', '#fff8f2', '#ffffff', '#3a160a', '#82624f')],
      ['Lagoon', p('#00838f', '#fbc02d', '#b2ebf2', '#f2fbfc', '#ffffff', '#0c2f33', '#5a7679')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'dino', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      sky: { name: 'confetti', tint: 'accent' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'header',
    },
    layouts: [L('party', 'Party', undefined, 'FREE', true), L('couple', 'Roar'), L('arch', 'Explorer'), L('photo', 'Safari'), L('split', 'Stomp'), L('dream', 'Dreams')],
  },
  {
    key: 'galaxy',
    word: 'Galaxy',
    phrase: 'Deep space blues, a rocket and a sky full of stars',
    occasion: 'birthday',
    style: 'Playful',
    tags: ['kids', 'boy', 'space', 'rocket'],
    colors: ['Outer Space', p('#283593', '#ffb300', '#b3c7ff', '#f3f5ff', '#ffffff', '#101540', '#5e6690')],
    presets: [
      ['Nebula', p('#6a1b9a', '#ffb300', '#e1bee7', '#fbf6fd', '#ffffff', '#2a0a3a', '#7a6286')],
      ['Teal Orbit', p('#00695c', '#ffb300', '#b2dfdb', '#f2faf9', '#ffffff', '#0b2a26', '#5a7672')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'fireflies',
    intro: 'celestial',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.25,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'rocket', tint: 'accent' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'accent' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [L('dream', 'Orbit'), L('party', 'Launch'), L('couple', 'Blastoff'), L('arch', 'Stardust'), L('photo', 'Voyage'), L('split', 'Rocket')],
  },
  {
    key: 'teddy',
    word: 'Teddy',
    phrase: 'Soft caramel and cream, a teddy bear and a sleepy moon',
    occasion: 'birthday',
    style: 'Cute',
    tags: ['kids', 'first-birthday', 'baby', 'teddy'],
    colors: ['Caramel', p('#8d5a3b', '#e0a458', '#f3dcc6', '#fdf8f3', '#ffffff', '#2e1d12', '#806a5c')],
    presets: [
      ['Baby Blue', p('#3d6ea8', '#e0a458', '#d6e6f7', '#f6f9fd', '#ffffff', '#16263a', '#5f7088')],
      ['Blush', p('#b4587a', '#e0a458', '#f8d6e2', '#fff7fa', '#ffffff', '#3a1626', '#86667a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'script',
      hero: { name: 'teddyBear', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'secondary' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [
      L('dream', 'Hugs', undefined, 'FREE', true),
      L('party', 'Picnic'),
      L('couple', 'Cuddles'),
      L('arch', 'Bear'),
      L('photo', 'Snuggle'),
      L('floral', 'Garden', { corner: { name: 'roseCluster', tint: '#8aa58c' } }),
      L('minimal', 'One'),
    ],
  },
  {
    key: 'cupcake',
    word: 'Cupcake',
    phrase: 'Strawberry pinks and buttercream, a cupcake with a candle',
    occasion: 'birthday',
    style: 'Sweet',
    tags: ['kids', 'girl', 'sweet', 'cupcake'],
    colors: ['Strawberry', p('#d6336c', '#f59f00', '#ffc9de', '#fff5f8', '#ffffff', '#3a1022', '#886070')],
    presets: [
      ['Mint Choc', p('#2b8a6e', '#a0522d', '#c3f0e0', '#f3fcf8', '#ffffff', '#0f2e25', '#5a786e')],
      ['Blueberry', p('#4c51bf', '#f59f00', '#d6d8fb', '#f7f7ff', '#ffffff', '#181a40', '#62648a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'cupcake', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      float: { name: 'moonCloud' },
      sky: { name: 'confetti', tint: 'accent' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'header',
    },
    layouts: [L('party', 'Party'), L('couple', 'Sprinkles'), L('arch', 'Frosting'), L('photo', 'Treat'), L('minimal', 'Sweet'), L('dream', 'Candy')],
  },
  {
    key: 'fiesta',
    word: 'Fiesta',
    phrase: 'Bright party colours with bunting, balloons and the birthday child',
    occasion: 'birthday',
    style: 'Playful',
    tags: ['kids', 'party', 'colourful'],
    colors: ['Rainbow', p('#e63946', '#ffb703', '#219ebc', '#fffaf0', '#ffffff', '#1d1b3a', '#6b6880')],
    presets: [
      ['Tropical', p('#06a77d', '#f9c80e', '#ff6b6b', '#f4fbf8', '#ffffff', '#0d2b24', '#5b746c')],
      ['Grape Soda', p('#7b2cbf', '#ffb703', '#ff6fb5', '#fbf7ff', '#ffffff', '#24103a', '#71658a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'kidGirl', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      sky: { name: 'confetti', tint: 'accent' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'header',
    },
    layouts: [
      L('party', 'Princess', undefined, 'FREE', true),
      L('party', 'Champ', { hero: { name: 'kidBoy', tint: 'accent' } }, 'FREE', true),
      L('party', 'Cake', { hero: { name: 'cake' } }),
      L('couple', 'Hooray'),
      L('couple', 'Buddy', { hero: { name: 'kidBoy', tint: 'accent' } }),
      L('arch', 'Balloons', { hero: { name: 'balloonBunch' } }),
      L('photo', 'Snapshot'),
    ],
  },
  {
    key: 'gudiya',
    word: 'Gudiya',
    phrase: 'A desi birthday in rani pink and marigold, the little girl in her lehenga',
    occasion: 'birthday',
    style: 'Festive',
    tags: ['kids', 'girl', 'indian', 'festive'],
    colors: ['Rani & Marigold', p('#c2185b', '#f5a623', '#ffd3a8', '#fff6f2', '#ffffff', '#3a0f22', '#86606e')],
    presets: [
      ['Parrot Green', p('#2e7d32', '#f5a623', '#ffd3a8', '#f6fbf2', '#ffffff', '#132b15', '#5e735f')],
      ['Peacock', p('#00838f', '#f5a623', '#ffd3a8', '#f2fbfc', '#ffffff', '#0c2f33', '#5a7679')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'kidGirl', tint: 'primary' },
      pair: { name: 'lantern', tint: 'secondary' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [L('couple', 'Pari', undefined, 'STANDARD', true), L('split', 'Rangoli'), L('home', 'Utsav'), L('party', 'Masti'), L('arch', 'Rani'), L('photo', 'Muskaan')],
  },
  {
    key: 'raja',
    word: 'Raja',
    phrase: 'A royal birthday in palace blue and gold, elephants at the window',
    occasion: 'birthday',
    style: 'Royal',
    tags: ['kids', 'boy', 'indian', 'royal'],
    colors: ['Palace Blue', p('#1f3a8a', '#d4a017', '#ffd99a', '#f6f7fc', '#ffffff', '#101b45', '#5e6688')],
    presets: [
      ['Emerald', p('#0f5a3e', '#d4a017', '#f1e5bf', '#f4faf6', '#ffffff', '#0b2619', '#5b7064')],
      ['Saffron', p('#b34700', '#d4a017', '#ffd27a', '#fff8ec', '#ffffff', '#2e1a0a', '#7a6248')],
    ],
    fonts: 'grand',
    look: 'royal',
    effect: 'goldDust',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.4,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'kidBoy', tint: 'accent' },
      pair: { name: 'elephant', tint: 'accent' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'palace',
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('jharokha', 'Beta', undefined, 'PREMIUM', true), L('couple', 'Shahzada'), L('party', 'Darbar', { pair: { name: 'balloonBunch' } }), L('arch', 'Mahal'), L('photo', 'Shaan'), L('split', 'Sawari')],
  },
  {
    key: 'nanha',
    word: 'Nanha',
    phrase: 'A first birthday in soft saffron and cream, with diyas, a cake and blessings',
    occasion: 'birthday',
    style: 'Traditional',
    tags: ['kids', 'first-birthday', 'indian', 'baby'],
    colors: ['Saffron Cream', p('#b4581a', '#e0a51a', '#ffe0b8', '#fffaf2', '#ffffff', '#33190a', '#80664f')],
    presets: [
      ['Mint', p('#2a8a72', '#e0a51a', '#c8eee3', '#f3fbf8', '#ffffff', '#0f2e26', '#5a786f')],
      ['Baby Pink', p('#c0567e', '#e0a51a', '#f9d3e1', '#fff7fa', '#ffffff', '#3a1626', '#86667a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'marigold',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.35,
      foil: false,
      nameFont: 'heading',
      nameWeight: 700,
      hero: { name: 'cake' },
      pair: { name: 'balloonBunch' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      float: { name: 'moonCloud' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'garland',
    },
    layouts: [
      L('home', 'Aashirwad'),
      L('couple', 'Kadam', { hero: { name: 'teddyBear', tint: 'primary' } }),
      L('party', 'Mela'),
      L('dream', 'Chanda', { hero: { name: 'babyCradle', tint: 'primary' } }),
      L('arch', 'Taara', { hero: { name: 'teddyBear', tint: 'primary' } }),
      L('photo', 'Muskaan'),
    ],
  },
  {
    key: 'cheers',
    word: 'Cheers',
    phrase: 'Black, gold and champagne for a milestone birthday',
    occasion: 'birthday',
    style: 'Luxury',
    tags: ['adult', 'milestone', '30th', '40th', '50th', 'party'],
    colors: ['Black & Gold', p('#1c1814', '#d4af37', '#efe1b0', '#f7f4ec', '#fffdf6', '#0b0a08', '#6e6658')],
    presets: [
      ['Navy & Gold', p('#14213d', '#d4af37', '#efe2c0', '#f5f6f9', '#ffffff', '#0a1120', '#5b6680')],
      ['Emerald & Gold', p('#0f3d2e', '#d4af37', '#eadcae', '#f6f3e9', '#fffdf6', '#0c241a', '#5f6f66')],
    ],
    fonts: 'elegant',
    look: 'modern',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'champagne' },
      pair: { name: 'balloonBunch' },
      top: { name: 'fairyLights' },
      centre: { name: 'medallion', foil: true },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', foil: true },
      crest: { name: 'champagne' },
      sky: { name: 'confetti', tint: 'secondary' },
      card: 'minimal',
    },
    layouts: [L('minimal', 'Milestone', undefined, 'STANDARD', true), L('couple', 'Toast'), L('photo', 'Glam'), L('split', 'Fizz'), L('arch', 'Gold'), L('party', 'Bash')],
  },
  {
    key: 'glow',
    word: 'Glow',
    phrase: 'Neon pink and electric cyan on midnight, for teens and night owls',
    occasion: 'birthday',
    style: 'Modern',
    tags: ['teen', 'adult', 'neon', 'party'],
    colors: ['Neon', p('#1a1033', '#ff2e93', '#2de2e6', '#f5f3ff', '#ffffff', '#0c0820', '#6c6488')],
    presets: [
      ['Laser Lime', p('#0f1a14', '#c6ff00', '#00e5ff', '#f4fff0', '#ffffff', '#060d09', '#5f6e66')],
      ['Sunset Synth', p('#2a0d3a', '#ff7a18', '#ff4ecd', '#fff4fb', '#ffffff', '#14051d', '#75607e')],
    ],
    fonts: 'modern',
    look: 'modern',
    effect: 'confetti',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.25,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'cake' },
      pair: { name: 'balloonBunch' },
      top: { name: 'fairyLights' },
      centre: { name: 'geometric', tint: 'secondary' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      sky: { name: 'confetti', tint: 'accent' },
      card: 'header',
    },
    layouts: [L('couple', 'Vibes'), L('split', 'Beat', { hero: { name: 'cupcake', tint: 'secondary' } }), L('photo', 'Selfie'), L('minimal', 'Mode'), L('arch', 'Lights')],
  },
  {
    key: 'blossom',
    word: 'Blossom',
    phrase: 'Peony pinks and sage, elegant enough for a fortieth or a sixtieth',
    occasion: 'birthday',
    style: 'Floral',
    tags: ['adult', 'milestone', 'floral', 'elegant'],
    colors: ['Peony', p('#b0466a', '#c9a165', '#f8d7e2', '#fff8f9', '#ffffff', '#38141f', '#88666f')],
    presets: [
      ['Sage', p('#4b6b4f', '#b0915c', '#dbe6d2', '#f7f8f2', '#ffffff', '#202b22', '#66736a')],
      ['Lavender', p('#6b4f8a', '#b0915c', '#e6dcf3', '#faf8fd', '#ffffff', '#24183a', '#706885')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.5,
      foil: true,
      nameFont: 'script',
      hero: { name: 'cake' },
      corner: { name: 'roseCluster', tint: '#7d9a7f' },
      top: { name: 'floralGarland', tint: '#7d9a7f' },
      centre: { name: 'mandala', tint: 'accent' },
      scene: 'floral',
      motif: { name: 'flourish' },
      crest: { name: 'roseCluster', tint: '#7d9a7f' },
      card: 'garland',
    },
    layouts: [L('floral', 'Bloom'), L('minimal', 'Petal'), L('photo', 'Grace'), L('arch', 'Rose'), L('couple', 'Bouquet'), L('split', 'Bliss')],
  },
  {
    key: 'amrit',
    word: 'Amrit',
    phrase: 'A sixtieth or seventy-fifth in maroon and gold, with diyas, the kalash and blessings',
    occasion: 'birthday',
    style: 'Traditional',
    tags: ['adult', 'milestone', '60th', '75th', 'indian', 'traditional'],
    colors: ['Maroon & Gold', p('#6a1526', '#cfa046', '#f4dcae', '#fbf5ec', '#fffaf3', '#2b1712', '#7a5d52')],
    presets: [
      ['Temple Green', p('#1f4d2c', '#c9a227', '#e2dcae', '#f5f6ec', '#ffffff', '#16261a', '#5f6e60')],
      ['Saffron', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'kalash' },
      pair: { name: 'elephant', tint: 'accent' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus', foil: true },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [
      L('home', 'Mahotsav', undefined, 'STANDARD', true),
      L('couple', 'Shashti', { hero: { name: 'coupleElder', tint: 'accent' } }),
      L('jharokha', 'Ashirwad'),
      L('arch', 'Deep'),
      L('photo', 'Smriti'),
      L('minimal', 'Varsh'),
    ],
  },
  {
    key: 'tara',
    word: 'Tara',
    phrase: 'Navy and gold stars, a sleepy moon and soft clouds',
    occasion: 'birthday',
    style: 'Dreamy',
    tags: ['kids', 'stars', 'moon', 'dreamy'],
    colors: ['Starry Navy', p('#22306b', '#e9b949', '#cfd9ff', '#f5f7ff', '#ffffff', '#111a40', '#5e6690')],
    presets: [
      ['Dusk Pink', p('#9c3f74', '#e9b949', '#f6d3e6', '#fff7fb', '#ffffff', '#3a1430', '#86607a')],
      ['Sea Green', p('#1f6f6a', '#e9b949', '#c6ecea', '#f3fbfa', '#ffffff', '#0e2e2c', '#5a7674')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'fireflies',
    intro: 'celestial',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'script',
      hero: { name: 'kidGirl', tint: 'primary' },
      pair: { name: 'balloonBunch' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'secondary' },
      motif: { name: 'flourish', tint: 'secondary' },
      crest: { name: 'moonCloud' },
      card: 'sky',
    },
    layouts: [
      L('dream', 'Moon'),
      L('dream', 'Sky', { hero: { name: 'kidBoy', tint: 'primary' }, float: { name: 'rocket', tint: 'primary' } }),
      L('couple', 'Wish'),
      L('couple', 'Dreamer', { hero: { name: 'kidBoy', tint: 'primary' } }),
      L('arch', 'Glow'),
      L('photo', 'Shine'),
    ],
  },
  {
    key: 'rangeela',
    word: 'Rangeela',
    phrase: 'Every colour of a mela: bunting, balloons and a big cake',
    occasion: 'birthday',
    style: 'Festive',
    tags: ['kids', 'indian', 'colourful', 'party'],
    colors: ['Mela', p('#d1365f', '#f7b32b', '#2bb3a3', '#fffaf0', '#ffffff', '#2a1020', '#7d6070')],
    presets: [
      ['Mango & Teal', p('#e07a1f', '#f7c548', '#1f8a8a', '#fff9ef', '#ffffff', '#33190a', '#80664f')],
      ['Parrot & Pink', p('#3d9a3d', '#f7b32b', '#ff6fa3', '#f6fbf2', '#ffffff', '#132b15', '#5e735f')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.35,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'cake' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      skyline: { name: 'giftBox' },
      sky: { name: 'confetti', tint: 'accent' },
      motif: { name: 'flourish' },
      card: 'header',
    },
    layouts: [
      L('party', 'Dhamaal'),
      L('couple', 'Chhotu', { hero: { name: 'kidBoy', tint: 'primary' } }),
      L('couple', 'Chutki', { hero: { name: 'kidGirl', tint: 'primary' } }),
      L('split', 'Jhoola', { hero: { name: 'kidGirl', tint: 'primary' } }),
      L('photo', 'Masti'),
      L('arch', 'Toli', { hero: { name: 'kidBoy', tint: 'primary' } }),
    ],
  },
  {
    key: 'surprise',
    word: 'Surprise',
    phrase: 'Wrapped in ribbons: a tower of presents, confetti and balloons',
    occasion: 'birthday',
    style: 'Playful',
    tags: ['party', 'gifts', 'any-age'],
    colors: ['Ribbon Red', p('#c62f3d', '#f2b134', '#ffd7d7', '#fff7f5', '#ffffff', '#3a0f14', '#86626a')],
    presets: [
      ['Teal Gift', p('#0f766e', '#f2b134', '#c8f0ea', '#f3fbf9', '#ffffff', '#0d2b27', '#5a7672')],
      ['Purple Bow', p('#6d28d9', '#f2b134', '#e7dcff', '#faf7ff', '#ffffff', '#24103a', '#71658a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'heading',
      nameWeight: 800,
      hero: { name: 'giftBox' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      sky: { name: 'confetti', tint: 'accent' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'header',
    },
    layouts: [L('party', 'Gifts'), L('couple', 'Unwrap'), L('minimal', 'Bow'), L('photo', 'Pop')],
  },
];
