import { L, palette as p, type Theme } from './theme';

const GANESH = '॥ श्री गणेशाय नमः ॥';

/** Engagement, haldi, mehendi, sangeet, reception and anniversary themes. */
export const CELEBRATION_THEMES: Theme[] = [
  // ─────────────────────────── Engagement ───────────────────────────
  {
    key: 'mudrika',
    word: 'Mudrika',
    phrase: 'Rose quartz and gold, with garden roses and a pair of rings',
    occasion: 'engagement',
    style: 'Romantic',
    tags: ['engagement', 'ring-ceremony', 'floral', 'modern'],
    colors: ['Rose Quartz', p('#a3445e', '#c8a165', '#f7d6dc', '#fff8f6', '#ffffff', '#35161f', '#8a6670')],
    presets: [
      ['Champagne', p('#7a5a3a', '#c9a96a', '#efe1cc', '#fbf8f2', '#ffffff', '#2c2216', '#7d6e5a')],
      ['Navy & Rose', p('#24345e', '#c9a165', '#f3d3d9', '#f7f7fb', '#ffffff', '#141c33', '#5f6a80')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.5,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      corner: { name: 'roseCluster', tint: '#7d9a7f' },
      top: { name: 'floralGarland', tint: '#7d9a7f' },
      scene: 'floral',
      motif: { name: 'rings', tint: 'secondary' },
      card: 'garland',
    },
    layouts: [L('floral', 'Gulab', undefined, 'STANDARD', true), L('couple', 'Ishq'), L('minimal', 'Vachan'), L('photo', 'Pal'), L('arch', 'Kamaan'), L('split', 'Ada'), L('mandap', 'Kunj')],
  },
  {
    key: 'sagai',
    word: 'Sagai',
    phrase: 'A traditional sagai in maroon and gold, with a marigold toran and kalash',
    occasion: 'engagement',
    style: 'Traditional',
    tags: ['hindu', 'engagement', 'roka', 'traditional'],
    colors: ['Maroon & Gold', p('#6b1426', '#c9973f', '#f3d9a4', '#fbf4ea', '#fffaf2', '#2b1712', '#7a5d52')],
    presets: [
      ['Emerald', p('#14503a', '#c9a24a', '#eadcae', '#f6f3e9', '#fffdf6', '#0c241a', '#5f6f66')],
      ['Saffron', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'toran',
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [
      L('couple', 'Shagun', undefined, 'STANDARD', true),
      L('jharokha', 'Haveli', { pair: { name: 'elephant', tint: 'accent' } }),
      L('mandap', 'Dwar'),
      L('arch', 'Tilak'),
      L('home', 'Roka', { hero: { name: 'coupleHindu', tint: 'accent' } }),
      L('photo', 'Rasm'),
      L('minimal', 'Moti'),
    ],
  },
  {
    key: 'solitaire',
    word: 'Solitaire',
    phrase: 'Navy, blush and champagne, modern and bright',
    occasion: 'engagement',
    style: 'Modern',
    tags: ['engagement', 'modern', 'christian', 'ring-ceremony'],
    colors: ['Navy & Blush', p('#1f3355', '#c2a46a', '#f2d4d9', '#f8f8fb', '#ffffff', '#141c2e', '#5f6a80')],
    presets: [
      ['Emerald & Gold', p('#14503a', '#c2a46a', '#dfe9df', '#f7f8f3', '#ffffff', '#0c241a', '#5f6f66')],
      ['Black & Gold', p('#1c1814', '#d4af37', '#efe1b0', '#f7f4ec', '#fffdf6', '#0b0a08', '#6e6658')],
    ],
    fonts: 'elegant',
    look: 'modern',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleChristian', tint: 'accent' },
      pair: { name: 'champagne' },
      centre: { name: 'medallion', foil: true },
      corner: { name: 'filigreeCorner', foil: true },
      motif: { name: 'rings', tint: 'secondary' },
      card: 'minimal',
    },
    layouts: [
      L('minimal', 'Vow'),
      L('couple', 'Forever'),
      L('photo', 'Moment'),
      L('split', 'Cheers', { hero: { name: 'champagne' } }),
      L('floral', 'Bouquet', { corner: { name: 'roseCluster', tint: '#7f9a83' } }),
      L('arch', 'Sparkle'),
    ],
  },
  {
    key: 'roka',
    word: 'Roka',
    phrase: 'A Punjabi roka in phulkari pinks, with the dhol',
    occasion: 'engagement',
    style: 'Festive',
    tags: ['sikh', 'punjabi', 'engagement', 'roka', 'festive'],
    colors: ['Phulkari', p('#b0195a', '#e0a03a', '#f6c66b', '#fff6ef', '#ffffff', '#30101e', '#866068')],
    presets: [
      ['Mustard & Green', p('#2f6b3f', '#e0a03a', '#ffcf6b', '#f8f8ec', '#ffffff', '#1a2a1d', '#62705f')],
      ['Royal Blue', p('#20307a', '#e0a03a', '#f6c66b', '#f5f6fb', '#ffffff', '#141a3a', '#5e6585')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleSikh', tint: 'primary' },
      pair: { name: 'dhol' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [L('couple', 'Chunni'), L('split', 'Dhol', { hero: { name: 'dhol' } }), L('arch', 'Kurmai'), L('photo', 'Rasm'), L('minimal', 'Kesri')],
  },
  {
    key: 'mangni',
    word: 'Mangni',
    phrase: 'A Rajasthani mangni in turquoise and coral, painted elephants at the gate',
    occasion: 'engagement',
    style: 'Royal',
    tags: ['hindu', 'rajasthani', 'gujarati', 'engagement'],
    colors: ['Turquoise & Coral', p('#0f5c63', '#d9a441', '#f4a48a', '#fbf6ef', '#ffffff', '#0e2a2c', '#5f7372')],
    presets: [
      ['Pink City', p('#a01d5a', '#c9973f', '#f7c9da', '#fff5f8', '#ffffff', '#2e0f1e', '#86606f')],
      ['Indigo & Gold', p('#24357a', '#d9a441', '#ffd8a0', '#f5f6fb', '#ffffff', '#141c3a', '#5f6685')],
    ],
    fonts: 'grand',
    look: 'royal',
    effect: 'petals',
    intro: 'doors',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'elephant', tint: 'accent' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'palace',
      motif: { name: 'flourish', foil: true },
      card: 'framed',
    },
    layouts: [L('jharokha', 'Gokh'), L('couple', 'Bandhan'), L('arch', 'Toran'), L('portrait', 'Jodi'), L('photo', 'Pal'), L('minimal', 'Sutra')],
  },
  {
    key: 'nischayam',
    word: 'Nischayam',
    phrase: 'A South Indian nischayathartham in silk green and temple gold',
    occasion: 'engagement',
    style: 'Temple',
    tags: ['hindu', 'south-indian', 'tamil', 'telugu', 'engagement'],
    colors: ['Mayil Green', p('#0f4d3a', '#d4a017', '#f1e5bf', '#f8f6ec', '#ffffff', '#11241c', '#5e6f64')],
    presets: [
      ['Arakku Red', p('#7d1515', '#d4a017', '#f6e7c1', '#fff8ec', '#ffffff', '#2e120c', '#7a5a4a')],
      ['Mango Yellow', p('#9a5b00', '#d4a017', '#ffe1a0', '#fff9ec', '#ffffff', '#2e1d04', '#7b6446')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'linen',
      strength: 0.45,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'coupleSouth', tint: 'accent' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'accent' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'gopuram',
      motif: { name: 'lotus', foil: true },
      card: 'banded',
    },
    layouts: [L('temple', 'Mangalam'), L('couple', 'Thamboolam'), L('arch', 'Kolam'), L('photo', 'Malar'), L('minimal', 'Kumkum', { dark: false, foil: false })],
  },

  // ─────────────────────────── Haldi ───────────────────────────
  {
    key: 'peeli',
    word: 'Peeli',
    phrase: 'Sunny haldi yellow with marigolds and an urli of turmeric',
    occasion: 'haldi',
    style: 'Festive',
    tags: ['haldi', 'hindu', 'marigold', 'festive'],
    colors: ['Haldi Yellow', p('#9a5b00', '#e8a317', '#ffe08a', '#fffbea', '#ffffff', '#2e1d04', '#7b6446')],
    presets: [
      ['Marigold & Green', p('#2f6b3f', '#e6a325', '#ffcf6b', '#f8f8ec', '#ffffff', '#1a2a1d', '#62705f')],
      ['Sunset Orange', p('#b4471a', '#e8a317', '#ffd2a0', '#fff7ef', '#ffffff', '#33170a', '#80624d')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'haldiBowl' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [
      L('home', 'Urli', undefined, 'STANDARD', true),
      L('couple', 'Ubtan', { hero: { name: 'coupleHindu', tint: 'secondary' } }),
      L('split', 'Genda'),
      L('arch', 'Kesar'),
      L('photo', 'Rang'),
      L('minimal', 'Chandan'),
      L('floral', 'Phool'),
    ],
  },
  {
    key: 'manjal',
    word: 'Manjal',
    phrase: 'A South Indian mangala snanam in turmeric and leaf green, jasmine and kolam',
    occasion: 'haldi',
    style: 'Temple',
    tags: ['haldi', 'south-indian', 'tamil', 'temple'],
    colors: ['Manjal', p('#1f5a2c', '#e0a51a', '#ffe08a', '#fbfaee', '#ffffff', '#12261a', '#5f6f60')],
    presets: [
      ['Turmeric & Red', p('#8a1c14', '#e0a51a', '#ffe08a', '#fff8ec', '#ffffff', '#2c120e', '#7b5f52')],
      ['Sandal', p('#7a4a1a', '#e0a51a', '#f6dcae', '#fbf6ec', '#ffffff', '#2c1a0a', '#7b6550')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'linen',
      strength: 0.45,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'haldiBowl' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'accent' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'gopuram',
      motif: { name: 'lotus', foil: true },
      card: 'banded',
    },
    layouts: [L('temple', 'Snanam'), L('home', 'Kolam', { dark: false, foil: false, top: { name: 'toran' } }), L('couple', 'Neerattu', { hero: { name: 'coupleSouth', tint: 'secondary' } }), L('photo', 'Malli')],
  },

  // ─────────────────────────── Mehendi ───────────────────────────
  {
    key: 'heena',
    word: 'Heena',
    phrase: 'Henna green and marigold, a hand painted with mehendi',
    occasion: 'mehendi',
    style: 'Festive',
    tags: ['mehendi', 'hindu', 'muslim', 'festive'],
    colors: ['Henna Green', p('#3d5a1e', '#d9a03a', '#f2c46b', '#fbf8ec', '#ffffff', '#1d2a0e', '#66704f')],
    presets: [
      ['Rani Pink', p('#a3195b', '#e0a03a', '#f6c66b', '#fff6ef', '#ffffff', '#2e1220', '#7d5a68')],
      ['Teal & Mustard', p('#0f5c63', '#d9a03a', '#ffd166', '#f5faf8', '#ffffff', '#0e2a2c', '#5f7372')],
    ],
    fonts: 'romantic',
    look: 'celebration',
    effect: 'petals',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.5,
      foil: false,
      nameFont: 'script',
      hero: { name: 'mehendiHand', tint: '#8a3a17' },
      pair: { name: 'lantern', tint: 'secondary' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [
      L('split', 'Haath', undefined, 'STANDARD', true),
      L('arch', 'Bel'),
      L('couple', 'Dulhan', { hero: { name: 'brideBust', tint: 'primary' } }),
      L('floral', 'Patti'),
      L('photo', 'Rang'),
      L('minimal', 'Bootah'),
      L('home', 'Aangan'),
    ],
  },
  {
    key: 'mehfil',
    word: 'Mehfil',
    phrase: 'A mehendi night of lanterns, paisleys and song',
    occasion: 'mehendi',
    style: 'Night',
    tags: ['mehendi', 'night', 'muslim', 'hindu'],
    colors: ['Plum Night', p('#3d1640', '#d1a54a', '#f0c9a0', '#f9f4f8', '#ffffff', '#1e0a20', '#6f5f72')],
    presets: [
      ['Emerald Night', p('#0b3d2e', '#c9a227', '#f1e3b0', '#f7f4ea', '#fffdf5', '#0e1f18', '#5b6f65')],
      ['Midnight Blue', p('#13285c', '#cfa63a', '#efe0b2', '#f4f5f9', '#ffffff', '#0c1430', '#5a6383')],
    ],
    fonts: 'elegant',
    look: 'royal',
    effect: 'lanterns',
    intro: 'lanterns',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'mehendiHand', tint: '#8a3a17' },
      hang: { name: 'lantern' },
      centre: { name: 'arabesque', tint: 'primary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('night', 'Raat', { hero: undefined }), L('split', 'Rachna'), L('arch', 'Mehrab'), L('photo', 'Shaam'), L('minimal', 'Noor')],
  },

  // ─────────────────────────── Sangeet ───────────────────────────
  {
    key: 'dholki',
    word: 'Dholki',
    phrase: 'A dholki night in magenta, saffron and gold, the dhol at the centre',
    occasion: 'sangeet',
    style: 'Festive',
    tags: ['sangeet', 'punjabi', 'festive', 'music'],
    colors: ['Magenta & Saffron', p('#a3195b', '#f0a92b', '#ffd27a', '#fff6f0', '#ffffff', '#2e1220', '#7d5a68')],
    presets: [
      ['Electric Blue', p('#1f3fae', '#f0a92b', '#ffd27a', '#f4f6fd', '#ffffff', '#101b45', '#5e6688')],
      ['Emerald & Gold', p('#0f5a3e', '#f0a92b', '#ffd27a', '#f4faf6', '#ffffff', '#0b2619', '#5b7064')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'confetti',
    intro: 'curtain',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'dhol' },
      pair: { name: 'lantern', tint: 'secondary' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      sky: { name: 'confetti', tint: 'accent' },
      card: 'header',
    },
    layouts: [
      L('split', 'Thaap', undefined, 'STANDARD', true),
      L('couple', 'Nach', { hero: { name: 'coupleHindu', tint: 'primary' } }),
      L('party', 'Baaja'),
      L('arch', 'Taal'),
      L('photo', 'Geet'),
      L('minimal', 'Sur'),
    ],
  },
  {
    key: 'ghungroo',
    word: 'Ghungroo',
    phrase: 'A sangeet under the stars in midnight blue and gold, lanterns swaying',
    occasion: 'sangeet',
    style: 'Night',
    tags: ['sangeet', 'night', 'music', 'royal'],
    colors: ['Midnight & Gold', p('#14213d', '#d1a54a', '#efe2c0', '#f5f6f9', '#ffffff', '#0a1120', '#5b6680')],
    presets: [
      ['Wine & Gold', p('#4b0f24', '#d1a54a', '#f0d6a8', '#fbf4ef', '#ffffff', '#24060f', '#7b5d62')],
      ['Peacock', p('#0d4f4c', '#d1a54a', '#e2e0b0', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
    ],
    fonts: 'grand',
    look: 'royal',
    effect: 'lanterns',
    intro: 'lanterns',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('night', 'Mehfil', { hero: undefined }, 'PREMIUM', true), L('couple', 'Jhankar'), L('split', 'Thumka', { hero: { name: 'dhol' } }), L('arch', 'Raag'), L('photo', 'Taal'), L('minimal', 'Sur')],
  },

  // ─────────────────────────── Reception ───────────────────────────
  {
    key: 'swagat',
    word: 'Swagat',
    phrase: 'An evening reception in wine and champagne gold',
    occasion: 'reception',
    style: 'Elegant',
    tags: ['reception', 'modern', 'evening'],
    colors: ['Wine & Champagne', p('#5a1230', '#c9a96a', '#f0dcc6', '#faf5f2', '#ffffff', '#2a0a18', '#7a5d68')],
    presets: [
      ['Navy & Gold', p('#1b2a4a', '#c9a96a', '#e3e8f0', '#f4f6fa', '#ffffff', '#0d1526', '#5e6a80')],
      ['Emerald & Gold', p('#0f4a35', '#c9a96a', '#e2e6d2', '#f6f3e9', '#fffdf6', '#0c241a', '#5f6f66')],
    ],
    fonts: 'elegant',
    look: 'modern',
    effect: 'goldDust',
    intro: 'curtain',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      pair: { name: 'champagne' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      crest: { name: 'champagne' },
      sky: { name: 'stars', tint: 'accent' },
      card: 'minimal',
    },
    layouts: [
      L('night', 'Shaam', { hero: { name: 'champagne' } }, 'PREMIUM', true),
      L('couple', 'Jashn'),
      L('minimal', 'Toast', { hero: { name: 'champagne' } }),
      L('photo', 'Pal'),
      L('split', 'Cheers', { hero: { name: 'champagne' } }),
      L('floral', 'Gulposh', { corner: { name: 'roseCluster', tint: '#6b8f6e' } }),
    ],
  },
  {
    key: 'velvet',
    word: 'Velvet',
    phrase: 'Black velvet and gold foil for a grand reception',
    occasion: 'reception',
    style: 'Luxury',
    tags: ['reception', 'luxury', 'black', 'gold'],
    colors: ['Black & Gold', p('#1c1814', '#d4af37', '#efe1b0', '#f7f4ec', '#fffdf6', '#0b0a08', '#6e6658')],
    presets: [
      ['Midnight Blue', p('#14213d', '#d4af37', '#efe2c0', '#f5f6f9', '#ffffff', '#0a1120', '#5b6680')],
      ['Emerald', p('#0f3d2e', '#d4af37', '#eadcae', '#f6f3e9', '#fffdf6', '#0c241a', '#5f6f66')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'secondary' },
      pair: { name: 'doves', tint: 'secondary' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion', foil: true },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'secondary' },
      card: 'framed',
    },
    layouts: [L('night', 'Gala', { hero: undefined }), L('couple', 'Soiree'), L('arch', 'Mehrab'), L('minimal', 'Noir', { hero: { name: 'champagne' } }), L('photo', 'Glow'), L('jharokha', 'Mahal')],
  },

  // ─────────────────────────── Anniversary ───────────────────────────
  {
    key: 'swarna',
    word: 'Swarna',
    phrase: 'A golden anniversary in ivory and gold, for a couple who have shared a lifetime',
    occasion: 'anniversary',
    style: 'Elegant',
    tags: ['anniversary', 'golden', '50th', 'classic'],
    colors: ['Ivory & Gold', p('#6b5338', '#c9a24a', '#efe3c8', '#faf6ee', '#fffdf8', '#2a2016', '#7a6e5c')],
    presets: [
      ['Maroon & Gold', p('#6b1426', '#c9a24a', '#f3d9a4', '#fbf4ea', '#fffaf2', '#2b1712', '#7a5d52')],
      ['Emerald & Gold', p('#1f5a42', '#c9a24a', '#e2e6d2', '#f8f8f2', '#ffffff', '#122a20', '#62705f')],
    ],
    fonts: 'classic',
    look: 'classic',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.5,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleElder', tint: 'primary' },
      pair: { name: 'doves', tint: 'secondary' },
      top: { name: 'floralGarland', tint: '#7f9a83' },
      corner: { name: 'filigreeCorner', foil: true },
      centre: { name: 'medallion' },
      motif: { name: 'rings', tint: 'secondary' },
      card: 'framed',
    },
    layouts: [
      L('couple', 'Varsh', undefined, 'STANDARD', true),
      L('arch', 'Saath'),
      L('floral', 'Bagiya', { corner: { name: 'roseCluster', tint: '#7f9a83' } }),
      L('minimal', 'Sutra'),
      L('photo', 'Yaadein'),
      L('jharokha', 'Jodi'),
    ],
  },
  {
    key: 'rajat',
    word: 'Rajat',
    phrase: 'A silver jubilee in pearl grey and silver foil',
    occasion: 'anniversary',
    style: 'Elegant',
    tags: ['anniversary', 'silver', '25th', 'modern'],
    colors: ['Pearl & Silver', p('#4a5568', '#a9b2c3', '#e3e8f0', '#f7f8fa', '#ffffff', '#1a202c', '#6b7280')],
    presets: [
      ['Silver & Blush', p('#7a4a5a', '#a9b2c3', '#f2d4d9', '#fbf7f8', '#ffffff', '#2c1a20', '#7a6a70')],
      ['Navy & Silver', p('#1f3355', '#a9b2c3', '#dbe2ea', '#f6f7f9', '#ffffff', '#141c2e', '#5f6a80')],
    ],
    fonts: 'elegant',
    look: 'modern',
    effect: 'goldDust',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'doves', tint: 'secondary' },
      corner: { name: 'roseCluster', tint: '#8a9a8f' },
      top: { name: 'floralGarland', tint: '#8a9a8f' },
      motif: { name: 'rings', tint: 'secondary' },
      card: 'minimal',
    },
    layouts: [L('couple', 'Jayanti'), L('minimal', 'Moti'), L('floral', 'Gulab'), L('photo', 'Lamhe'), L('arch', 'Kamaan')],
  },
  {
    key: 'manik',
    word: 'Manik',
    phrase: 'Ruby red and gold for forty years together',
    occasion: 'anniversary',
    style: 'Romantic',
    tags: ['anniversary', 'ruby', '40th', 'romantic'],
    colors: ['Ruby', p('#8a1538', '#c9973f', '#f6d0da', '#fff7f8', '#ffffff', '#2e0b16', '#7d5a63')],
    presets: [
      ['Wine Night', p('#4b0f24', '#d1a54a', '#f0d6a8', '#fbf4ef', '#ffffff', '#24060f', '#7b5d62')],
      ['Rose Gold', p('#9c4a5a', '#c08a6c', '#f6d6d6', '#fff8f6', '#ffffff', '#33161c', '#88666c')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleElder', tint: 'accent' },
      pair: { name: 'doves', tint: 'accent' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'roseCluster', tint: '#6b8f6e' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'rings', tint: 'secondary' },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('couple', 'Chalis'), L('night', 'Raat', { hero: undefined }), L('arch', 'Mehrab'), L('photo', 'Pal'), L('minimal', 'Moti')],
  },
  {
    key: 'humsafar',
    word: 'Humsafar',
    phrase: 'Terracotta, sage and cream, warm and modern for any anniversary',
    occasion: 'anniversary',
    style: 'Modern',
    tags: ['anniversary', 'modern', 'boho'],
    colors: ['Terracotta & Sage', p('#9a4a2a', '#b88a4a', '#dbe6d2', '#faf4ee', '#fffdf9', '#2e1a10', '#7a6658')],
    presets: [
      ['Olive', p('#5f6a32', '#b88a4a', '#e6e2c4', '#f7f7f0', '#ffffff', '#262a14', '#6c6e5a')],
      ['Dusty Blue', p('#3f5b7a', '#b39a6b', '#cfdcea', '#f5f7fa', '#ffffff', '#1f2a36', '#677585')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.55,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'doves', tint: 'secondary' },
      corner: { name: 'roseCluster', tint: '#7a8f6a' },
      top: { name: 'floralGarland', tint: '#7a8f6a' },
      motif: { name: 'doves', tint: 'secondary' },
      card: 'minimal',
    },
    layouts: [L('couple', 'Safar'), L('split', 'Raahein'), L('minimal', 'Saathi'), L('photo', 'Kahani'), L('floral', 'Mausam')],
  },
  {
    key: 'evergreen',
    word: 'Evergreen',
    phrase: 'Garden whites and greenery for a church anniversary or a vow renewal',
    occasion: 'anniversary',
    style: 'Floral',
    tags: ['anniversary', 'christian', 'vow-renewal', 'floral'],
    colors: ['Garden White', p('#3f5a4a', '#b49a62', '#e6eee6', '#fbfbf7', '#ffffff', '#1f2a24', '#6a766e')],
    presets: [
      ['Blush', p('#8c3b4a', '#a88a5a', '#f2c4cc', '#fbf7f2', '#ffffff', '#3a2a2c', '#857174')],
      ['Navy', p('#1f3355', '#b49a62', '#dbe2ea', '#f8f8fb', '#ffffff', '#141c2e', '#5f6a80')],
    ],
    fonts: 'classic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.55,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleChristian', tint: 'accent' },
      corner: { name: 'roseCluster', tint: '#6b8f6e' },
      top: { name: 'floralGarland', tint: '#6b8f6e' },
      motif: { name: 'doves', tint: 'secondary' },
      scene: 'floral',
      card: 'garland',
    },
    layouts: [L('floral', 'Garden'), L('couple', 'Renewal'), L('mandap', 'Arbour'), L('arch', 'Chapel'), L('minimal', 'Grace'), L('photo', 'Always')],
  },
  {
    key: 'vachan',
    word: 'Vachan',
    phrase: 'A traditional anniversary in kumkum red and gold, the couple garlanded again',
    occasion: 'anniversary',
    style: 'Traditional',
    tags: ['anniversary', 'hindu', 'traditional'],
    colors: ['Kumkum', p('#7a1020', '#d4a017', '#f6dfae', '#fff8ef', '#ffffff', '#2e080d', '#7b5d58')],
    presets: [
      ['Peacock', p('#0d4f4c', '#c9a24a', '#e2e0b0', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
      ['Saffron', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleVarmala', tint: 'accent' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'mandala', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'mandap',
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus', foil: true },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [L('couple', 'Saptapadi'), L('jharokha', 'Haveli'), L('mandap', 'Phere'), L('photo', 'Smriti')],
  },
];
