import { L, palette as p, type Theme } from './theme';

const GANESH = '॥ श्री गणेशाय नमः ॥';

/** Baby showers, naming ceremonies and mundans. */
export const FAMILY_THEMES: Theme[] = [
  // ─────────────────────────── Baby shower ───────────────────────────
  {
    key: 'godh',
    word: 'Godh',
    phrase: 'A godh bharai in rani pink and marigold, the mother-to-be in silk',
    occasion: 'babyShower',
    style: 'Traditional',
    tags: ['baby-shower', 'godh-bharai', 'hindu', 'indian'],
    colors: ['Rani & Marigold', p('#a8235e', '#dba23c', '#f8cf86', '#fff7f0', '#ffffff', '#2e1220', '#7d5a68')],
    presets: [
      ['Peacock', p('#0d5a5a', '#dba23c', '#f1e0a8', '#f2faf9', '#ffffff', '#0a2828', '#5a7473')],
      ['Saffron', p('#b34700', '#d4a017', '#ffd27a', '#fff8ec', '#ffffff', '#2e1a0a', '#7a6248')],
    ],
    fonts: 'romantic',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'momToBe', tint: 'primary' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [
      L('couple', 'Bharai', undefined, 'STANDARD', true),
      L('home', 'Mangal'),
      L('split', 'Mamta'),
      L('arch', 'Phool'),
      L('jharokha', 'Haveli', { pair: { name: 'royalPeacock', tint: 'accent' }, dark: true, foil: true }),
      L('photo', 'Intezaar'),
      L('minimal', 'Nanhi'),
    ],
  },
  {
    key: 'stork',
    word: 'Stork',
    phrase: 'Powder blue and blush, a stork carrying the little one over the clouds',
    occasion: 'babyShower',
    style: 'Dreamy',
    tags: ['baby-shower', 'pastel', 'modern', 'stork'],
    colors: ['Powder Blue', p('#3d6ea8', '#e8b04a', '#d6e6f7', '#f6f9fd', '#ffffff', '#16263a', '#5f7088')],
    presets: [
      ['Blush', p('#b4587a', '#e8b04a', '#f8d6e2', '#fff7fa', '#ffffff', '#3a1626', '#86667a')],
      ['Mint', p('#2a8a72', '#e8b04a', '#c8eee3', '#f3fbf8', '#ffffff', '#0f2e26', '#5a786f')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'babyCradle', tint: 'primary' },
      float: { name: 'stork' },
      pair: { name: 'balloonBunch' },
      sky: { name: 'stars', tint: 'secondary' },
      corner: { name: 'roseCluster', tint: '#8aa58c' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [
      L('dream', 'Delivery', undefined, 'FREE', true),
      L('arch', 'Dreams'),
      L('couple', 'Arrival', { hero: { name: 'stork' } }),
      L('floral', 'Wishes'),
      L('split', 'Mama', { hero: { name: 'momToBe', tint: 'primary' }, centre: { name: 'mandala', tint: 'accent' } }),
      L('photo', 'Hello', { hero: { name: 'stork' } }),
      L('minimal', 'Tiny', { hero: { name: 'teddyBear', tint: 'primary' } }),
    ],
  },
  {
    key: 'lori',
    word: 'Lori',
    phrase: 'A lullaby in midnight blue and soft gold, a sleepy moon over the cradle',
    occasion: 'babyShower',
    style: 'Dreamy',
    tags: ['baby-shower', 'night', 'moon', 'pastel'],
    colors: ['Lullaby', p('#2a3a6e', '#c9b06a', '#d9e2ff', '#f5f7ff', '#ffffff', '#141c40', '#5e6690')],
    presets: [
      ['Lilac', p('#6b4f8a', '#c9b06a', '#e6dcf3', '#faf8fd', '#ffffff', '#24183a', '#706885')],
      ['Sage', p('#4b6b4f', '#c9b06a', '#dbe6d2', '#f7f8f2', '#ffffff', '#202b22', '#66736a')],
    ],
    fonts: 'elegant',
    look: 'celebration',
    effect: 'fireflies',
    intro: 'celestial',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'script',
      hero: { name: 'babyCradle', tint: 'primary' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'secondary' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [
      L('night', 'Chanda', { centre: { name: 'mandala', tint: 'accent' }, skyline: { name: 'moonCloud' } }),
      L('couple', 'Palna'),
      L('arch', 'Taare'),
      L('photo', 'Sapne'),
      L('minimal', 'Neend'),
    ],
  },
  {
    key: 'valaikappu',
    word: 'Valaikappu',
    phrase: 'A valaikappu in silk green and gold, with glass bangles, jasmine and banana leaves',
    occasion: 'babyShower',
    style: 'Temple',
    tags: ['baby-shower', 'south-indian', 'tamil', 'seemantham'],
    colors: ['Silk Green', p('#14523d', '#d6a520', '#f3e3b8', '#f8f6ec', '#ffffff', '#11241c', '#5e6f64')],
    presets: [
      ['Arakku', p('#7d1515', '#d4a017', '#f6e7c1', '#fff8ec', '#ffffff', '#2e120c', '#7a5a4a')],
      ['Rani Pink', p('#a3195b', '#d4a017', '#f6d3a0', '#fff6f2', '#ffffff', '#2e1220', '#7d5a68')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'linen',
      strength: 0.45,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'momToBe', tint: 'accent' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'accent' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'gopuram',
      motif: { name: 'lotus', foil: true },
      card: 'banded',
    },
    layouts: [L('temple', 'Seemantham'), L('couple', 'Amma'), L('split', 'Valayal'), L('photo', 'Malli'), L('minimal', 'Kumkum', { dark: false, foil: false })],
  },

  // ─────────────────────────── Naming and mundan ───────────────────────────
  {
    key: 'naam',
    word: 'Naam',
    phrase: 'A namkaran in saffron and gold, the baby in a cradle under a marigold toran',
    occasion: 'naming',
    style: 'Traditional',
    tags: ['naming', 'namkaran', 'hindu', 'baby'],
    colors: ['Saffron & Gold', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    presets: [
      ['Maroon', p('#6b1426', '#c9973f', '#f3d9a4', '#fbf4ea', '#fffaf2', '#2b1712', '#7a5d52')],
      ['Peacock', p('#0d4f4c', '#c9a24a', '#e2e0b0', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'babyCradle', tint: 'primary' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      float: { name: 'moonCloud' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [
      L('home', 'Sanskar', undefined, 'STANDARD', true),
      L('couple', 'Utsav'),
      L('arch', 'Aashish'),
      L('jharokha', 'Haveli', { dark: true, foil: true, pair: { name: 'elephant', tint: 'accent' } }),
      L('split', 'Chandrama'),
      L('photo', 'Pehchaan'),
      L('minimal', 'Akshar'),
    ],
  },
  {
    key: 'palna',
    word: 'Palna',
    phrase: 'Mint, peach and cream, a cradle under a sleepy moon for the naming day',
    occasion: 'naming',
    style: 'Dreamy',
    tags: ['naming', 'baby', 'pastel', 'modern'],
    colors: ['Mint & Peach', p('#2a8a72', '#f0a868', '#ffd9c2', '#f5fbf9', '#ffffff', '#0f2e26', '#5a786f')],
    presets: [
      ['Baby Blue', p('#3d6ea8', '#e8b04a', '#d6e6f7', '#f6f9fd', '#ffffff', '#16263a', '#5f7088')],
      ['Baby Pink', p('#c0567e', '#e8b04a', '#f9d3e1', '#fff7fa', '#ffffff', '#3a1626', '#86667a')],
    ],
    fonts: 'playful',
    look: 'celebration',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.4,
      foil: false,
      nameFont: 'script',
      hero: { name: 'babyCradle', tint: 'primary' },
      float: { name: 'moonCloud' },
      pair: { name: 'balloonBunch' },
      sky: { name: 'stars', tint: 'secondary' },
      corner: { name: 'roseCluster', tint: '#8aa58c' },
      top: { name: 'bunting' },
      motif: { name: 'flourish', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [L('dream', 'Jhoola'), L('couple', 'Nanhe'), L('floral', 'Kaliyan'), L('arch', 'Taara'), L('photo', 'Pyaara'), L('minimal', 'Naam')],
  },
  {
    key: 'mundan',
    word: 'Mundan',
    phrase: 'A mundan sanskar in marigold and leaf green, with the kalash and temple bells',
    occasion: 'naming',
    eventTypes: ['MUNDAN', 'NAMING_CEREMONY'],
    style: 'Traditional',
    tags: ['mundan', 'hindu', 'baby', 'traditional'],
    colors: ['Marigold & Leaf', p('#2f6b3f', '#e6a325', '#ffcf6b', '#f8f8ec', '#ffffff', '#1a2a1d', '#62705f')],
    presets: [
      ['Saffron', p('#b4471a', '#e8a317', '#ffd2a0', '#fff7ef', '#ffffff', '#33170a', '#80624d')],
      ['Temple Red', p('#7d1515', '#d4a017', '#f6e7c1', '#fff8ec', '#ffffff', '#2e120c', '#7a5a4a')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'kalash' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [
      L('home', 'Sanskar'),
      L('couple', 'Utsav', { hero: { name: 'teddyBear', tint: 'primary' } }),
      L('arch', 'Aashirwad'),
      L('temple', 'Mandir', { pair: { name: 'bananaLeaf', tint: '#3d7f3e' } }),
      L('photo', 'Pal'),
      L('minimal', 'Shubh'),
    ],
  },
];
