import { L, palette as p, type Theme } from './theme';

const GANESH = '॥ श्री गणेशाय नमः ॥';

/** Housewarmings, pujas and festivals. */
export const HOME_THEMES: Theme[] = [
  // ─────────────────────────── Housewarming ───────────────────────────
  {
    key: 'vastu',
    word: 'Vastu',
    phrase: 'A griha pravesh in marigold and maroon: a toran at the door, the kalash and a row of diyas',
    occasion: 'housewarming',
    style: 'Traditional',
    tags: ['housewarming', 'griha-pravesh', 'hindu', 'traditional'],
    colors: ['Marigold & Maroon', p('#7a1c14', '#e0a51a', '#ffd89a', '#fff8ef', '#ffffff', '#2c120e', '#7b5f52')],
    presets: [
      ['Leaf Green', p('#2f6b3f', '#e6a325', '#ffcf6b', '#f8f8ec', '#ffffff', '#1a2a1d', '#62705f')],
      ['Royal Blue', p('#1f3a8a', '#d4a017', '#ffd99a', '#f6f7fc', '#ffffff', '#101b45', '#5e6688')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'house' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'toran',
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [
      L('home', 'Shanti', undefined, 'STANDARD', true),
      L('home', 'Kalash', { hero: { name: 'kalash' } }),
      L('couple', 'Ghar'),
      L('arch', 'Dwar'),
      L('mandap', 'Toran'),
      L('jharokha', 'Haveli', { dark: true, foil: true, pair: { name: 'elephant', tint: 'accent' } }),
      L('photo', 'Naya'),
      L('minimal', 'Deep'),
    ],
  },
  {
    key: 'dehleez',
    word: 'Dehleez',
    phrase: 'Sage, blush and cream: a cosy new home and a rangoli at the threshold',
    occasion: 'housewarming',
    style: 'Modern',
    tags: ['housewarming', 'modern', 'pastel'],
    colors: ['Sage & Blush', p('#4b6b4f', '#c9976a', '#f6d6cc', '#f8f8f2', '#ffffff', '#202b22', '#66736a')],
    presets: [
      ['Terracotta', p('#9a4a2a', '#b88a4a', '#efd6bf', '#faf4ee', '#fffdf9', '#2e1a10', '#7a6658')],
      ['Dusty Blue', p('#3f5b7a', '#b39a6b', '#cfdcea', '#f5f7fa', '#ffffff', '#1f2a36', '#677585')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.5,
      foil: false,
      nameFont: 'script',
      hero: { name: 'house' },
      corner: { name: 'roseCluster', tint: '#7a8f6a' },
      top: { name: 'floralGarland', tint: '#7a8f6a' },
      centre: { name: 'mandala', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      card: 'minimal',
    },
    layouts: [L('couple', 'Basera'), L('arch', 'Swagat'), L('home', 'Aangan'), L('photo', 'Sapna'), L('minimal', 'Chaukhat'), L('floral', 'Bagicha')],
  },
  {
    key: 'haven',
    word: 'Haven',
    phrase: 'Navy and gold, a house that glows with lamps, for a modern housewarming',
    occasion: 'housewarming',
    style: 'Modern',
    tags: ['housewarming', 'modern', 'minimal'],
    colors: ['Navy & Gold', p('#1f3355', '#c2a46a', '#e3e8f0', '#f8f8fb', '#ffffff', '#141c2e', '#5f6a80')],
    presets: [
      ['Forest', p('#14503a', '#c2a46a', '#dfe9df', '#f7f8f3', '#ffffff', '#0c241a', '#5f6f66')],
      ['Charcoal & Coral', p('#2e2a30', '#e07a5f', '#f6d6cc', '#f8f6f7', '#ffffff', '#151316', '#6e6870')],
    ],
    fonts: 'modern',
    look: 'modern',
    effect: 'confetti',
    kit: {
      dark: false,
      texture: 'grain',
      strength: 0.2,
      foil: false,
      nameFont: 'heading',
      nameWeight: 700,
      hero: { name: 'house' },
      pair: { name: 'balloonBunch' },
      top: { name: 'fairyLights' },
      motif: { name: 'flourish' },
      card: 'minimal',
    },
    layouts: [L('minimal', 'Home'), L('photo', 'Keys'), L('couple', 'Welcome'), L('arch', 'Doorway'), L('party', 'Party')],
  },

  // ─────────────────────────── Puja ───────────────────────────
  {
    key: 'aarti',
    word: 'Aarti',
    phrase: 'A puja in saffron and gold: the kalash, diyas, temple bells and a lotus',
    occasion: 'puja',
    style: 'Traditional',
    tags: ['puja', 'religious', 'hindu', 'temple'],
    colors: ['Saffron', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    presets: [
      ['Kumkum', p('#7a1020', '#d4a017', '#f6dfae', '#fff8ef', '#ffffff', '#2e080d', '#7b5d58')],
      ['Tulsi Green', p('#1f5a2c', '#d4a017', '#e8e0b0', '#f5f8ef', '#ffffff', '#12261a', '#5f6f60')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'kalash' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'mandala', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'gopuram',
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [
      L('home', 'Thali', undefined, 'STANDARD', true),
      L('temple', 'Ghanti', { pair: { name: 'bananaLeaf', tint: '#3d7f3e' } }),
      L('mandap', 'Mandir'),
      L('night', 'Sandhya', { hero: undefined }),
      L('couple', 'Deep'),
      L('photo', 'Prasad'),
      L('minimal', 'Om'),
    ],
  },
  {
    key: 'katha',
    word: 'Katha',
    phrase: 'A katha at home in marigold and leaf green, with a toran and the kalash',
    occasion: 'puja',
    style: 'Traditional',
    tags: ['puja', 'katha', 'hindu', 'home'],
    colors: ['Marigold & Leaf', p('#2c6a3a', '#e8a325', '#ffd07a', '#f8f9ee', '#ffffff', '#162a1b', '#62705f')],
    presets: [
      ['Saffron & Red', p('#9a1f1a', '#e8a325', '#ffd07a', '#fff7ef', '#ffffff', '#2e0c0a', '#7d5f58')],
      ['Turmeric', p('#9a5b00', '#e8a317', '#ffe08a', '#fffbea', '#ffffff', '#2e1d04', '#7b6446')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'kalash' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [L('home', 'Path'), L('arch', 'Vrat'), L('couple', 'Kalash'), L('split', 'Shraddha'), L('photo', 'Bhog'), L('minimal', 'Mangal')],
  },
  {
    key: 'janeu',
    word: 'Janeu',
    phrase: 'An upanayanam in temple red and gold: bells, jasmine and the gopuram',
    occasion: 'puja',
    eventTypes: ['THREAD_CEREMONY', 'RELIGIOUS'],
    style: 'Temple',
    tags: ['thread-ceremony', 'upanayanam', 'janeu', 'south-indian'],
    colors: ['Temple Gold', p('#6e1a10', '#d6a21a', '#f6e4b8', '#fff8ec', '#ffffff', '#2e120c', '#7a5a4a')],
    presets: [
      ['Mayil Green', p('#0f4d3a', '#d4a017', '#f1e5bf', '#f8f6ec', '#ffffff', '#11241c', '#5e6f64')],
      ['Saffron', p('#a8430f', '#d4a017', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'linen',
      strength: 0.45,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'kalash' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'accent' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'gopuram',
      motif: { name: 'lotus', foil: true },
      invocation: GANESH,
      card: 'banded',
    },
    layouts: [
      L('temple', 'Sanskar'),
      L('couple', 'Vatu'),
      L('home', 'Yagna', { dark: false, foil: false, top: { name: 'toran' } }),
      L('photo', 'Diksha'),
      L('minimal', 'Gayatri', { dark: false, foil: false, hero: undefined, corner: { name: 'lotus', tint: 'secondary' } }),
    ],
  },

  // ─────────────────────────── Festivals ───────────────────────────
  {
    key: 'jyoti',
    word: 'Jyoti',
    phrase: 'Diwali in deep purple and gold: diyas, lanterns and rangoli',
    occasion: 'festival',
    style: 'Festive',
    tags: ['festival', 'diwali', 'deepavali', 'lights'],
    colors: ['Diwali Night', p('#3d1a5c', '#e8a317', '#ffd08a', '#f9f5fb', '#ffffff', '#1e0c2f', '#6d6080')],
    presets: [
      ['Royal Maroon', p('#5c0f1f', '#e8a317', '#ffd08a', '#fbf4ea', '#fffaf2', '#2b1712', '#7a5d52')],
      ['Peacock', p('#0d4f4c', '#e8a317', '#ffd08a', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
    ],
    fonts: 'grand',
    look: 'royal',
    effect: 'lanterns',
    intro: 'lanterns',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'house' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('night', 'Raat', { hero: undefined }, 'STANDARD', true), L('home', 'Deep'), L('arch', 'Rangoli'), L('photo', 'Milan'), L('minimal', 'Diya'), L('split', 'Phuljhadi')],
  },
  {
    key: 'chand',
    word: 'Chand',
    phrase: 'Eid in emerald and gold: a crescent moon, lanterns and domes',
    occasion: 'festival',
    style: 'Festive',
    tags: ['festival', 'eid', 'muslim', 'night'],
    colors: ['Emerald Night', p('#0c4434', '#cfa52e', '#f0e2ae', '#f7f4ea', '#fffdf5', '#0e1f18', '#5b6f65')],
    presets: [
      ['Midnight Blue', p('#13285c', '#cfa63a', '#efe0b2', '#f4f5f9', '#ffffff', '#0c1430', '#5a6383')],
      ['Teal & Gold', p('#0d4f4c', '#cfa63a', '#e2e0b0', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
    ],
    fonts: 'elegant',
    look: 'royal',
    effect: 'lanterns',
    intro: 'lanterns',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'lantern', tint: 'secondary' },
      pair: { name: 'lantern', tint: 'secondary' },
      hang: { name: 'lantern' },
      centre: { name: 'arabesque', tint: 'primary' },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'domes', foil: true },
      scene: 'arches',
      motif: { name: 'flourish', foil: true },
      crest: { name: 'crescent', tint: 'secondary' },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('night', 'Raat', { hero: undefined }, 'STANDARD', true), L('arch', 'Mubarak'), L('mandap', 'Mehrab'), L('photo', 'Daawat'), L('minimal', 'Noor')],
  },
  {
    key: 'gulal',
    word: 'Gulal',
    phrase: 'Holi in every colour: gulal pink, turmeric, leaf green and sky blue',
    occasion: 'festival',
    style: 'Festive',
    tags: ['festival', 'holi', 'colourful'],
    colors: ['Gulal', p('#d6336c', '#f59f00', '#2bb3a3', '#fffaf3', '#ffffff', '#2a1020', '#7d6070')],
    presets: [
      ['Sky & Lime', p('#1c7ed6', '#f59f00', '#94d82d', '#f5f9ff', '#ffffff', '#0c2340', '#5f6f88')],
      ['Purple & Yellow', p('#7b2cbf', '#ffd43b', '#ff6fb5', '#fbf7ff', '#ffffff', '#24103a', '#71658a')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'confetti',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.5,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'dhol' },
      pair: { name: 'balloonBunch' },
      top: { name: 'bunting' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      sky: { name: 'confetti', tint: 'accent' },
      motif: { name: 'flourish' },
      crest: { name: 'rangoliBloom', tint: 'secondary' },
      card: 'header',
    },
    layouts: [L('party', 'Rang'), L('split', 'Pichkari'), L('photo', 'Masti'), L('minimal', 'Abeer'), L('couple', 'Holi')],
  },
  {
    key: 'noel',
    word: 'Noel',
    phrase: 'Christmas in red, green and gold: fairy lights, presents and a starry sky',
    occasion: 'festival',
    style: 'Festive',
    tags: ['festival', 'christmas', 'christian'],
    colors: ['Holly', p('#9b1c2c', '#d4a017', '#cfe8d0', '#fbf7f2', '#ffffff', '#2e0a10', '#7a5d5e')],
    presets: [
      ['Evergreen', p('#14503a', '#d4a017', '#f3d6d6', '#f6f8f3', '#ffffff', '#0c241a', '#5f6f66')],
      ['Midnight', p('#14213d', '#d4a017', '#efe2c0', '#f5f6f9', '#ffffff', '#0a1120', '#5b6680')],
    ],
    fonts: 'classic',
    look: 'celebration',
    effect: 'snow',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: false,
      nameFont: 'script',
      hero: { name: 'giftBox' },
      pair: { name: 'doves', tint: 'secondary' },
      top: { name: 'fairyLights' },
      float: { name: 'moonCloud' },
      sky: { name: 'stars', tint: 'secondary' },
      skyline: { name: 'giftBox' },
      motif: { name: 'flourish' },
      crest: { name: 'giftBox' },
      card: 'minimal',
    },
    layouts: [L('party', 'Joy', { pair: { name: 'balloonBunch' } }), L('dream', 'Starlight'), L('minimal', 'Carol'), L('photo', 'Merry')],
  },
  {
    key: 'navrang',
    word: 'Navrang',
    phrase: 'Navratri nights in nine colours, with the dhol, marigolds and a mirror-bright rangoli',
    occasion: 'festival',
    style: 'Festive',
    tags: ['festival', 'navratri', 'garba', 'gujarati'],
    colors: ['Navratri', p('#a3195b', '#f0a92b', '#3dc1d3', '#fff6f0', '#ffffff', '#2e1220', '#7d5a68')],
    presets: [
      ['Royal Blue', p('#1f3fae', '#f0a92b', '#ffd27a', '#f4f6fd', '#ffffff', '#101b45', '#5e6688')],
      ['Parrot Green', p('#2e7d32', '#f5a623', '#ff6fa3', '#f6fbf2', '#ffffff', '#132b15', '#5e735f')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'dhol' },
      pair: { name: 'lantern', tint: 'secondary' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [L('split', 'Garba', undefined, 'STANDARD', true), L('home', 'Aarti', { hero: { name: 'kalash' } }), L('couple', 'Dandiya'), L('photo', 'Raas'), L('minimal', 'Shakti')],
  },
  {
    key: 'pongal',
    word: 'Pongal',
    phrase: 'Pongal in turmeric and leaf green: a kolam, banana leaves and a brimming pot',
    occasion: 'festival',
    style: 'Temple',
    tags: ['festival', 'pongal', 'sankranti', 'south-indian'],
    colors: ['Harvest', p('#1f5a2c', '#e0a51a', '#ffe08a', '#fbfaee', '#ffffff', '#12261a', '#5f6f60')],
    presets: [
      ['Sugarcane', p('#5a2a6b', '#e0a51a', '#f3dcae', '#fbf7fb', '#ffffff', '#24102b', '#76627c')],
      ['Sun Red', p('#9a1f1a', '#e0a51a', '#ffd07a', '#fff7ef', '#ffffff', '#2e0c0a', '#7d5f58')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'marigold',
    kit: {
      dark: false,
      texture: 'linen',
      strength: 0.45,
      foil: false,
      nameFont: 'heading',
      hero: { name: 'kalash' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      top: { name: 'toran' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'primary' },
      corner: { name: 'kolam', tint: 'primary' },
      scene: 'gopuram',
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      card: 'banded',
    },
    layouts: [L('home', 'Kolam'), L('temple', 'Thai', { dark: true, foil: true }), L('photo', 'Vazhthu'), L('minimal', 'Karumbu')],
  },
];
