import { L, palette as p, type Theme } from './theme';

const GANESH = '॥ श्री गणेशाय नमः ॥';

/** Wedding themes: each a tradition or a mood, with the layouts that suit it. */
export const WEDDING_THEMES: Theme[] = [
  {
    key: 'rajwada',
    word: 'Rajwada',
    phrase: 'Royal Rajasthani maroon and gold on paper stock',
    occasion: 'wedding',
    style: 'Royal',
    tags: ['hindu', 'rajasthani', 'royal', 'heritage'],
    colors: ['Maroon & Gold', p('#5c0f1f', '#c9973f', '#f3d9a4', '#fbf4ea', '#fffaf2', '#2b1712', '#7a5d52')],
    presets: [
      ['Emerald Durbar', p('#0f3d2e', '#c9a24a', '#ecdcae', '#f6f3e9', '#fffdf6', '#122019', '#5f6f66')],
      ['Royal Indigo', p('#1e2457', '#d1a54a', '#f0dca8', '#f6f5f1', '#ffffff', '#141833', '#5d6380')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'goldDust',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.5,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'elephant', tint: 'accent' },
      top: { name: 'toran' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      centre: { name: 'medallion', tint: 'secondary' },
      hang: { name: 'lantern' },
      scene: 'palace',
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [
      L('jharokha', 'Jharokha', undefined, 'PREMIUM', true),
      L('couple', 'Milan'),
      L('mandap', 'Mandap'),
      L('portrait', 'Roop'),
      L('arch', 'Darbar'),
      L('split', 'Varmala', { hero: { name: 'coupleVarmala', tint: 'primary' } }),
      L('night', 'Chandni', { skyline: { name: 'domes', foil: true } }),
      L('home', 'Aangan', { hero: { name: 'coupleVarmala', tint: 'primary' } }),
      L('minimal', 'Moti'),
      L('photo', 'Yaad'),
    ],
  },
  {
    key: 'mayur',
    word: 'Mayur',
    phrase: 'A peacock garden in teal, jade and gold watercolour',
    occasion: 'wedding',
    style: 'Illustrated',
    tags: ['hindu', 'peacock', 'garden', 'romantic'],
    colors: ['Peacock Teal', p('#0d4f4c', '#c9a24a', '#1f8a7a', '#f7f2e7', '#ffffff', '#15302d', '#5c726e')],
    presets: [
      ['Peacock Blue', p('#1b3a7a', '#c9a24a', '#2a7fb0', '#f3f5fa', '#ffffff', '#141c33', '#5d6582')],
      ['Jade Blush', p('#2f6b5a', '#c08a5c', '#d98f8c', '#fbf5f1', '#ffffff', '#20302b', '#6e7c76')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.6,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'royalPeacock', tint: 'accent' },
      top: { name: 'toran' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      centre: { name: 'medallion' },
      scene: 'lotus',
      motif: { name: 'flourish', foil: true },
      card: 'framed',
    },
    layouts: [
      L('arch', 'Pankh', { hero: undefined }, 'STANDARD', true),
      L('couple', 'Bagh'),
      L('jharokha', 'Mahal', { pair: { name: 'royalPeacock', tint: 'accent' } }),
      L('floral', 'Kunj'),
      L('portrait', 'Rang'),
      L('mandap', 'Sarovar'),
      L('split', 'Neel'),
      L('minimal', 'Sutra'),
      L('photo', 'Pal'),
    ],
  },
  {
    key: 'kanchi',
    word: 'Kanchi',
    phrase: 'A South Indian temple wedding in Kanjeevaram red and gold',
    occasion: 'wedding',
    style: 'Temple',
    tags: ['hindu', 'south-indian', 'tamil', 'telugu', 'temple'],
    colors: ['Temple Red', p('#7d1515', '#d4a017', '#f6e7c1', '#fff8ec', '#ffffff', '#2e120c', '#7a5a4a')],
    presets: [
      ['Mayil Green', p('#0f4d3a', '#d4a017', '#f1e5bf', '#f8f6ec', '#ffffff', '#11241c', '#5e6f64')],
      ['Kanjeevaram Purple', p('#4a1658', '#d4a017', '#f2dfb3', '#fbf6f2', '#ffffff', '#261030', '#76647c')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'marigold',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'linen',
      strength: 0.5,
      foil: true,
      nameFont: 'heading',
      hero: { name: 'coupleSouth', tint: 'accent' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'accent' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'gopuram',
      motif: { name: 'lotus', foil: true },
      card: 'banded',
    },
    layouts: [
      L('temple', 'Deepa', undefined, 'PREMIUM', true),
      L('couple', 'Kalyanam'),
      L('mandap', 'Gopuram', { hero: { name: 'coupleSouth', tint: 'accent' } }),
      L('arch', 'Kolam'),
      L('split', 'Malli'),
      L('home', 'Muhurtham', { hero: { name: 'coupleSouth', tint: 'accent' }, top: { name: 'toran' } }),
      L('minimal', 'Kumkum', { dark: false, foil: false }),
      L('photo', 'Pattu'),
    ],
  },
  {
    key: 'kerala',
    word: 'Kerala',
    phrase: 'Kasavu ivory and gold by the backwaters',
    occasion: 'wedding',
    style: 'Heritage',
    tags: ['hindu', 'kerala', 'malayali', 'south-indian'],
    colors: ['Kasavu', p('#5b3a12', '#c9a227', '#e9dcb8', '#f8f3e6', '#fffdf6', '#2b1f10', '#7a6a50')],
    presets: [
      ['Temple Green', p('#1f4d2c', '#c9a227', '#e2dcae', '#f5f6ec', '#ffffff', '#16261a', '#5f6e60')],
      ['Thrissur Red', p('#7a1c14', '#c9a227', '#f0dcb0', '#fbf5ec', '#ffffff', '#2c120e', '#7b5f52')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    intro: 'curtain',
    kit: {
      dark: false,
      texture: 'linen',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleSouth', tint: '#e3cf98' },
      pair: { name: 'bananaLeaf', tint: '#3d7f3e' },
      hang: { name: 'jasmineStrand' },
      centre: { name: 'kolam', tint: 'secondary' },
      corner: { name: 'filigreeCorner' },
      scene: 'backwaters',
      motif: { name: 'lotus' },
      card: 'minimal',
    },
    layouts: [
      L('mandap', 'Kayal', undefined, 'PREMIUM', true),
      L('couple', 'Mangalyam'),
      L('arch', 'Vilakku'),
      L('home', 'Pookalam'),
      L('split', 'Mullapoo'),
      L('minimal', 'Thali'),
      L('photo', 'Ormakal'),
      L('floral', 'Thamara', { corner: { name: 'paisleyOrnate', tint: 'secondary' }, motif: { name: 'lotus' } }),
    ],
  },
  {
    key: 'mehtab',
    word: 'Mehtab',
    phrase: 'A Mughal night in emerald and gold, with lanterns and domes',
    occasion: 'wedding',
    style: 'Royal',
    tags: ['muslim', 'nikah', 'walima', 'mughal', 'night'],
    colors: ['Emerald Night', p('#0b3d2e', '#c9a227', '#f1e3b0', '#f7f4ea', '#fffdf5', '#0e1f18', '#5b6f65')],
    presets: [
      ['Midnight Blue', p('#13285c', '#cfa63a', '#efe0b2', '#f4f5f9', '#ffffff', '#0c1430', '#5a6383')],
      ['Plum & Gold', p('#4b1840', '#cda23e', '#f0deb4', '#faf5f8', '#ffffff', '#230b1f', '#77627a')],
    ],
    fonts: 'elegant',
    look: 'royal',
    effect: 'lanterns',
    intro: 'lanterns',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleNikah', tint: 'primary' },
      pair: { name: 'doves', tint: 'secondary' },
      hang: { name: 'lantern' },
      centre: { name: 'arabesque', tint: 'primary' },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'domes', foil: true },
      scene: 'arches',
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [
      L('night', 'Raat', undefined, 'PREMIUM', true),
      L('couple', 'Qubool'),
      L('arch', 'Mehrab'),
      L('mandap', 'Darwaza'),
      L('jharokha', 'Jharokha', { pair: { name: 'doves', tint: 'secondary' } }),
      L('floral', 'Gulshan', { corner: { name: 'roseCluster', tint: '#5e8a6a' }, dark: false, foil: false }),
      L('minimal', 'Sitara'),
      L('photo', 'Lamha'),
      L('split', 'Mubarak'),
    ],
  },
  {
    key: 'zardozi',
    word: 'Zardozi',
    phrase: 'Wine and gold embroidery for a nikah and walima',
    occasion: 'wedding',
    style: 'Royal',
    tags: ['muslim', 'nikah', 'walima', 'luxury'],
    colors: ['Wine & Zari', p('#5a1230', '#d1a648', '#f0d9a8', '#faf4f0', '#ffffff', '#2a0a18', '#7a5d68')],
    presets: [
      ['Pista & Gold', p('#41602e', '#c9a24a', '#e8e0b0', '#f6f7ef', '#ffffff', '#1e2b16', '#66705c')],
      ['Ivory Zari', p('#6b5a3a', '#c9a24a', '#efe2c0', '#fbf8f0', '#ffffff', '#2d2516', '#7b705c')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'goldDust',
    intro: 'curtain',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleNikah', tint: 'accent' },
      pair: { name: 'lantern', tint: 'secondary' },
      hang: { name: 'lantern' },
      centre: { name: 'arabesque', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      skyline: { name: 'domes', foil: true },
      scene: 'arches',
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('night', 'Shab'), L('arch', 'Mehrab'), L('couple', 'Mubarak'), L('mandap', 'Darbar'), L('minimal', 'Zari'), L('photo', 'Afreen'), L('jharokha', 'Haveli', { pair: { name: 'doves', tint: 'secondary' } })],
  },
  {
    key: 'rosewood',
    word: 'Rosewood',
    phrase: 'Garden roses in soft watercolour for a church or garden wedding',
    occasion: 'wedding',
    style: 'Floral',
    tags: ['christian', 'church', 'floral', 'garden', 'classic'],
    colors: ['Blush Rose', p('#8c3b4a', '#a88a5a', '#f2c4cc', '#fbf7f2', '#ffffff', '#3a2a2c', '#857174')],
    presets: [
      ['Sage Garden', p('#4f6b52', '#b0915c', '#d8e4d3', '#f7f8f2', '#ffffff', '#232d24', '#6b776c')],
      ['Dusty Blue', p('#3f5b7a', '#b39a6b', '#cfdcea', '#f5f7fa', '#ffffff', '#1f2a36', '#677585')],
    ],
    fonts: 'classic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.6,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleChristian', tint: 'accent' },
      corner: { name: 'roseCluster', tint: '#6b8f6e' },
      top: { name: 'floralGarland', tint: '#6b8f6e' },
      scene: 'floral',
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [
      L('floral', 'Garden', undefined, 'STANDARD', true),
      L('couple', 'Vows'),
      L('arch', 'Chapel'),
      L('mandap', 'Arbour'),
      L('minimal', 'Ivory'),
      L('photo', 'Forever'),
      L('split', 'Promise'),
      L('dream', 'Dusk', { float: { name: 'doves', tint: 'secondary' }, hero: { name: 'coupleChristian', tint: 'accent' } }),
    ],
  },
  {
    key: 'lily',
    word: 'Lily',
    phrase: 'White florals and greenery, light as a veil',
    occasion: 'wedding',
    style: 'Elegant',
    tags: ['christian', 'church', 'floral', 'white', 'modern'],
    colors: ['Lily White', p('#3f5a4a', '#b49a62', '#e6eee6', '#fbfbf7', '#ffffff', '#1f2a24', '#6a766e')],
    presets: [
      ['Navy & Blush', p('#1f3355', '#b49a62', '#f2d4d9', '#f8f8fb', '#ffffff', '#141c2e', '#5f6a80')],
      ['Champagne', p('#6b5338', '#c2a46a', '#efe3cc', '#fbf8f2', '#ffffff', '#2c2216', '#7d6e5a')],
    ],
    fonts: 'elegant',
    look: 'classic',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.4,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleChristian', tint: 'accent' },
      corner: { name: 'roseCluster', tint: '#7f9a83' },
      top: { name: 'floralGarland', tint: '#7f9a83' },
      motif: { name: 'doves', tint: 'secondary' },
      scene: 'floral',
      card: 'minimal',
    },
    layouts: [L('minimal', 'Veil'), L('floral', 'Bouquet'), L('arch', 'Aisle'), L('couple', 'Ever After'), L('photo', 'Moment'), L('mandap', 'Arch')],
  },
  {
    key: 'laavan',
    word: 'Laavan',
    phrase: 'An Anand Karaj in phulkari pinks and saffron',
    occasion: 'wedding',
    style: 'Festive',
    tags: ['sikh', 'punjabi', 'anand-karaj', 'festive'],
    colors: ['Phulkari Pink', p('#a3195b', '#e0a03a', '#f6c66b', '#fff6ef', '#ffffff', '#2e1220', '#7d5a68')],
    presets: [
      ['Saffron', p('#b34700', '#d4a017', '#ffd27a', '#fff8ec', '#ffffff', '#2e1a0a', '#7a6248')],
      ['Royal Blue', p('#20307a', '#e0a03a', '#f6c66b', '#f5f6fb', '#ffffff', '#141a3a', '#5e6585')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleSikh', tint: 'primary' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'sarovar',
      motif: { name: 'flourish' },
      card: 'garland',
    },
    layouts: [
      L('couple', 'Karaj', undefined, 'STANDARD', true),
      L('split', 'Shagun'),
      L('mandap', 'Sarovar', { dark: true, foil: true }),
      L('arch', 'Darshan'),
      L('jharokha', 'Haveli', { pair: { name: 'kalash' } }),
      L('floral', 'Phulkari', { corner: { name: 'paisleyOrnate', tint: 'accent' } }),
      L('home', 'Mela', { hero: { name: 'coupleSikh', tint: 'primary' } }),
      L('minimal', 'Kesri'),
      L('photo', 'Baraat'),
    ],
  },
  {
    key: 'sindoor',
    word: 'Sindoor',
    phrase: 'A Bengali biye in red, white and gold, with alpana and the topor',
    occasion: 'wedding',
    style: 'Traditional',
    tags: ['hindu', 'bengali', 'traditional'],
    colors: ['Lal Paar', p('#a1121b', '#c9973f', '#f6e6d4', '#fffaf5', '#ffffff', '#2c0d0f', '#7a5a5a')],
    presets: [
      ['Banarasi Gold', p('#7a1c14', '#d4a017', '#f3e1b7', '#fbf6ec', '#ffffff', '#2c120e', '#7b5f52')],
      ['Shola White', p('#6b2a2a', '#b8935c', '#efe6da', '#fdfbf8', '#ffffff', '#2a1414', '#7b6a62')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    intro: 'curtain',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.5,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleBengali', tint: 'primary' },
      pair: { name: 'doves', tint: 'primary' },
      top: { name: 'toran' },
      centre: { name: 'kolam', tint: 'primary' },
      corner: { name: 'paisleyOrnate', tint: 'primary' },
      scene: 'lotus',
      motif: { name: 'lotus' },
      card: 'garland',
    },
    layouts: [
      L('couple', 'Bibaho'),
      L('arch', 'Alpana'),
      L('mandap', 'Chhadnatala'),
      L('floral', 'Rajanigandha', { corner: { name: 'paisleyOrnate', tint: 'primary' } }),
      L('minimal', 'Shankha'),
      L('photo', 'Topor'),
      L('jharokha', 'Rajbari', { pair: { name: 'doves', tint: 'primary' }, dark: true, foil: true }),
      L('split', 'Mukut'),
    ],
  },
  {
    key: 'gulabi',
    word: 'Gulabi',
    phrase: 'Jaipur pink and gold, with painted elephants',
    occasion: 'wedding',
    style: 'Royal',
    tags: ['hindu', 'rajasthani', 'pink', 'royal'],
    colors: ['Pink City', p('#a01d5a', '#c9973f', '#f7c9da', '#fff5f8', '#ffffff', '#2e0f1e', '#86606f')],
    presets: [
      ['Rani & Orange', p('#b0195a', '#e08a2b', '#ffd0a8', '#fff6ef', '#ffffff', '#30101e', '#866068')],
      ['Lilac & Silver', p('#6a3a8c', '#9ea3b0', '#e5d8f0', '#faf7fc', '#ffffff', '#24162f', '#6f6480')],
    ],
    fonts: 'romantic',
    look: 'royal',
    effect: 'petals',
    intro: 'doors',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'elephant', tint: 'accent' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'palace',
      motif: { name: 'flourish', foil: true },
      card: 'framed',
    },
    layouts: [L('jharokha', 'Mahal'), L('couple', 'Shaam'), L('arch', 'Jharna'), L('portrait', 'Rani'), L('split', 'Rang'), L('mandap', 'Hawa'), L('minimal', 'Pankhuri'), L('photo', 'Kali'), L('floral', 'Bagicha', { corner: { name: 'paisleyOrnate', tint: 'accent' } })],
  },
  {
    key: 'panna',
    word: 'Panna',
    phrase: 'Emerald and gold, as rich as a maharaja’s treasury',
    occasion: 'wedding',
    style: 'Royal',
    tags: ['hindu', 'royal', 'emerald', 'luxury'],
    colors: ['Emerald', p('#0f4a35', '#c9a24a', '#eadcae', '#f6f3e9', '#fffdf6', '#0c241a', '#5f6f66')],
    presets: [
      ['Ruby', p('#6b0f1f', '#c9a24a', '#f0d6a8', '#fbf4ef', '#ffffff', '#2a0910', '#7b5d62')],
      ['Sapphire', p('#14306b', '#c9a24a', '#e7dcb6', '#f4f5f9', '#ffffff', '#0c1838', '#5a6383')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'goldDust',
    intro: 'doors',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'secondary' },
      pair: { name: 'royalPeacock', tint: 'accent' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'palace',
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('jharokha', 'Jharokha'), L('couple', 'Raas'), L('arch', 'Mehrab'), L('portrait', 'Shringar'), L('mandap', 'Mandap'), L('night', 'Chandni'), L('minimal', 'Sutra'), L('photo', 'Pal'), L('split', 'Varmala', { hero: { name: 'coupleVarmala', tint: 'secondary' } })],
  },
  {
    key: 'vrindavan',
    word: 'Neelam',
    phrase: 'Moonlit Vrindavan in sapphire and gold, with peacocks and the raas',
    occasion: 'wedding',
    style: 'Celestial',
    tags: ['hindu', 'krishna', 'vrindavan', 'peacock', 'night'],
    colors: ['Sapphire Night', p('#16245e', '#d1a54a', '#e9d9a6', '#f4f5fa', '#ffffff', '#0b1233', '#5a6383')],
    presets: [
      ['Yamuna Teal', p('#0d4a52', '#d1a54a', '#e2e0b0', '#f2f7f6', '#ffffff', '#0a2427', '#5a7375')],
      ['Midnight Plum', p('#3d1a5c', '#d1a54a', '#ecd8b0', '#f8f5fb', '#ffffff', '#1e0c2f', '#6d6080')],
    ],
    fonts: 'grand',
    look: 'royal',
    effect: 'fireflies',
    intro: 'celestial',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.35,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      pair: { name: 'royalPeacock', tint: 'accent' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion' },
      scene: 'vrindavan',
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'framed',
    },
    layouts: [L('mandap', 'Vrindavan', undefined, 'PREMIUM', true), L('couple', 'Raas'), L('arch', 'Bansuri', { hero: undefined }), L('night', 'Sharad', { skyline: { name: 'diyaRow' } }), L('jharokha', 'Mahal'), L('minimal', 'Moti'), L('photo', 'Yamuna'), L('split', 'Leela')],
  },
  {
    key: 'kesariya',
    word: 'Kesariya',
    phrase: 'Saffron and marigold, bright as a baraat',
    occasion: 'wedding',
    style: 'Festive',
    tags: ['hindu', 'festive', 'marigold', 'colourful'],
    colors: ['Saffron', p('#a8430f', '#e6a325', '#ffd08a', '#fff8ec', '#ffffff', '#2e1608', '#7a5f48')],
    presets: [
      ['Marigold & Green', p('#2f6b3f', '#e6a325', '#ffcf6b', '#f8f8ec', '#ffffff', '#1a2a1d', '#62705f')],
      ['Rani & Saffron', p('#a3195b', '#e6a325', '#ffc27a', '#fff6f2', '#ffffff', '#2e1220', '#7d5a68')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'marigold',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleVarmala', tint: 'primary' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'toran',
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [L('couple', 'Varmala'), L('split', 'Utsav'), L('mandap', 'Dwar'), L('arch', 'Baraat'), L('home', 'Aangan'), L('floral', 'Genda'), L('photo', 'Mela'), L('minimal', 'Kesar'), L('portrait', 'Saathi')],
  },
  {
    key: 'paithani',
    word: 'Paithani',
    phrase: 'Maharashtrian purple and green silk with a peacock border',
    occasion: 'wedding',
    style: 'Traditional',
    tags: ['hindu', 'marathi', 'maharashtrian', 'peacock'],
    colors: ['Paithani Purple', p('#5a1f6b', '#c9a227', '#9ccf8a', '#fbf6fb', '#ffffff', '#24102b', '#76627c')],
    presets: [
      ['Popati Green', p('#2f6b2f', '#c9a227', '#e6c0d8', '#f7faf3', '#ffffff', '#162a16', '#617061')],
      ['Ruby & Gold', p('#8a1538', '#c9a227', '#f2d39a', '#fdf6f6', '#ffffff', '#2e0b16', '#7d5a63')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    intro: 'doors',
    kit: {
      dark: false,
      texture: 'linen',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleSouth', tint: 'primary' },
      pair: { name: 'royalPeacock', tint: 'accent' },
      top: { name: 'toran' },
      centre: { name: 'medallion' },
      corner: { name: 'paisleyOrnate', tint: 'accent' },
      scene: 'mandap',
      motif: { name: 'flourish', foil: true },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [L('couple', 'Lagna'), L('arch', 'Mor', { hero: undefined }), L('jharokha', 'Wada'), L('split', 'Shalu'), L('mandap', 'Mandav'), L('minimal', 'Nath'), L('photo', 'Saptapadi'), L('floral', 'Bel')],
  },
  {
    key: 'bandhani',
    word: 'Bandhani',
    phrase: 'Gujarati red and yellow with mirrorwork brightness',
    occasion: 'wedding',
    style: 'Festive',
    tags: ['hindu', 'gujarati', 'festive', 'colourful'],
    colors: ['Lal Bandhej', p('#b01a24', '#e8a33d', '#ffd166', '#fff7ec', '#ffffff', '#2e0c0e', '#7d5a52')],
    presets: [
      ['Leheriya Green', p('#2e6b35', '#e8a33d', '#ffd166', '#f7f9ef', '#ffffff', '#16291a', '#62705f')],
      ['Indigo Mirror', p('#24357a', '#e8a33d', '#ffd8a0', '#f5f6fb', '#ffffff', '#141c3a', '#5f6685')],
    ],
    fonts: 'desi',
    look: 'celebration',
    effect: 'confetti',
    intro: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.45,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'rangoliBloom', tint: 'secondary' },
      corner: { name: 'paisleyOrnate', tint: 'secondary' },
      scene: 'toran',
      skyline: { name: 'diyaRow' },
      motif: { name: 'flourish' },
      invocation: GANESH,
      card: 'garland',
    },
    layouts: [L('couple', 'Lagan'), L('split', 'Garba'), L('arch', 'Chundadi'), L('mandap', 'Mandvo'), L('home', 'Pol'), L('minimal', 'Kanku'), L('photo', 'Mehfil'), L('floral', 'Phool')],
  },
  {
    key: 'banaras',
    word: 'Banaras',
    phrase: 'Banarasi red and gold by the ghats, lamps on the river',
    occasion: 'wedding',
    style: 'Traditional',
    tags: ['hindu', 'banarasi', 'ghats', 'traditional'],
    colors: ['Banarasi Red', p('#8a1020', '#d1a54a', '#f3dcae', '#fbf4ec', '#ffffff', '#2e080d', '#7b5d58')],
    presets: [
      ['Ganga Blue', p('#173d6b', '#d1a54a', '#e9dbb2', '#f4f6f9', '#ffffff', '#0d1f38', '#5a6680')],
      ['Marigold Silk', p('#9a4a0a', '#d1a54a', '#ffd89a', '#fff8ef', '#ffffff', '#2e1704', '#7b6446')],
    ],
    fonts: 'grand',
    look: 'heritage',
    effect: 'goldDust',
    intro: 'gates',
    kit: {
      dark: true,
      texture: 'paper',
      strength: 0.45,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      pair: { name: 'kalash' },
      top: { name: 'toran' },
      hang: { name: 'marigoldStrand' },
      centre: { name: 'mandala', tint: 'secondary' },
      scene: 'sarovar',
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      invocation: GANESH,
      card: 'framed',
    },
    layouts: [L('mandap', 'Ghat'), L('couple', 'Ganga'), L('jharokha', 'Haveli', { pair: { name: 'kalash' } }), L('arch', 'Deep'), L('temple', 'Mandir', { scene: 'sarovar' }), L('portrait', 'Shringar'), L('night', 'Aarti', { skyline: { name: 'diyaRow' } }), L('minimal', 'Resham'), L('photo', 'Yaadein')],
  },
  {
    key: 'chandni',
    word: 'Chandni',
    phrase: 'Silver moonlight on midnight navy, quietly modern',
    occasion: 'wedding',
    style: 'Modern',
    tags: ['modern', 'silver', 'night', 'minimal'],
    colors: ['Silver Night', p('#1b2a4a', '#aab4c3', '#e3e8f0', '#f4f6fa', '#ffffff', '#0d1526', '#5e6a80')],
    presets: [
      ['Charcoal & Rose', p('#2e2a30', '#c9a0a8', '#f0dde0', '#f8f6f7', '#ffffff', '#151316', '#6e6870')],
      ['Midnight & Gold', p('#14213d', '#d1a54a', '#efe2c0', '#f5f6f9', '#ffffff', '#0a1120', '#5b6680')],
    ],
    fonts: 'elegant',
    look: 'modern',
    effect: 'goldDust',
    intro: 'celestial',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'accent' },
      pair: { name: 'doves', tint: 'secondary' },
      centre: { name: 'medallion' },
      corner: { name: 'filigreeCorner', foil: true },
      skyline: { name: 'diyaRow' },
      scene: 'lotus',
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'accent' },
      card: 'minimal',
    },
    layouts: [L('night', 'Raat', { centre: { name: 'medallion' }, hang: { name: 'lantern' } }), L('couple', 'Saath'), L('arch', 'Mehrab'), L('minimal', 'Rekha'), L('photo', 'Lamhe'), L('portrait', 'Roop'), L('mandap', 'Sarovar'), L('split', 'Taara')],
  },
  {
    key: 'kohinoor',
    word: 'Kohinoor',
    phrase: 'Black and gold, with the shine of a jewel box',
    occasion: 'wedding',
    style: 'Luxury',
    tags: ['luxury', 'black', 'gold', 'royal'],
    colors: ['Onyx & Gold', p('#1c1814', '#d4af37', '#efe1b0', '#f7f4ec', '#fffdf6', '#0b0a08', '#6e6658')],
    presets: [
      ['Wine & Gold', p('#3d0d1c', '#d4af37', '#f0dcae', '#faf4f3', '#ffffff', '#1c060d', '#755c63')],
      ['Forest & Gold', p('#14301f', '#d4af37', '#e8e0b0', '#f5f7f2', '#ffffff', '#0a1810', '#5f6e62')],
    ],
    fonts: 'regal',
    look: 'royal',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: true,
      texture: 'grain',
      strength: 0.3,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'secondary' },
      pair: { name: 'elephant', tint: 'secondary' },
      top: { name: 'toran' },
      hang: { name: 'lantern' },
      centre: { name: 'medallion', foil: true },
      corner: { name: 'filigreeCorner', foil: true },
      scene: 'palace',
      skyline: { name: 'domes', foil: true },
      motif: { name: 'flourish', foil: true },
      sky: { name: 'stars', tint: 'secondary' },
      card: 'framed',
    },
    layouts: [L('night', 'Raat'), L('jharokha', 'Taj'), L('couple', 'Heera'), L('arch', 'Mehrab'), L('minimal', 'Noor'), L('photo', 'Chamak'), L('portrait', 'Ratna'), L('mandap', 'Mahal')],
  },
  {
    key: 'hariyali',
    word: 'Hariyali',
    phrase: 'Sage greenery and cream, softly boho',
    occasion: 'wedding',
    style: 'Floral',
    tags: ['boho', 'garden', 'green', 'modern'],
    colors: ['Sage', p('#4b6b4f', '#b0915c', '#dbe6d2', '#f7f8f2', '#ffffff', '#202b22', '#66736a')],
    presets: [
      ['Olive & Rust', p('#5a5a2a', '#b5652f', '#efd9bd', '#faf7ef', '#ffffff', '#24240f', '#6e6c58')],
      ['Eucalyptus', p('#3e6460', '#a8946a', '#d8e6e2', '#f5f8f7', '#ffffff', '#1c2b29', '#64746f')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.55,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      corner: { name: 'roseCluster', tint: '#6b8f6e' },
      top: { name: 'floralGarland', tint: '#6b8f6e' },
      pair: { name: 'bananaLeaf', tint: '#5f8a63' },
      scene: 'floral',
      motif: { name: 'doves', tint: 'secondary' },
      card: 'garland',
    },
    layouts: [L('floral', 'Bagh'), L('couple', 'Saawan'), L('arch', 'Patta'), L('minimal', 'Hara'), L('photo', 'Mausam'), L('mandap', 'Kunj'), L('split', 'Jhula')],
  },
  {
    key: 'gulaab',
    word: 'Gulaab',
    phrase: 'Blush pink and rose gold, romantic and modern',
    occasion: 'wedding',
    style: 'Romantic',
    tags: ['romantic', 'pink', 'floral', 'modern'],
    colors: ['Blush & Rose Gold', p('#9c3a5a', '#c08a6c', '#f6d0da', '#fff7f8', '#ffffff', '#33141f', '#88626e')],
    presets: [
      ['Peach & Gold', p('#b4583a', '#c9973f', '#ffd9c4', '#fff8f3', '#ffffff', '#33180e', '#86675a')],
      ['Mauve & Silver', p('#6e4a6e', '#a9a4b5', '#ead8ea', '#faf6fa', '#ffffff', '#271a27', '#776a77')],
    ],
    fonts: 'romantic',
    look: 'garden',
    effect: 'petals',
    intro: 'envelope',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.55,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      corner: { name: 'roseCluster', tint: '#7d9a7f' },
      top: { name: 'floralGarland', tint: '#7d9a7f' },
      scene: 'floral',
      motif: { name: 'rings', tint: 'secondary' },
      card: 'garland',
    },
    layouts: [L('floral', 'Ishq'), L('couple', 'Pyaar'), L('arch', 'Phool'), L('minimal', 'Pankhudi'), L('photo', 'Mohabbat'), L('split', 'Ada'), L('mandap', 'Kunj'), L('portrait', 'Jodi')],
  },
  {
    key: 'mitti',
    word: 'Mitti',
    phrase: 'Earthy terracotta, olive and clay, warm as a courtyard',
    occasion: 'wedding',
    style: 'Minimal',
    tags: ['boho', 'earthy', 'modern', 'minimal'],
    colors: ['Terracotta', p('#9a4a2a', '#b88a4a', '#efd6bf', '#faf4ee', '#fffdf9', '#2e1a10', '#7a6658')],
    presets: [
      ['Olive Clay', p('#5f6a32', '#b88a4a', '#e6e2c4', '#f7f7f0', '#ffffff', '#262a14', '#6c6e5a')],
      ['Indigo Clay', p('#2e4a6b', '#b88a4a', '#dbe2ea', '#f6f7f9', '#ffffff', '#142238', '#5f6a7a')],
    ],
    fonts: 'heritage',
    look: 'heritage',
    effect: 'petals',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.55,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      pair: { name: 'bananaLeaf', tint: '#6b7a3a' },
      top: { name: 'toran' },
      corner: { name: 'paisleyOrnate', tint: 'secondary' },
      skyline: { name: 'diyaRow' },
      motif: { name: 'lotus' },
      card: 'minimal',
    },
    layouts: [L('arch', 'Diya'), L('couple', 'Rang'), L('floral', 'Patte', { corner: { name: 'paisleyOrnate', tint: 'secondary' } }), L('minimal', 'Kumhar'), L('photo', 'Sondhi'), L('home', 'Aangan', { hero: { name: 'coupleHindu', tint: 'primary' } }), L('split', 'Chaak')],
  },
  {
    key: 'lavanya',
    word: 'Lavanya',
    phrase: 'Lavender and silver, dreamy as a summer sky',
    occasion: 'wedding',
    style: 'Dreamy',
    tags: ['dreamy', 'pastel', 'lavender', 'modern'],
    colors: ['Lavender', p('#5e4b8b', '#9fa3b8', '#e3dcf3', '#faf8fd', '#ffffff', '#221a36', '#6e6885')],
    presets: [
      ['Powder Blue', p('#3d5f8a', '#a9b2c3', '#d8e6f3', '#f6f9fc', '#ffffff', '#16243a', '#62708a')],
      ['Lilac & Gold', p('#6b3f7d', '#c9a24a', '#ecd9f0', '#fbf7fc', '#ffffff', '#26142e', '#76627c')],
    ],
    fonts: 'elegant',
    look: 'garden',
    effect: 'petals',
    intro: 'celestial',
    kit: {
      dark: false,
      texture: 'watercolor',
      strength: 0.5,
      foil: false,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'primary' },
      corner: { name: 'roseCluster', tint: '#8a9a8f' },
      top: { name: 'floralGarland', tint: '#8a9a8f' },
      float: { name: 'moonCloud', tint: 'secondary' },
      scene: 'lotus',
      motif: { name: 'doves', tint: 'secondary' },
      sky: { name: 'stars', tint: 'secondary' },
      card: 'sky',
    },
    layouts: [L('floral', 'Bloom'), L('couple', 'Sapna'), L('arch', 'Megh'), L('dream', 'Sitare', { hero: { name: 'coupleHindu', tint: 'primary' } }), L('minimal', 'Shaanti'), L('photo', 'Khwab'), L('mandap', 'Kamal')],
  },
  {
    key: 'sona',
    word: 'Sona',
    phrase: 'Ivory and gold foil, classic and quiet',
    occasion: 'wedding',
    style: 'Elegant',
    tags: ['classic', 'ivory', 'gold', 'minimal'],
    colors: ['Ivory & Gold', p('#5a4630', '#c9a24a', '#efe3c8', '#faf6ee', '#fffdf8', '#2a2016', '#7a6e5c')],
    presets: [
      ['Ivory & Maroon', p('#6b1a24', '#c9a24a', '#f3dcc8', '#fbf6f1', '#ffffff', '#2c0c10', '#7b5f5e')],
      ['Ivory & Emerald', p('#1f5a42', '#c9a24a', '#e2e6d2', '#f8f8f2', '#ffffff', '#122a20', '#62705f')],
    ],
    fonts: 'classic',
    look: 'classic',
    effect: 'goldDust',
    intro: 'seal',
    kit: {
      dark: false,
      texture: 'paper',
      strength: 0.5,
      foil: true,
      nameFont: 'script',
      hero: { name: 'coupleHindu', tint: 'secondary' },
      corner: { name: 'filigreeCorner', foil: true },
      centre: { name: 'medallion' },
      motif: { name: 'rings', tint: 'secondary' },
      card: 'minimal',
    },
    layouts: [L('minimal', 'Sutra'), L('photo', 'Pal'), L('arch', 'Kamaan'), L('couple', 'Jodi'), L('floral', 'Patti', { corner: { name: 'filigreeCorner', foil: true } }), L('portrait', 'Chitra'), L('split', 'Saath')],
  },
];
